import type { Measurable } from '@/types';

export const areaMeasurables: Measurable[] = [
  // Microscopic
  {
    id: 'virus-typical',
    name: 'Typical virus',
    description: 'Cross-sectional area of a typical virus',
    dimension: 'area',
    value: 0.008,
    unit: 'square-micrometer',
    valueMin: 0.003,
    valueMax: 0.07,
    tags: ['biology', 'microscopic'],
    relatability: 5,
    accuracy: 6,
  },
  {
    id: 'bacteria-typical',
    name: 'Typical bacterium',
    description: 'Cross-sectional area of a typical bacterium',
    dimension: 'area',
    value: 0.78,
    unit: 'square-micrometer',
    valueMin: 0.2,
    valueMax: 2,
    tags: ['biology', 'microscopic'],
    relatability: 6,
    accuracy: 6,
  },
  {
    id: 'red-blood-cell-area',
    name: 'Red blood cell',
    description: 'Surface area of a human red blood cell',
    dimension: 'area',
    value: 50,
    unit: 'square-micrometer',
    valueMin: 30,
    valueMax: 60,
    tags: ['biology', 'microscopic', 'human-body'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'human-cell-typical',
    name: 'Typical human cell',
    description: 'Average surface area of a typical human cell',
    dimension: 'area',
    value: 1250,
    unit: 'square-micrometer',
    valueMin: 700,
    valueMax: 2000,
    tags: ['biology', 'microscopic', 'human-body'],
    relatability: 6,
    accuracy: 6,
  },
  {
    id: 'human-hair-cross-section',
    name: 'Human hair cross-section',
    description: 'Cross-sectional area of a human hair',
    dimension: 'area',
    value: 7850,
    unit: 'square-micrometer',
    valueMin: 3000,
    valueMax: 12000,
    tags: ['biology', 'microscopic', 'human-body'],
    relatability: 8,
    accuracy: 7,
  },

  // Tiny
  {
    id: 'fingernail-area',
    name: 'Fingernail area',
    description: 'Area of an adult fingernail',
    dimension: 'area',
    value: 1,
    unit: 'square-centimeter',
    tags: ['human-body', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'us-penny-area',
    name: 'US penny',
    description: 'Area of a US one-cent coin',
    dimension: 'area',
    value: 2.85,
    unit: 'square-centimeter',
    tags: ['everyday', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'us-dime-area',
    name: 'US dime',
    description: 'Area of a US ten-cent coin',
    dimension: 'area',
    value: 2.52,
    unit: 'square-centimeter',
    tags: ['everyday', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'postage-stamp',
    name: 'Postage stamp',
    description: 'Area of a typical postage stamp',
    dimension: 'area',
    value: 4,
    unit: 'square-centimeter',
    valueMin: 3,
    valueMax: 6,
    tags: ['everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'us-quarter-area',
    name: 'US quarter',
    description: 'Area of a US twenty-five cent coin',
    dimension: 'area',
    value: 4.62,
    unit: 'square-centimeter',
    tags: ['everyday', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'euro-2-coin',
    name: '2 Euro coin',
    description: 'Area of a 2 Euro coin',
    dimension: 'area',
    value: 5.21,
    unit: 'square-centimeter',
    tags: ['everyday', 'european'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'business-card',
    name: 'Business card',
    description: 'Area of a standard business card',
    dimension: 'area',
    value: 45.4,
    unit: 'square-centimeter',
    tags: ['everyday', 'office', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'credit-card-area',
    name: 'Credit card area',
    description: 'Area of a standard credit card',
    dimension: 'area',
    value: 46,
    unit: 'square-centimeter',
    tags: ['everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'playing-card',
    name: 'Playing card',
    description: 'Area of a standard poker-size playing card',
    dimension: 'area',
    value: 56.5,
    unit: 'square-centimeter',
    tags: ['everyday', 'games', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'smartphone-screen',
    name: 'Smartphone screen',
    description: 'Screen area of a typical 6-inch smartphone',
    dimension: 'area',
    value: 90,
    unit: 'square-centimeter',
    valueMin: 70,
    valueMax: 120,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'index-card',
    name: 'Index card',
    description: 'Area of a standard 3x5 inch index card',
    dimension: 'area',
    value: 96.5,
    unit: 'square-centimeter',
    tags: ['everyday', 'office', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Small everyday objects
  {
    id: 'photo-4x6',
    name: '4x6 photo print',
    description: 'Area of a standard 4x6 inch photograph',
    dimension: 'area',
    value: 155,
    unit: 'square-centimeter',
    tags: ['everyday', 'photography', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'mass-market-paperback',
    name: 'Mass market paperback cover',
    description: 'Cover area of a typical mass market paperback book',
    dimension: 'area',
    value: 188.5,
    unit: 'square-centimeter',
    tags: ['everyday', 'reading', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'photo-5x7',
    name: '5x7 photo print',
    description: 'Area of a 5x7 inch photograph',
    dimension: 'area',
    value: 226,
    unit: 'square-centimeter',
    tags: ['everyday', 'photography', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'hardcover-book',
    name: 'Hardcover book cover',
    description: 'Cover area of a typical hardcover book',
    dimension: 'area',
    value: 350,
    unit: 'square-centimeter',
    valueMin: 300,
    valueMax: 400,
    tags: ['everyday', 'reading', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'ipad-screen',
    name: 'iPad screen',
    description: 'Screen area of a typical 10-11 inch iPad',
    dimension: 'area',
    value: 360,
    unit: 'square-centimeter',
    valueMin: 340,
    valueMax: 380,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'monitor-24-inch',
    name: '24-inch monitor',
    description: 'Screen area of a 24-inch computer monitor',
    dimension: 'area',
    value: 1293,
    unit: 'square-centimeter',
    tags: ['technology', 'office', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'monitor-27-inch',
    name: '27-inch monitor',
    description: 'Screen area of a 27-inch computer monitor',
    dimension: 'area',
    value: 1638,
    unit: 'square-centimeter',
    tags: ['technology', 'office', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'monitor-32-inch',
    name: '32-inch monitor',
    description: 'Screen area of a 32-inch computer monitor',
    dimension: 'area',
    value: 2212,
    unit: 'square-centimeter',
    tags: ['technology', 'office', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'photo-8x10',
    name: '8x10 photo print',
    description: 'Area of an 8x10 inch photograph',
    dimension: 'area',
    value: 516,
    unit: 'square-centimeter',
    tags: ['everyday', 'photography', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'pizza-12-inch',
    name: '12-inch pizza',
    description: 'Area of a 12-inch pizza',
    dimension: 'area',
    value: 729,
    unit: 'square-centimeter',
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'pizza-14-inch',
    name: '14-inch pizza',
    description: 'Area of a 14-inch pizza',
    dimension: 'area',
    value: 993,
    unit: 'square-centimeter',
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'pizza-16-inch',
    name: '16-inch pizza',
    description: 'Area of a 16-inch pizza',
    dimension: 'area',
    value: 1297,
    unit: 'square-centimeter',
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },

  // Paper and everyday
  {
    id: 'a4-paper',
    name: 'A4 paper',
    description: 'Area of an A4 sheet of paper',
    dimension: 'area',
    value: 0.0625,
    unit: 'square-meter',
    tags: ['everyday', 'office', 'international'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'letter-paper',
    name: 'US Letter paper',
    description: 'Area of a US Letter sheet of paper',
    dimension: 'area',
    value: 0.0603,
    unit: 'square-meter',
    tags: ['everyday', 'office', 'american'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'laptop-screen',
    name: 'Laptop screen',
    description: 'Screen area of a 15-inch laptop',
    dimension: 'area',
    value: 0.066,
    unit: 'square-meter',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'tv-55-inch',
    name: '55-inch TV',
    description: 'Screen area of a 55-inch television',
    dimension: 'area',
    value: 0.83,
    unit: 'square-meter',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'tv-65-inch',
    name: '65-inch TV',
    description: 'Screen area of a 65-inch television',
    dimension: 'area',
    value: 1.17,
    unit: 'square-meter',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'desk-surface',
    name: 'Office desk surface',
    description: 'Typical office desk surface area',
    dimension: 'area',
    value: 1.2,
    unit: 'square-meter',
    valueMin: 0.8,
    valueMax: 1.8,
    tags: ['office', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },

  // Room scale
  {
    id: 'bathroom-half',
    name: 'Half bathroom',
    description: 'Floor area of a powder room',
    dimension: 'area',
    value: 1.7,
    unit: 'square-meter',
    valueMin: 1.1,
    valueMax: 3,
    tags: ['housing', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'bathroom-full',
    name: 'Full bathroom',
    description: 'Floor area of a standard full bathroom',
    dimension: 'area',
    value: 3.7,
    unit: 'square-meter',
    valueMin: 3.3,
    valueMax: 10,
    tags: ['housing', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'solar-panel-residential-area',
    name: 'Residential solar panel',
    description: 'Area of a typical residential solar panel',
    dimension: 'area',
    value: 1.68,
    unit: 'square-meter',
    valueMin: 1.6,
    valueMax: 1.8,
    tags: ['technology', 'renewable-energy', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'solar-panel-commercial',
    name: 'Commercial solar panel',
    description: 'Area of a typical commercial solar panel',
    dimension: 'area',
    value: 2,
    unit: 'square-meter',
    tags: ['technology', 'renewable-energy', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'parking-space',
    name: 'Parking space',
    description: 'Standard parking space area',
    dimension: 'area',
    value: 15,
    unit: 'square-meter',
    tags: ['everyday', 'urban', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'small-bedroom',
    name: 'Small bedroom',
    description: 'Floor area of a small bedroom',
    dimension: 'area',
    value: 10,
    unit: 'square-meter',
    tags: ['housing', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'kitchen-typical',
    name: 'Typical kitchen',
    description: 'Floor area of an average US kitchen',
    dimension: 'area',
    value: 15,
    unit: 'square-meter',
    valueMin: 10,
    valueMax: 22,
    tags: ['housing', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'average-bedroom',
    name: 'Average bedroom',
    description: 'Floor area of an average bedroom',
    dimension: 'area',
    value: 13,
    unit: 'square-meter',
    valueMin: 10,
    valueMax: 16,
    tags: ['housing', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'studio-apartment',
    name: 'Studio apartment',
    description: 'Floor area of a typical studio apartment',
    dimension: 'area',
    value: 35,
    unit: 'square-meter',
    valueMin: 25,
    valueMax: 50,
    tags: ['housing', 'urban', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'residential-lot-median',
    name: 'Median residential lot',
    description: 'Median lot size for new US homes',
    dimension: 'area',
    value: 780,
    unit: 'square-meter',
    valueMin: 600,
    valueMax: 900,
    tags: ['housing', 'american'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'quarter-acre-lot',
    name: 'Quarter-acre lot',
    description: 'Traditional suburban lot size',
    dimension: 'area',
    value: 1012,
    unit: 'square-meter',
    tags: ['housing', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'billboard-standard',
    name: 'Standard billboard',
    description: 'Area of a standard 14x48 ft billboard',
    dimension: 'area',
    value: 62.4,
    unit: 'square-meter',
    tags: ['advertising', 'urban', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'one-bedroom-apartment',
    name: 'One-bedroom apartment',
    description: 'Floor area of a typical one-bedroom apartment',
    dimension: 'area',
    value: 68,
    unit: 'square-meter',
    valueMin: 50,
    valueMax: 80,
    tags: ['housing', 'urban', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'two-bedroom-apartment',
    name: 'Two-bedroom apartment',
    description: 'Floor area of a typical two-bedroom apartment',
    dimension: 'area',
    value: 102,
    unit: 'square-meter',
    valueMin: 85,
    valueMax: 120,
    tags: ['housing', 'urban', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Sports - Courts
  {
    id: 'table-tennis-table',
    name: 'Table tennis table',
    description: 'Surface area of a regulation ping pong table',
    dimension: 'area',
    value: 4.18,
    unit: 'square-meter',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'squash-court',
    name: 'Squash court',
    description: 'Floor area of a regulation squash court',
    dimension: 'area',
    value: 62.4,
    unit: 'square-meter',
    tags: ['sports', 'international'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'racquetball-court',
    name: 'Racquetball court',
    description: 'Floor area of a regulation racquetball court',
    dimension: 'area',
    value: 74.3,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'badminton-court',
    name: 'Badminton court',
    description: 'Area of a doubles badminton court',
    dimension: 'area',
    value: 81.74,
    unit: 'square-meter',
    tags: ['sports', 'international'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'volleyball-court',
    name: 'Volleyball court',
    description: 'Area of a regulation volleyball court',
    dimension: 'area',
    value: 162,
    unit: 'square-meter',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'tennis-court',
    name: 'Tennis court',
    description: 'Area of a singles tennis court',
    dimension: 'area',
    value: 196,
    unit: 'square-meter',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'basketball-court',
    name: 'Basketball court',
    description: 'Area of an NBA basketball court',
    dimension: 'area',
    value: 420,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'baseball-diamond',
    name: 'Baseball diamond',
    description: 'Area of the infield diamond',
    dimension: 'area',
    value: 751,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'olympic-swimming-pool',
    name: 'Olympic swimming pool',
    description: 'Surface area of an Olympic-size swimming pool',
    dimension: 'area',
    value: 1250,
    unit: 'square-meter',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'ice-hockey-rink',
    name: 'Ice hockey rink',
    description: 'Area of an NHL hockey rink',
    dimension: 'area',
    value: 1580,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 7,
    accuracy: 10,
  },

  // Sports - Fields
  {
    id: 'super-bowl-halftime-stage',
    name: 'Super Bowl halftime stage',
    description: 'Ground cloth area for halftime show',
    dimension: 'area',
    value: 817,
    unit: 'square-meter',
    tags: ['sports', 'entertainment', 'american'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'football-field-area',
    name: 'American football field',
    description: 'Playing area of an American football field',
    dimension: 'area',
    value: 5351,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'soccer-field-area',
    name: 'Soccer field',
    description: 'Area of a FIFA regulation soccer pitch',
    dimension: 'area',
    value: 7140,
    unit: 'square-meter',
    tags: ['sports', 'international'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'rugby-field',
    name: 'Rugby field',
    description: 'Playing area of a regulation rugby field',
    dimension: 'area',
    value: 8640,
    unit: 'square-meter',
    valueMin: 7208,
    valueMax: 10080,
    tags: ['sports', 'international'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'cricket-field-mcg',
    name: 'Melbourne Cricket Ground',
    description: 'Playing area of the MCG oval',
    dimension: 'area',
    value: 17720,
    unit: 'square-meter',
    tags: ['sports', 'international', 'australian'],
    relatability: 5,
    accuracy: 9,
  },

  // Buildings and landmarks
  {
    id: 'average-house-europe',
    name: 'Average European house',
    description: 'Floor area of an average European house',
    dimension: 'area',
    value: 100,
    unit: 'square-meter',
    valueMin: 76,
    valueMax: 120,
    tags: ['housing', 'european'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'average-house-usa',
    name: 'Average US house',
    description: 'Floor area of an average American house',
    dimension: 'area',
    value: 214,
    unit: 'square-meter',
    tags: ['housing', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'standard-cinema-screen',
    name: 'Standard cinema screen',
    description: 'Area of a typical movie theater screen',
    dimension: 'area',
    value: 180,
    unit: 'square-meter',
    valueMin: 80,
    valueMax: 290,
    tags: ['entertainment', 'technology', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'imax-screen',
    name: 'IMAX screen',
    description: 'Area of a typical IMAX movie screen',
    dimension: 'area',
    value: 465,
    unit: 'square-meter',
    valueMin: 300,
    valueMax: 1050,
    tags: ['entertainment', 'technology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'boeing-737-wing',
    name: 'Boeing 737 wing area',
    description: 'Total wing area of a Boeing 737',
    dimension: 'area',
    value: 125,
    unit: 'square-meter',
    tags: ['aviation', 'technology', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'boeing-747-wing',
    name: 'Boeing 747 wing area',
    description: 'Total wing area of a Boeing 747',
    dimension: 'area',
    value: 554,
    unit: 'square-meter',
    tags: ['aviation', 'technology', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'airbus-a380-wing',
    name: 'Airbus A380 wing area',
    description: 'Total wing area of an Airbus A380',
    dimension: 'area',
    value: 845,
    unit: 'square-meter',
    tags: ['aviation', 'technology', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'white-house-floor',
    name: 'White House floor area',
    description: 'Total floor area of the White House',
    dimension: 'area',
    value: 5100,
    unit: 'square-meter',
    tags: ['landmarks', 'architecture', 'american'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'walmart-store',
    name: 'Walmart Supercenter',
    description: 'Floor area of a typical Walmart Supercenter',
    dimension: 'area',
    value: 16700,
    unit: 'square-meter',
    tags: ['retail', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'aircraft-carrier-deck',
    name: 'Aircraft carrier deck',
    description: 'Flight deck area of USS Gerald R. Ford',
    dimension: 'area',
    value: 20234,
    unit: 'square-meter',
    tags: ['military', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'container-ship-deck',
    name: 'Container ship deck',
    description: 'Deck area of a large container ship',
    dimension: 'area',
    value: 24000,
    unit: 'square-meter',
    tags: ['maritime', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'vatican-museums',
    name: 'Vatican Museums',
    description: 'Gallery floor area of the Vatican Museums',
    dimension: 'area',
    value: 43000,
    unit: 'square-meter',
    tags: ['landmarks', 'culture', 'european'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'louvre-museum',
    name: 'Louvre Museum',
    description: 'Exhibition floor area of the Louvre',
    dimension: 'area',
    value: 72735,
    unit: 'square-meter',
    tags: ['landmarks', 'culture', 'european'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'empire-state-building-floor-area',
    name: 'Empire State Building',
    description: 'Total floor area of the Empire State Building',
    dimension: 'area',
    value: 257211,
    unit: 'square-meter',
    tags: ['landmarks', 'architecture', 'american'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'rose-bowl-stadium',
    name: 'Rose Bowl Stadium',
    description: 'Total area of the Rose Bowl Stadium',
    dimension: 'area',
    value: 232258,
    unit: 'square-meter',
    tags: ['sports', 'landmarks', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'att-stadium',
    name: 'AT&T Stadium',
    description: 'Total area of AT&T Stadium (Cowboys Stadium)',
    dimension: 'area',
    value: 278709,
    unit: 'square-meter',
    tags: ['sports', 'landmarks', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'pentagon',
    name: 'Pentagon floor area',
    description: 'Total floor area of the Pentagon',
    dimension: 'area',
    value: 603870,
    unit: 'square-meter',
    tags: ['landmarks', 'architecture', 'american', 'military'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'mall-of-america',
    name: 'Mall of America',
    description: 'Total floor area of Mall of America',
    dimension: 'area',
    value: 520257,
    unit: 'square-meter',
    tags: ['retail', 'landmarks', 'american'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'dubai-mall',
    name: 'Dubai Mall',
    description: 'Total floor area of Dubai Mall',
    dimension: 'area',
    value: 1200000,
    unit: 'square-meter',
    tags: ['retail', 'landmarks', 'asian'],
    relatability: 6,
    accuracy: 9,
  },

  // Agricultural
  {
    id: 'vineyard-small',
    name: 'Small vineyard',
    description: 'Area of a typical small vineyard',
    dimension: 'area',
    value: 10,
    unit: 'hectare',
    valueMin: 4,
    valueMax: 20,
    tags: ['agriculture', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'golf-course-18-hole',
    name: '18-hole golf course',
    description: 'Area of a typical 18-hole golf course',
    dimension: 'area',
    value: 60,
    unit: 'hectare',
    valueMin: 50,
    valueMax: 75,
    tags: ['sports', 'recreation', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'small-farm',
    name: 'Small farm',
    description: 'Area of a typical small family farm',
    dimension: 'area',
    value: 93,
    unit: 'hectare',
    valueMin: 40,
    valueMax: 150,
    tags: ['agriculture', 'universal'],
    relatability: 6,
    accuracy: 6,
  },
  {
    id: 'average-farm-usa',
    name: 'Average US farm',
    description: 'Area of an average American farm',
    dimension: 'area',
    value: 180,
    unit: 'hectare',
    tags: ['agriculture', 'american'],
    relatability: 6,
    accuracy: 8,
  },

  // Parks and recreation
  {
    id: 'city-block',
    name: 'City block',
    description: 'Area of a typical Manhattan city block',
    dimension: 'area',
    value: 2,
    unit: 'hectare',
    valueMin: 1.5,
    valueMax: 2.5,
    tags: ['urban', 'american'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'disneyland-park',
    name: 'Disneyland Park',
    description: 'Area of Disneyland in California',
    dimension: 'area',
    value: 2,
    unit: 'square-kilometer',
    tags: ['entertainment', 'landmarks', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'central-park',
    name: 'Central Park',
    description: 'Area of Central Park, NYC',
    dimension: 'area',
    value: 3.41,
    unit: 'square-kilometer',
    tags: ['parks', 'landmarks', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'golden-gate-park',
    name: 'Golden Gate Park',
    description: 'Area of Golden Gate Park, San Francisco',
    dimension: 'area',
    value: 4.12,
    unit: 'square-kilometer',
    tags: ['parks', 'landmarks', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'griffith-park',
    name: 'Griffith Park',
    description: 'Area of Griffith Park, Los Angeles',
    dimension: 'area',
    value: 17.4,
    unit: 'square-kilometer',
    tags: ['parks', 'landmarks', 'american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'disney-world',
    name: 'Walt Disney World',
    description: 'Total area of Walt Disney World Resort',
    dimension: 'area',
    value: 110,
    unit: 'square-kilometer',
    tags: ['entertainment', 'landmarks', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'lax-airport',
    name: 'LAX Airport',
    description: 'Total land area of Los Angeles International Airport',
    dimension: 'area',
    value: 14,
    unit: 'square-kilometer',
    tags: ['aviation', 'infrastructure', 'american'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'jfk-airport',
    name: 'JFK Airport',
    description: 'Total land area of John F. Kennedy Airport',
    dimension: 'area',
    value: 21,
    unit: 'square-kilometer',
    tags: ['aviation', 'infrastructure', 'american'],
    relatability: 6,
    accuracy: 9,
  },

  // Urban areas
  {
    id: 'manhattan-area',
    name: 'Manhattan',
    description: 'Land area of Manhattan island',
    dimension: 'area',
    value: 59.1,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'paris-city',
    name: 'Paris (city proper)',
    description: 'Area of Paris within the Périphérique',
    dimension: 'area',
    value: 105,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'european'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    description: 'Land area of San Francisco',
    dimension: 'area',
    value: 121,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'tokyo-central',
    name: 'Central Tokyo',
    description: 'Area of Tokyo special wards',
    dimension: 'area',
    value: 616,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'asian'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'new-york-city',
    name: 'New York City',
    description: 'Total land area of NYC five boroughs',
    dimension: 'area',
    value: 826,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'london-greater',
    name: 'Greater London',
    description: 'Area of Greater London',
    dimension: 'area',
    value: 1590,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'tokyo-metropolis',
    name: 'Tokyo Metropolis',
    description: 'Area of Tokyo Metropolis prefecture',
    dimension: 'area',
    value: 2194,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'asian'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'yosemite-national-park',
    name: 'Yosemite National Park',
    description: 'Total area of Yosemite National Park',
    dimension: 'area',
    value: 3074,
    unit: 'square-kilometer',
    tags: ['nature', 'parks', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'grand-canyon-national-park',
    name: 'Grand Canyon National Park',
    description: 'Total area of Grand Canyon National Park',
    dimension: 'area',
    value: 4862.9,
    unit: 'square-kilometer',
    tags: ['nature', 'parks', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'yellowstone-national-park',
    name: 'Yellowstone National Park',
    description: 'Total area of Yellowstone National Park',
    dimension: 'area',
    value: 8983,
    unit: 'square-kilometer',
    tags: ['nature', 'parks', 'american'],
    relatability: 7,
    accuracy: 10,
  },

  // Small states and countries
  {
    id: 'vatican-city',
    name: 'Vatican City',
    description: 'Area of Vatican City, the smallest country',
    dimension: 'area',
    value: 0.44,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'monaco',
    name: 'Monaco',
    description: 'Area of Monaco, second smallest country',
    dimension: 'area',
    value: 2.02,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'san-marino',
    name: 'San Marino',
    description: 'Area of San Marino',
    dimension: 'area',
    value: 61,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'liechtenstein',
    name: 'Liechtenstein',
    description: 'Area of Liechtenstein',
    dimension: 'area',
    value: 160,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'malta',
    name: 'Malta',
    description: 'Area of Malta',
    dimension: 'area',
    value: 316,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'maldives',
    name: 'Maldives',
    description: 'Area of Maldives, smallest Asian country',
    dimension: 'area',
    value: 300,
    unit: 'square-kilometer',
    tags: ['geography', 'asian'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    description: 'Area of Singapore',
    dimension: 'area',
    value: 719,
    unit: 'square-kilometer',
    tags: ['geography', 'asian'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'bahrain',
    name: 'Bahrain',
    description: 'Area of Bahrain',
    dimension: 'area',
    value: 765,
    unit: 'square-kilometer',
    tags: ['geography', 'asian'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'hong-kong',
    name: 'Hong Kong',
    description: 'Area of Hong Kong',
    dimension: 'area',
    value: 2755,
    unit: 'square-kilometer',
    tags: ['geography', 'asian'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'luxembourg',
    name: 'Luxembourg',
    description: 'Area of Luxembourg',
    dimension: 'area',
    value: 2586,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'rhode-island',
    name: 'Rhode Island',
    description: 'Area of Rhode Island (smallest US state)',
    dimension: 'area',
    value: 4001,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'delaware',
    name: 'Delaware',
    description: 'Area of Delaware',
    dimension: 'area',
    value: 5060,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'connecticut',
    name: 'Connecticut',
    description: 'Area of Connecticut',
    dimension: 'area',
    value: 14356,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 6,
    accuracy: 10,
  },

  // Islands
  {
    id: 'sicily',
    name: 'Sicily',
    description: 'Area of Sicily, largest Mediterranean island',
    dimension: 'area',
    value: 25711,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'european'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'great-britain',
    name: 'Great Britain',
    description: 'Area of the island of Great Britain',
    dimension: 'area',
    value: 209331,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'new-zealand',
    name: 'New Zealand',
    description: 'Total land area of New Zealand',
    dimension: 'area',
    value: 268021,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'international'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'japan-islands',
    name: 'Japan',
    description: 'Total land area of Japanese islands',
    dimension: 'area',
    value: 377000,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'asian'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'sumatra',
    name: 'Sumatra',
    description: 'Area of Sumatra island',
    dimension: 'area',
    value: 480848,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'asian'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'madagascar',
    name: 'Madagascar',
    description: 'Area of Madagascar island',
    dimension: 'area',
    value: 591896,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'african'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'borneo',
    name: 'Borneo',
    description: 'Area of Borneo, third largest island',
    dimension: 'area',
    value: 748168,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'asian'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'new-guinea',
    name: 'New Guinea',
    description: 'Area of New Guinea, second largest island',
    dimension: 'area',
    value: 785753,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'international'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'greenland',
    name: 'Greenland',
    description: 'Area of Greenland, largest island',
    dimension: 'area',
    value: 2166086,
    unit: 'square-kilometer',
    tags: ['geography', 'islands', 'arctic'],
    relatability: 6,
    accuracy: 10,
  },

  // States and regions
  {
    id: 'massachusetts',
    name: 'Massachusetts',
    description: 'Area of Massachusetts',
    dimension: 'area',
    value: 27336,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'new-york-state',
    name: 'New York State',
    description: 'Area of New York State',
    dimension: 'area',
    value: 141297,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'florida',
    name: 'Florida',
    description: 'Area of Florida',
    dimension: 'area',
    value: 170310,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'california',
    name: 'California',
    description: 'Area of California',
    dimension: 'area',
    value: 423970,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'texas',
    name: 'Texas',
    description: 'Area of Texas',
    dimension: 'area',
    value: 695662,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'alaska',
    name: 'Alaska',
    description: 'Area of Alaska (largest US state)',
    dimension: 'area',
    value: 1717856,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 7,
    accuracy: 10,
  },

  // Countries
  {
    id: 'belgium',
    name: 'Belgium',
    description: 'Area of Belgium',
    dimension: 'area',
    value: 30689,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    description: 'Area of the Netherlands',
    dimension: 'area',
    value: 41850,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    description: 'Area of the United Kingdom',
    dimension: 'area',
    value: 244820,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'italy',
    name: 'Italy',
    description: 'Area of Italy',
    dimension: 'area',
    value: 301220,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'germany',
    name: 'Germany',
    description: 'Area of Germany',
    dimension: 'area',
    value: 357021,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'spain',
    name: 'Spain',
    description: 'Area of Spain',
    dimension: 'area',
    value: 504782,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'france',
    name: 'France',
    description: 'Area of metropolitan France',
    dimension: 'area',
    value: 643801,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'egypt',
    name: 'Egypt',
    description: 'Area of Egypt',
    dimension: 'area',
    value: 1001450,
    unit: 'square-kilometer',
    tags: ['geography', 'african'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'south-africa',
    name: 'South Africa',
    description: 'Area of South Africa',
    dimension: 'area',
    value: 1221037,
    unit: 'square-kilometer',
    tags: ['geography', 'african'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'mexico',
    name: 'Mexico',
    description: 'Area of Mexico',
    dimension: 'area',
    value: 1964375,
    unit: 'square-kilometer',
    tags: ['geography', 'north-american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'india',
    name: 'India',
    description: 'Area of India',
    dimension: 'area',
    value: 3287263,
    unit: 'square-kilometer',
    tags: ['geography', 'asian'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'australia',
    name: 'Australia',
    description: 'Area of Australia',
    dimension: 'area',
    value: 7692024,
    unit: 'square-kilometer',
    tags: ['geography', 'international'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'brazil',
    name: 'Brazil',
    description: 'Area of Brazil',
    dimension: 'area',
    value: 8515770,
    unit: 'square-kilometer',
    tags: ['geography', 'south-american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'china',
    name: 'China',
    description: 'Area of China',
    dimension: 'area',
    value: 9600000,
    unit: 'square-kilometer',
    tags: ['geography', 'asian'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'united-states',
    name: 'United States',
    description: 'Total area of the United States',
    dimension: 'area',
    value: 9833517,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'canada',
    name: 'Canada',
    description: 'Area of Canada',
    dimension: 'area',
    value: 9984670,
    unit: 'square-kilometer',
    tags: ['geography', 'north-american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'russia',
    name: 'Russia',
    description: 'Area of Russia, largest country',
    dimension: 'area',
    value: 17075400,
    unit: 'square-kilometer',
    tags: ['geography', 'international'],
    relatability: 7,
    accuracy: 10,
  },

  // Lakes
  {
    id: 'lake-tahoe-area',
    name: 'Lake Tahoe',
    description: 'Surface area of Lake Tahoe',
    dimension: 'area',
    value: 490,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'lake-ontario',
    name: 'Lake Ontario',
    description: 'Surface area of Lake Ontario',
    dimension: 'area',
    value: 19009,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'north-american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'lake-michigan',
    name: 'Lake Michigan',
    description: 'Surface area of Lake Michigan',
    dimension: 'area',
    value: 57750,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'lake-superior-area',
    name: 'Lake Superior',
    description: 'Surface area of Lake Superior',
    dimension: 'area',
    value: 82103,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'north-american'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'caspian-sea-area',
    name: 'Caspian Sea',
    description: 'Surface area of the Caspian Sea',
    dimension: 'area',
    value: 371000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'international'],
    relatability: 6,
    accuracy: 9,
  },

  // Seas and oceans
  {
    id: 'mediterranean-sea-area',
    name: 'Mediterranean Sea',
    description: 'Area of the Mediterranean Sea',
    dimension: 'area',
    value: 2500000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'caribbean-sea',
    name: 'Caribbean Sea',
    description: 'Area of the Caribbean Sea',
    dimension: 'area',
    value: 2754000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'international'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'indian-ocean',
    name: 'Indian Ocean',
    description: 'Area of the Indian Ocean',
    dimension: 'area',
    value: 70560000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'atlantic-ocean',
    name: 'Atlantic Ocean',
    description: 'Area of the Atlantic Ocean',
    dimension: 'area',
    value: 106400000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'pacific-ocean',
    name: 'Pacific Ocean',
    description: 'Area of the Pacific Ocean',
    dimension: 'area',
    value: 165250000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Deserts and forests
  {
    id: 'gobi-desert',
    name: 'Gobi Desert',
    description: 'Area of the Gobi Desert',
    dimension: 'area',
    value: 1295000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'asian'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'amazon-rainforest',
    name: 'Amazon Rainforest',
    description: 'Area of the Amazon rainforest',
    dimension: 'area',
    value: 5500000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'sahara-desert',
    name: 'Sahara Desert',
    description: 'Area of the Sahara Desert',
    dimension: 'area',
    value: 9200000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'african'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'antarctica-desert',
    name: 'Antarctic Desert',
    description: 'Area of Antarctica, largest desert',
    dimension: 'area',
    value: 14200000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'polar'],
    relatability: 6,
    accuracy: 9,
  },

  // Continents
  {
    id: 'europe',
    name: 'Europe',
    description: 'Land area of Europe',
    dimension: 'area',
    value: 10186000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'south-america',
    name: 'South America',
    description: 'Land area of South America',
    dimension: 'area',
    value: 17840000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'north-america',
    name: 'North America',
    description: 'Land area of North America',
    dimension: 'area',
    value: 24709000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'africa',
    name: 'Africa',
    description: 'Area of the African continent',
    dimension: 'area',
    value: 30370000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'asia',
    name: 'Asia',
    description: 'Land area of Asia',
    dimension: 'area',
    value: 44580000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 10,
  },

  // Earth surface areas
  {
    id: 'earth-land-area',
    name: "Earth's land area",
    description: 'Total land surface of Earth',
    dimension: 'area',
    value: 148900000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'earth-surface',
    name: "Earth's surface",
    description: 'Total surface area of Earth',
    dimension: 'area',
    value: 510100000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },

  // Astronomical
  {
    id: 'moon-surface',
    name: 'Moon surface area',
    description: 'Total surface area of the Moon',
    dimension: 'area',
    value: 37900000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'mars-surface-area',
    name: 'Mars surface area',
    description: 'Total surface area of Mars',
    dimension: 'area',
    value: 145000000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'venus-surface-area',
    name: 'Venus surface area',
    description: 'Total surface area of Venus',
    dimension: 'area',
    value: 460000000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'jupiter-surface',
    name: 'Jupiter surface area',
    description: 'Total surface area of Jupiter',
    dimension: 'area',
    value: 61420000000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'sun-surface',
    name: 'Sun surface area',
    description: 'Total surface area of the Sun',
    dimension: 'area',
    value: 6.09e12,
    unit: 'square-kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
];
