import type { Measurable } from '@/types';

export const areaMeasurables: Measurable[] = [
  // Tiny
  {
    id: 'fingernail-area',
    name: 'Fingernail area',
    description: 'Area of an adult fingernail',
    dimension: 'area',
    value: 1,
    unit: 'square-centimeter',
    tags: ['human-body', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'postage-stamp',
    name: 'Postage stamp',
    description: 'Area of a standard US postage stamp',
    dimension: 'area',
    value: 5.8,
    unit: 'square-centimeter',
    tags: ['everyday', 'american'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'credit-card-area',
    name: 'Credit card area',
    description: 'Area of a standard credit card',
    dimension: 'area',
    value: 46,
    unit: 'square-centimeter',
    tags: ['everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'smartphone-screen',
    name: 'Smartphone screen',
    description: 'Screen area of a typical smartphone',
    dimension: 'area',
    value: 90,
    unit: 'square-centimeter',
    valueMin: 70,
    valueMax: 120,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Paper and everyday
  {
    id: 'a4-paper',
    name: 'A4 paper',
    description: 'Area of an A4 sheet of paper',
    dimension: 'area',
    value: 0.0625,
    unit: 'square-meter',
    tags: ['everyday', 'office', 'international'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'letter-paper',
    name: 'US Letter paper',
    description: 'Area of a US Letter sheet of paper',
    dimension: 'area',
    value: 0.0603,
    unit: 'square-meter',
    tags: ['everyday', 'office', 'american'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'laptop-screen',
    name: 'Laptop screen',
    description: 'Screen area of a 15-inch laptop',
    dimension: 'area',
    value: 0.066,
    unit: 'square-meter',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'desk-surface',
    name: 'Office desk surface',
    description: 'Typical office desk surface area',
    dimension: 'area',
    value: 1.2,
    unit: 'square-meter',
    valueMin: 0.8,
    valueMax: 1.8,
    tags: ['office', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },

  // Room scale
  {
    id: 'parking-space',
    name: 'Parking space',
    description: 'Standard parking space area',
    dimension: 'area',
    value: 15,
    unit: 'square-meter',
    tags: ['everyday', 'urban', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'small-bedroom',
    name: 'Small bedroom',
    description: 'Floor area of a small bedroom',
    dimension: 'area',
    value: 10,
    unit: 'square-meter',
    tags: ['housing', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'studio-apartment',
    name: 'Studio apartment',
    description: 'Floor area of a typical studio apartment',
    dimension: 'area',
    value: 35,
    unit: 'square-meter',
    valueMin: 25,
    valueMax: 50,
    tags: ['housing', 'urban', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Sports
  {
    id: 'tennis-court',
    name: 'Tennis court',
    description: 'Area of a singles tennis court',
    dimension: 'area',
    value: 196,
    unit: 'square-meter',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'basketball-court',
    name: 'Basketball court',
    description: 'Area of an NBA basketball court',
    dimension: 'area',
    value: 420,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'ice-hockey-rink',
    name: 'Ice hockey rink',
    description: 'Area of an NHL hockey rink',
    dimension: 'area',
    value: 1580,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'football-field-area',
    name: 'American football field',
    description: 'Playing area of an American football field',
    dimension: 'area',
    value: 5351,
    unit: 'square-meter',
    tags: ['sports', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'soccer-field-area',
    name: 'Soccer field',
    description: 'Area of a regulation soccer pitch',
    dimension: 'area',
    value: 7140,
    unit: 'square-meter',
    valueMin: 6400,
    valueMax: 8250,
    tags: ['sports', 'international'],
    relatability: 9,
    accuracy: 8,
  },

  // Buildings and landmarks
  {
    id: 'white-house-floor',
    name: 'White House floor area',
    description: 'Total floor area of the White House',
    dimension: 'area',
    value: 5100,
    unit: 'square-meter',
    tags: ['landmarks', 'architecture', 'american'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'walmart-store',
    name: 'Walmart Supercenter',
    description: 'Floor area of a typical Walmart Supercenter',
    dimension: 'area',
    value: 16700,
    unit: 'square-meter',
    tags: ['retail', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'pentagon',
    name: 'Pentagon floor area',
    description: 'Total floor area of the Pentagon',
    dimension: 'area',
    value: 620000,
    unit: 'square-meter',
    tags: ['landmarks', 'architecture', 'american', 'military'],
    relatability: 6,
    accuracy: 9,
  },

  // Urban areas
  {
    id: 'city-block',
    name: 'City block',
    description: 'Area of a typical Manhattan city block',
    dimension: 'area',
    value: 2,
    unit: 'hectare',
    valueMin: 1.5,
    valueMax: 2.5,
    tags: ['urban', 'american'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'central-park',
    name: 'Central Park',
    description: 'Area of Central Park, NYC',
    dimension: 'area',
    value: 3.41,
    unit: 'square-kilometer',
    tags: ['parks', 'landmarks', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'manhattan-area',
    name: 'Manhattan',
    description: 'Land area of Manhattan island',
    dimension: 'area',
    value: 59.1,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    description: 'Land area of San Francisco',
    dimension: 'area',
    value: 121,
    unit: 'square-kilometer',
    tags: ['geography', 'urban', 'american'],
    relatability: 7,
    accuracy: 10,
  },

  // States/Countries
  {
    id: 'rhode-island',
    name: 'Rhode Island',
    description: 'Area of Rhode Island (smallest US state)',
    dimension: 'area',
    value: 4001,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'texas',
    name: 'Texas',
    description: 'Area of Texas',
    dimension: 'area',
    value: 695662,
    unit: 'square-kilometer',
    tags: ['geography', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'france',
    name: 'France',
    description: 'Area of metropolitan France',
    dimension: 'area',
    value: 643801,
    unit: 'square-kilometer',
    tags: ['geography', 'european'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'australia',
    name: 'Australia',
    description: 'Area of Australia',
    dimension: 'area',
    value: 7692024,
    unit: 'square-kilometer',
    tags: ['geography', 'international'],
    relatability: 7,
    accuracy: 10,
  },

  // Continental/Global
  {
    id: 'amazon-rainforest',
    name: 'Amazon Rainforest',
    description: 'Area of the Amazon rainforest',
    dimension: 'area',
    value: 5500000,
    unit: 'square-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'africa',
    name: 'Africa',
    description: 'Area of the African continent',
    dimension: 'area',
    value: 30370000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'earth-surface',
    name: "Earth's surface",
    description: 'Total surface area of Earth',
    dimension: 'area',
    value: 510100000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'earth-land-area',
    name: "Earth's land area",
    description: 'Total land surface of Earth',
    dimension: 'area',
    value: 148900000,
    unit: 'square-kilometer',
    tags: ['geography', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Astronomical
  {
    id: 'moon-surface',
    name: 'Moon surface area',
    description: 'Total surface area of the Moon',
    dimension: 'area',
    value: 37900000,
    unit: 'square-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'sun-surface',
    name: 'Sun surface area',
    description: 'Total surface area of the Sun',
    dimension: 'area',
    value: 6.09e12,
    unit: 'square-kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
];
