import type { Measurable } from '@/types';

export const dataMeasurables: Measurable[] = [
  // Tiny - Character level
  {
    id: 'single-character',
    name: 'Single text character',
    description: 'A single ASCII character like "A"',
    dimension: 'data',
    value: 1,
    unit: 'byte',
    tags: ['text', 'universal', 'everyday'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'text-word',
    name: 'Average English word',
    description: 'Average word with 5 characters plus a space',
    dimension: 'data',
    value: 6,
    unit: 'byte',
    tags: ['text', 'universal', 'everyday'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'emoji',
    name: 'Emoji character',
    description: 'A single emoji in Unicode (UTF-8)',
    dimension: 'data',
    value: 4,
    unit: 'byte',
    tags: ['text', 'social-media', 'universal'],
    relatability: 10,
    accuracy: 9,
  },

  // Small text
  {
    id: 'sms-message',
    name: 'SMS text message',
    description: 'Standard 160-character SMS message',
    dimension: 'data',
    value: 160,
    unit: 'byte',
    tags: ['communication', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'tweet',
    name: 'Twitter/X post',
    description: 'Standard tweet at 280 characters (UTF-8)',
    dimension: 'data',
    value: 280,
    unit: 'byte',
    valueMax: 560,
    tags: ['social-media', 'communication', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'short-email',
    name: 'Short email',
    description: 'Brief text-only email message',
    dimension: 'data',
    value: 10,
    unit: 'kilobyte',
    valueMin: 5,
    valueMax: 20,
    tags: ['communication', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Small files
  {
    id: 'qr-code',
    name: 'QR code data',
    description: 'Maximum data capacity of a QR code',
    dimension: 'data',
    value: 2.953,
    unit: 'kilobyte',
    tags: ['technology', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'word-document-page',
    name: 'Word document page',
    description: 'Single page of text in a document',
    dimension: 'data',
    value: 2,
    unit: 'kilobyte',
    valueMin: 1,
    valueMax: 5,
    tags: ['office', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'low-res-photo',
    name: 'Low-resolution photo',
    description: 'Small JPEG image for web use',
    dimension: 'data',
    value: 100,
    unit: 'kilobyte',
    valueMin: 50,
    valueMax: 200,
    tags: ['photography', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Medium files - Images and documents
  {
    id: 'ebook-novel',
    name: 'Ebook novel',
    description: 'Average ebook file (text-only, EPUB format)',
    dimension: 'data',
    value: 2.6,
    unit: 'megabyte',
    valueMin: 1,
    valueMax: 5,
    tags: ['reading', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'smartphone-photo',
    name: 'Smartphone photo',
    description: 'Typical photo from a modern smartphone',
    dimension: 'data',
    value: 3.5,
    unit: 'megabyte',
    valueMin: 2,
    valueMax: 5,
    tags: ['photography', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'mp3-song',
    name: 'MP3 song',
    description: 'Compressed audio file of a 3-4 minute song',
    dimension: 'data',
    value: 4,
    unit: 'megabyte',
    valueMin: 3,
    valueMax: 10,
    tags: ['music', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'ebook-illustrated',
    name: 'Illustrated ebook',
    description: 'Ebook with images (cookbook, graphic novel)',
    dimension: 'data',
    value: 20,
    unit: 'megabyte',
    valueMin: 10,
    valueMax: 50,
    tags: ['reading', 'universal'],
    relatability: 7,
    accuracy: 7,
  },

  // Storage media
  {
    id: 'floppy-disk',
    name: '3.5" floppy disk',
    description: 'Standard high-density floppy disk capacity',
    dimension: 'data',
    value: 1.44,
    unit: 'megabyte',
    tags: ['technology', 'vintage', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'zip-disk-100',
    name: 'Zip disk (100MB)',
    description: 'Original Iomega Zip disk capacity',
    dimension: 'data',
    value: 100,
    unit: 'megabyte',
    tags: ['technology', 'vintage'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'cd-rom',
    name: 'CD-ROM',
    description: 'Standard compact disc storage capacity',
    dimension: 'data',
    value: 700,
    unit: 'megabyte',
    valueMin: 650,
    valueMax: 700,
    tags: ['technology', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'human-genome',
    name: 'Human genome',
    description: 'Complete human DNA sequence (uncompressed)',
    dimension: 'data',
    value: 800,
    unit: 'megabyte',
    valueMin: 750,
    valueMax: 875,
    tags: ['biology', 'science', 'universal'],
    relatability: 8,
    accuracy: 9,
  },

  // Video and large files
  {
    id: 'hour-music',
    name: 'Hour of MP3 music',
    description: 'One hour of compressed audio',
    dimension: 'data',
    value: 60,
    unit: 'megabyte',
    valueMin: 40,
    valueMax: 80,
    tags: ['music', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'minute-4k-video',
    name: 'Minute of 4K video',
    description: 'One minute of compressed 4K video (H.264)',
    dimension: 'data',
    value: 350,
    unit: 'megabyte',
    valueMin: 200,
    valueMax: 500,
    tags: ['video', 'technology', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'dvd-movie',
    name: 'DVD movie',
    description: 'Standard definition movie on DVD',
    dimension: 'data',
    value: 4.7,
    unit: 'gigabyte',
    valueMin: 4,
    valueMax: 6,
    tags: ['video', 'entertainment', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'wikipedia-text-dump',
    name: 'Wikipedia text dump',
    description: 'All English Wikipedia articles (compressed)',
    dimension: 'data',
    value: 24.87,
    unit: 'gigabyte',
    tags: ['internet', 'knowledge', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'blu-ray-movie',
    name: 'Blu-ray movie',
    description: 'HD movie on single-layer Blu-ray disc',
    dimension: 'data',
    value: 25,
    unit: 'gigabyte',
    valueMin: 20,
    valueMax: 30,
    tags: ['video', 'entertainment', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'usb-flash-drive-32gb',
    name: '32GB USB flash drive',
    description: 'Common USB flash drive capacity',
    dimension: 'data',
    value: 32,
    unit: 'gigabyte',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'hour-4k-video',
    name: 'Hour of 4K video',
    description: 'One hour of compressed 4K video',
    dimension: 'data',
    value: 45,
    unit: 'gigabyte',
    valueMin: 30,
    valueMax: 80,
    tags: ['video', 'technology', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'dual-layer-blu-ray',
    name: 'Dual-layer Blu-ray disc',
    description: 'Standard dual-layer Blu-ray capacity',
    dimension: 'data',
    value: 50,
    unit: 'gigabyte',
    tags: ['video', 'technology', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'usb-flash-drive-64gb',
    name: '64GB USB flash drive',
    description: 'Popular USB flash drive size',
    dimension: 'data',
    value: 64,
    unit: 'gigabyte',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: '4k-uhd-movie',
    name: '4K UHD movie',
    description: 'Ultra HD movie file (uncompressed rip)',
    dimension: 'data',
    value: 65,
    unit: 'gigabyte',
    valueMin: 55,
    valueMax: 75,
    tags: ['video', 'entertainment', 'technology'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'aaa-video-game',
    name: 'AAA video game',
    description: 'Modern triple-A game install size',
    dimension: 'data',
    value: 70,
    unit: 'gigabyte',
    valueMin: 50,
    valueMax: 150,
    tags: ['gaming', 'technology', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'wikipedia-full-dump',
    name: 'Wikipedia complete dump',
    description: 'All English Wikipedia articles with images (uncompressed)',
    dimension: 'data',
    value: 109,
    unit: 'gigabyte',
    tags: ['internet', 'knowledge', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'smartphone-128gb',
    name: '128GB smartphone storage',
    description: 'Standard smartphone storage capacity',
    dimension: 'data',
    value: 128,
    unit: 'gigabyte',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'call-of-duty-game',
    name: 'Call of Duty Modern Warfare III',
    description: 'One of the largest modern video games',
    dimension: 'data',
    value: 300,
    unit: 'gigabyte',
    valueMin: 250,
    valueMax: 350,
    tags: ['gaming', 'technology'],
    relatability: 7,
    accuracy: 8,
  },

  // Terabyte scale
  {
    id: 'laptop-hard-drive',
    name: 'Laptop hard drive',
    description: 'Typical laptop HDD/SSD capacity',
    dimension: 'data',
    value: 1,
    unit: 'terabyte',
    valueMin: 0.5,
    valueMax: 2,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'wikimedia-commons',
    name: 'Wikimedia Commons',
    description: 'All Wikipedia images and media files',
    dimension: 'data',
    value: 428,
    unit: 'terabyte',
    tags: ['internet', 'knowledge', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'library-of-congress-print',
    name: 'Library of Congress (text)',
    description: 'All printed materials digitized as text',
    dimension: 'data',
    value: 10,
    unit: 'terabyte',
    tags: ['knowledge', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'wikipedia-edit-history',
    name: 'Wikipedia edit history',
    description: 'Complete edit history of English Wikipedia',
    dimension: 'data',
    value: 26,
    unit: 'terabyte',
    valueMin: 19,
    valueMax: 26,
    tags: ['internet', 'knowledge', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Petabyte scale
  {
    id: 'library-of-congress-digital',
    name: 'Library of Congress digital',
    description: 'Digital collections of the Library of Congress',
    dimension: 'data',
    value: 21,
    unit: 'petabyte',
    tags: ['knowledge', 'american'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'google-daily-processing',
    name: "Google's daily data processing",
    description: 'Data processed by Google every day',
    dimension: 'data',
    value: 2500,
    unit: 'petabyte',
    tags: ['internet', 'technology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'google-storage',
    name: 'Google total storage',
    description: 'Estimated total storage across all Google data centers',
    dimension: 'data',
    value: 15,
    unit: 'exabyte',
    valueMin: 10,
    valueMax: 20,
    tags: ['internet', 'technology', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'global-daily-data',
    name: 'Global daily data generation',
    description: 'Total data generated worldwide each day (2025)',
    dimension: 'data',
    value: 463,
    unit: 'exabyte',
    tags: ['internet', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'global-datasphere-2025',
    name: 'Global datasphere',
    description: 'Total digital data stored worldwide in 2025',
    dimension: 'data',
    value: 181,
    unit: 'zettabyte',
    tags: ['internet', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
];
