import type { Measurable } from '@/types';

export const energyMeasurables: Measurable[] = [
  // Quantum and particle physics
  {
    id: 'visible-light-photon',
    name: 'Visible light photon',
    description: 'Energy of a single photon of green light (550 nm)',
    dimension: 'energy',
    value: 2.25,
    unit: 'electronvolt',
    tags: ['quantum', 'physics', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'radio-wave-photon',
    name: 'Radio wave photon',
    description: 'Energy of a photon from FM radio (100 MHz)',
    dimension: 'energy',
    value: 4.1357e-7,
    unit: 'electronvolt',
    tags: ['quantum', 'physics', 'universal'],
    relatability: 4,
    accuracy: 9,
  },
  {
    id: 'x-ray-photon',
    name: 'X-ray photon',
    description: 'Energy of a typical medical X-ray photon',
    dimension: 'energy',
    value: 60,
    unit: 'kiloelectronvolt',
    tags: ['quantum', 'physics', 'medical', 'universal'],
    relatability: 6,
    accuracy: 8,
  },

  // Molecular and chemical
  {
    id: 'atp-hydrolysis',
    name: 'ATP hydrolysis',
    description: 'Energy released when one ATP molecule is broken down in cells',
    dimension: 'energy',
    value: 30.5,
    unit: 'kilojoule',
    tags: ['biology', 'chemistry', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'glucose-photosynthesis',
    name: 'Glucose synthesis',
    description: 'Energy required to create one glucose molecule via photosynthesis',
    dimension: 'energy',
    value: 686,
    unit: 'kilocalorie',
    tags: ['biology', 'chemistry', 'nature', 'universal'],
    relatability: 6,
    accuracy: 8,
  },

  // Human body - tiny
  {
    id: 'single-pushup',
    name: 'Single pushup',
    description: 'Energy burned doing one pushup',
    dimension: 'energy',
    value: 1.9,
    unit: 'joule',
    valueMin: 1.25,
    valueMax: 2.5,
    tags: ['human-body', 'exercise', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'kinetic-energy-walking',
    name: 'Person walking',
    description: 'Kinetic energy of a 75 kg person walking at 1.5 m/s',
    dimension: 'energy',
    value: 84.4,
    unit: 'joule',
    tags: ['human-body', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'kinetic-energy-running',
    name: 'Person running',
    description: 'Kinetic energy of a 75 kg person running at 3 m/s',
    dimension: 'energy',
    value: 337.5,
    unit: 'joule',
    tags: ['human-body', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Food and nutrition
  {
    id: 'small-banana',
    name: 'Small banana',
    description: 'Energy content of a small banana',
    dimension: 'energy',
    value: 85,
    unit: 'kilocalorie',
    valueMin: 80,
    valueMax: 90,
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'snickers-bar-energy',
    name: 'Snickers bar',
    description: 'Energy content of a standard 1.86 oz Snickers bar',
    dimension: 'energy',
    value: 250,
    unit: 'kilocalorie',
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'big-mac',
    name: 'Big Mac',
    description: "Energy content of a McDonald's Big Mac",
    dimension: 'energy',
    value: 550,
    unit: 'kilocalorie',
    tags: ['food', 'everyday', 'american'],
    relatability: 10,
    accuracy: 9,
  },

  // Human metabolism
  {
    id: 'basal-metabolic-rate-male',
    name: 'Daily BMR (male)',
    description: 'Basal metabolic rate for average adult male per day',
    dimension: 'energy',
    value: 1696,
    unit: 'kilocalorie',
    valueMin: 1600,
    valueMax: 1800,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'basal-metabolic-rate-female',
    name: 'Daily BMR (female)',
    description: 'Basal metabolic rate for average adult female per day',
    dimension: 'energy',
    value: 1410,
    unit: 'kilocalorie',
    valueMin: 1300,
    valueMax: 1500,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'daily-energy-active',
    name: 'Daily energy (active person)',
    description: 'Total daily energy expenditure for an active 70 kg person',
    dimension: 'energy',
    value: 4000,
    unit: 'kilocalorie',
    valueMin: 3000,
    valueMax: 5000,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 6,
  },

  // Batteries - small
  {
    id: 'aa-battery-energy',
    name: 'AA battery',
    description: 'Energy stored in a typical alkaline AA battery',
    dimension: 'energy',
    value: 14400,
    unit: 'joule',
    valueMin: 13500,
    valueMax: 16200,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'car-battery',
    name: 'Car battery',
    description: 'Energy stored in a typical 60 Ah car battery',
    dimension: 'energy',
    value: 2.6,
    unit: 'megajoule',
    valueMin: 2.2,
    valueMax: 3.7,
    tags: ['vehicles', 'technology', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'smartphone-battery',
    name: 'Smartphone battery',
    description: 'Energy stored in a typical smartphone battery (4000 mAh at 3.7V)',
    dimension: 'energy',
    value: 53.3,
    unit: 'kilojoule',
    valueMin: 40,
    valueMax: 70,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'laptop-battery',
    name: 'Laptop battery',
    description: 'Energy stored in a typical laptop battery',
    dimension: 'energy',
    value: 198,
    unit: 'kilojoule',
    valueMin: 144,
    valueMax: 360,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'tesla-model-3-battery',
    name: 'Tesla Model 3 battery',
    description: 'Energy stored in Tesla Model 3 Long Range battery pack',
    dimension: 'energy',
    value: 82,
    unit: 'kilowatt-hour',
    valueMin: 62,
    valueMax: 82,
    tags: ['vehicles', 'technology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Household appliances
  {
    id: 'microwave-heating',
    name: 'Microwave heating',
    description: 'Energy used by a microwave oven heating food for 5 minutes',
    dimension: 'energy',
    value: 300,
    unit: 'kilojoule',
    valueMin: 250,
    valueMax: 450,
    tags: ['household', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'dishwasher-cycle',
    name: 'Dishwasher cycle',
    description: 'Energy used by a dishwasher for one normal cycle',
    dimension: 'energy',
    value: 1.8,
    unit: 'kilowatt-hour',
    valueMin: 1.2,
    valueMax: 2.4,
    tags: ['household', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Projectiles and weapons
  {
    id: 'bullet-9mm',
    name: '9mm bullet',
    description: 'Kinetic energy of a 9mm bullet at muzzle velocity',
    dimension: 'energy',
    value: 500,
    unit: 'joule',
    valueMin: 400,
    valueMax: 600,
    tags: ['weapons', 'physics', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'kinetic-energy-sprinter',
    name: 'Sprinter at full speed',
    description: 'Kinetic energy of Usain Bolt sprinting at 12 m/s',
    dimension: 'energy',
    value: 6192,
    unit: 'joule',
    tags: ['human-body', 'sports', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Fuels - small scale
  {
    id: 'stick-of-dynamite',
    name: 'Stick of dynamite',
    description: 'Energy released by exploding one stick of dynamite',
    dimension: 'energy',
    value: 1,
    unit: 'megajoule',
    tags: ['explosives', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'hand-grenade',
    name: 'Hand grenade',
    description: 'Energy released by a typical hand grenade (50g TNT)',
    dimension: 'energy',
    value: 209,
    unit: 'kilojoule',
    tags: ['explosives', 'military', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'kilogram-coal',
    name: 'Kilogram of coal',
    description: 'Energy content of one kilogram of bituminous coal',
    dimension: 'energy',
    value: 28,
    unit: 'megajoule',
    valueMin: 27,
    valueMax: 30,
    tags: ['fuel', 'energy-production', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'gallon-gasoline',
    name: 'Gallon of gasoline',
    description: 'Energy content of one US gallon of gasoline',
    dimension: 'energy',
    value: 121,
    unit: 'megajoule',
    tags: ['fuel', 'vehicles', 'american'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'liter-gasoline',
    name: 'Liter of gasoline',
    description: 'Energy content of one liter of gasoline',
    dimension: 'energy',
    value: 33.6,
    unit: 'megajoule',
    tags: ['fuel', 'vehicles', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Natural phenomena
  {
    id: 'lightning-bolt-energy',
    name: 'Lightning bolt',
    description: 'Energy in a typical lightning strike',
    dimension: 'energy',
    value: 1000,
    unit: 'megajoule',
    valueMin: 250,
    valueMax: 5000,
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Large explosives
  {
    id: 'ton-tnt',
    name: 'Ton of TNT',
    description: 'Energy released by detonating one ton of TNT',
    dimension: 'energy',
    value: 1,
    unit: 'ton-tnt',
    tags: ['explosives', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'hiroshima-bomb',
    name: 'Hiroshima atomic bomb',
    description: 'Energy released by the Little Boy atomic bomb',
    dimension: 'energy',
    value: 15,
    unit: 'kiloton-tnt',
    valueMin: 12,
    valueMax: 18,
    tags: ['nuclear', 'weapons', 'history', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Earthquakes
  {
    id: 'earthquake-magnitude-5',
    name: 'Magnitude 5.0 earthquake',
    description: 'Energy released by a magnitude 5.0 earthquake',
    dimension: 'energy',
    value: 200,
    unit: 'ton-tnt',
    tags: ['nature', 'geology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'earthquake-magnitude-6',
    name: 'Magnitude 6.0 earthquake',
    description: 'Energy released by a magnitude 6.0 earthquake',
    dimension: 'energy',
    value: 6.27,
    unit: 'kiloton-tnt',
    tags: ['nature', 'geology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'earthquake-magnitude-7',
    name: 'Magnitude 7.0 earthquake',
    description: 'Energy released by a magnitude 7.0 earthquake',
    dimension: 'energy',
    value: 199,
    unit: 'kiloton-tnt',
    tags: ['nature', 'geology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'earthquake-magnitude-9',
    name: 'Magnitude 9.0 earthquake',
    description: 'Energy released by a magnitude 9.0 earthquake',
    dimension: 'energy',
    value: 99,
    unit: 'megaton-tnt',
    tags: ['nature', 'geology', 'universal'],
    relatability: 6,
    accuracy: 8,
  },

  // Volcanic eruptions
  {
    id: 'mount-st-helens',
    name: 'Mount St. Helens eruption',
    description: 'Total thermal energy from 1980 Mount St. Helens eruption',
    dimension: 'energy',
    value: 24,
    unit: 'megaton-tnt',
    tags: ['nature', 'geology', 'american'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'krakatoa-eruption',
    name: 'Krakatoa eruption',
    description: 'Energy released by the 1883 Krakatoa eruption',
    dimension: 'energy',
    value: 200,
    unit: 'megaton-tnt',
    tags: ['nature', 'geology', 'history', 'universal'],
    relatability: 6,
    accuracy: 8,
  },

  // Nuclear weapons
  {
    id: 'tsar-bomba',
    name: 'Tsar Bomba',
    description: 'Largest nuclear weapon ever detonated',
    dimension: 'energy',
    value: 50,
    unit: 'megaton-tnt',
    tags: ['nuclear', 'weapons', 'history', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Asteroid impacts
  {
    id: 'tunguska-event',
    name: 'Tunguska event',
    description: 'Energy from 1908 Tunguska asteroid explosion',
    dimension: 'energy',
    value: 15,
    unit: 'megaton-tnt',
    tags: ['space', 'history', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'chicxulub-impact',
    name: 'Chicxulub asteroid impact',
    description: 'Energy from the dinosaur-killing asteroid 66 million years ago',
    dimension: 'energy',
    value: 100000000,
    unit: 'megaton-tnt',
    tags: ['space', 'history', 'universal'],
    relatability: 7,
    accuracy: 7,
  },

  // Power generation
  {
    id: 'nuclear-plant-daily',
    name: 'Nuclear plant daily output',
    description: 'Daily electrical output from a 1 GW nuclear power plant',
    dimension: 'energy',
    value: 86.4,
    unit: 'gigajoule',
    valueMin: 70,
    valueMax: 100,
    tags: ['energy-production', 'nuclear', 'universal'],
    relatability: 5,
    accuracy: 7,
  },
  {
    id: 'coal-plant-yearly',
    name: 'Coal plant yearly output',
    description: 'Annual electrical output from a large coal power plant',
    dimension: 'energy',
    value: 31.5,
    unit: 'gigajoule',
    tags: ['energy-production', 'universal'],
    relatability: 4,
    accuracy: 7,
  },

  // Cosmic
  {
    id: 'sun-one-second',
    name: 'Sun energy (1 second)',
    description: 'Total energy output by the Sun in one second',
    dimension: 'energy',
    value: 3.86e26,
    unit: 'joule',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'sun-lifetime',
    name: 'Sun lifetime energy',
    description: 'Total energy output by the Sun over its 10 billion year lifetime',
    dimension: 'energy',
    value: 1e44,
    unit: 'joule',
    tags: ['astronomy', 'universal'],
    relatability: 4,
    accuracy: 8,
  },
  {
    id: 'supernova',
    name: 'Supernova explosion',
    description: 'Kinetic energy released by a Type II supernova',
    dimension: 'energy',
    value: 1e44,
    unit: 'joule',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'supernova-neutrinos',
    name: 'Supernova neutrino burst',
    description: 'Total energy released in neutrinos during a supernova collapse',
    dimension: 'energy',
    value: 1e46,
    unit: 'joule',
    tags: ['astronomy', 'physics', 'universal'],
    relatability: 4,
    accuracy: 8,
  },
];
