import type { Measurable } from '@/types';

export const lengthMeasurables: Measurable[] = [
  // Atomic / Subatomic
  {
    id: 'hydrogen-atom',
    name: 'Hydrogen atom diameter',
    description: 'Diameter of a hydrogen atom',
    dimension: 'length',
    value: 120,
    unit: 'picometer',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'dna-helix-width',
    name: 'DNA double helix width',
    description: 'Width of the DNA double helix structure',
    dimension: 'length',
    value: 2,
    unit: 'nanometer',
    tags: ['biology', 'molecular', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Microscopic
  {
    id: 'virus-diameter',
    name: 'Typical virus diameter',
    description: 'Diameter of an average virus particle',
    dimension: 'length',
    value: 100,
    unit: 'nanometer',
    valueMin: 20,
    valueMax: 300,
    tags: ['biology', 'microscopic', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'bacteria-length',
    name: 'Typical bacteria length',
    description: 'Length of an average bacterium (E. coli)',
    dimension: 'length',
    value: 2,
    unit: 'micrometer',
    valueMin: 1,
    valueMax: 10,
    tags: ['biology', 'microscopic', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'red-blood-cell',
    name: 'Red blood cell diameter',
    description: 'Diameter of a human red blood cell',
    dimension: 'length',
    value: 7,
    unit: 'micrometer',
    tags: ['biology', 'human-body', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'human-hair-thickness',
    name: 'Human hair thickness',
    description: 'Average diameter of a human hair strand',
    dimension: 'length',
    value: 70,
    unit: 'micrometer',
    valueMin: 50,
    valueMax: 100,
    tags: ['biology', 'human-body', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Small everyday objects
  {
    id: 'grain-of-sand',
    name: 'Grain of sand',
    description: 'Diameter of a medium grain of sand',
    dimension: 'length',
    value: 0.5,
    unit: 'millimeter',
    valueMin: 0.1,
    valueMax: 2,
    tags: ['nature', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'credit-card-thickness',
    name: 'Credit card thickness',
    description: 'Thickness of a standard credit card',
    dimension: 'length',
    value: 0.76,
    unit: 'millimeter',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'pencil-diameter',
    name: 'Pencil diameter',
    description: 'Diameter of a standard wooden pencil',
    dimension: 'length',
    value: 7,
    unit: 'millimeter',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'us-quarter-diameter',
    name: 'US quarter diameter',
    description: 'Diameter of a US quarter coin',
    dimension: 'length',
    value: 24.26,
    unit: 'millimeter',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },

  // Human scale
  {
    id: 'hand-span',
    name: 'Hand span',
    description: 'Average adult hand span (thumb to pinky stretched)',
    dimension: 'length',
    value: 20,
    unit: 'centimeter',
    valueMin: 18,
    valueMax: 25,
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'human-arm-length',
    name: 'Human arm length',
    description: 'Average adult arm length (shoulder to fingertip)',
    dimension: 'length',
    value: 64,
    unit: 'centimeter',
    tags: ['human-body', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'human-height',
    name: 'Human height',
    description: 'Average adult human height',
    dimension: 'length',
    value: 1.7,
    unit: 'meter',
    valueMin: 1.5,
    valueMax: 1.9,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Vehicles and large objects
  {
    id: 'car-length',
    name: 'Car length',
    description: 'Length of an average sedan',
    dimension: 'length',
    value: 4.5,
    unit: 'meter',
    valueMin: 4,
    valueMax: 5,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'school-bus-length',
    name: 'School bus length',
    description: 'Length of a full-size school bus',
    dimension: 'length',
    value: 12,
    unit: 'meter',
    tags: ['vehicles', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'blue-whale-length',
    name: 'Blue whale length',
    description: 'Length of an adult blue whale',
    dimension: 'length',
    value: 30,
    unit: 'meter',
    valueMin: 24,
    valueMax: 33,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'boeing-747-length',
    name: 'Boeing 747 length',
    description: 'Length of a Boeing 747-400',
    dimension: 'length',
    value: 70.7,
    unit: 'meter',
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 7,
    accuracy: 10,
  },

  // Sports and fields
  {
    id: 'football-field-length',
    name: 'American football field',
    description: 'Length of an American football field (end zone to end zone)',
    dimension: 'length',
    value: 109.7,
    unit: 'meter',
    tags: ['sports', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'soccer-field-length',
    name: 'Soccer field length',
    description: 'Length of a regulation soccer/football pitch',
    dimension: 'length',
    value: 105,
    unit: 'meter',
    valueMin: 100,
    valueMax: 110,
    tags: ['sports', 'international'],
    relatability: 9,
    accuracy: 8,
  },

  // Landmarks and structures
  {
    id: 'statue-of-liberty-height',
    name: 'Statue of Liberty height',
    description: 'Height from ground to torch tip',
    dimension: 'length',
    value: 93,
    unit: 'meter',
    tags: ['landmarks', 'american', 'architecture'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'eiffel-tower-height',
    name: 'Eiffel Tower height',
    description: 'Height to the top of the Eiffel Tower',
    dimension: 'length',
    value: 330,
    unit: 'meter',
    tags: ['landmarks', 'european', 'architecture'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'empire-state-building',
    name: 'Empire State Building height',
    description: 'Height to roof (without antenna)',
    dimension: 'length',
    value: 381,
    unit: 'meter',
    tags: ['landmarks', 'american', 'architecture'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'burj-khalifa-height',
    name: 'Burj Khalifa height',
    description: "Height of the world's tallest building",
    dimension: 'length',
    value: 828,
    unit: 'meter',
    tags: ['landmarks', 'architecture', 'universal'],
    relatability: 7,
    accuracy: 10,
  },

  // Geographic
  {
    id: 'marathon-distance',
    name: 'Marathon distance',
    description: 'Standard marathon race distance',
    dimension: 'length',
    value: 42.195,
    unit: 'kilometer',
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'mount-everest-height',
    name: 'Mount Everest height',
    description: 'Height above sea level',
    dimension: 'length',
    value: 8848.86,
    unit: 'meter',
    tags: ['geography', 'nature', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'grand-canyon-depth',
    name: 'Grand Canyon depth',
    description: 'Maximum depth of the Grand Canyon',
    dimension: 'length',
    value: 1.83,
    unit: 'kilometer',
    tags: ['geography', 'american', 'nature'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'mariana-trench-depth',
    name: 'Mariana Trench depth',
    description: 'Depth of the deepest point in the ocean',
    dimension: 'length',
    value: 10.994,
    unit: 'kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Planetary
  {
    id: 'earth-diameter',
    name: 'Earth diameter',
    description: 'Equatorial diameter of Earth',
    dimension: 'length',
    value: 12742,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'moon-diameter',
    name: 'Moon diameter',
    description: "Diameter of Earth's Moon",
    dimension: 'length',
    value: 3474,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'earth-to-moon',
    name: 'Earth to Moon distance',
    description: 'Average distance from Earth to Moon',
    dimension: 'length',
    value: 384400,
    unit: 'kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'sun-diameter',
    name: 'Sun diameter',
    description: 'Diameter of the Sun',
    dimension: 'length',
    value: 1.3927,
    unit: 'kilometer',
    valueMin: 1392700,
    valueMax: 1392700,
    tags: ['astronomy', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'earth-to-sun',
    name: 'Earth to Sun distance',
    description: 'Average distance from Earth to Sun (1 AU)',
    dimension: 'length',
    value: 1,
    unit: 'astronomical-unit',
    tags: ['astronomy', 'universal'],
    relatability: 7,
    accuracy: 10,
  },

  // Galactic
  {
    id: 'light-second',
    name: 'Light-second',
    description: 'Distance light travels in one second',
    dimension: 'length',
    value: 299792,
    unit: 'kilometer',
    tags: ['physics', 'astronomy', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'milky-way-diameter',
    name: 'Milky Way diameter',
    description: 'Diameter of our galaxy',
    dimension: 'length',
    value: 100000,
    unit: 'light-year',
    tags: ['astronomy', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
];
