import type { Measurable } from '@/types';

export const lengthMeasurables: Measurable[] = [
  // Quantum / Subatomic
  {
    id: 'planck-length',
    name: 'Planck length',
    description: 'Smallest measurable length in physics',
    dimension: 'length',
    value: 1.616e-35,
    unit: 'meter',
    tags: ['physics', 'quantum', 'universal'],
    relatability: 4,
    accuracy: 10,
  },
  {
    id: 'proton-diameter',
    name: 'Proton diameter',
    description: 'Diameter of a proton',
    dimension: 'length',
    value: 1.7,
    unit: 'picometer',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'hydrogen-atom',
    name: 'Hydrogen atom diameter',
    description: 'Diameter of a hydrogen atom',
    dimension: 'length',
    value: 120,
    unit: 'picometer',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'silicon-atom',
    name: 'Silicon atom diameter',
    description: 'Diameter of a silicon atom',
    dimension: 'length',
    value: 0.2,
    unit: 'nanometer',
    tags: ['physics', 'atomic', 'technology'],
    relatability: 5,
    accuracy: 9,
  },

  // Molecular / Nanoscale
  {
    id: 'dna-helix-width',
    name: 'DNA double helix width',
    description: 'Width of the DNA double helix structure',
    dimension: 'length',
    value: 2,
    unit: 'nanometer',
    tags: ['biology', 'molecular', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'semiconductor-transistor',
    name: 'Modern transistor size',
    description: 'Feature size of cutting-edge semiconductor transistors (3nm process)',
    dimension: 'length',
    value: 3,
    unit: 'nanometer',
    tags: ['technology', 'electronics', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'wavelength-visible-light',
    name: 'Visible light wavelength',
    description: 'Wavelength of visible light (green)',
    dimension: 'length',
    value: 550,
    unit: 'nanometer',
    valueMin: 400,
    valueMax: 700,
    tags: ['physics', 'light', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Microscopic
  {
    id: 'virus-diameter',
    name: 'Typical virus diameter',
    description: 'Diameter of an average virus particle',
    dimension: 'length',
    value: 100,
    unit: 'nanometer',
    valueMin: 20,
    valueMax: 300,
    tags: ['biology', 'microscopic', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'bacteria-length',
    name: 'Typical bacteria length',
    description: 'Length of an average bacterium (E. coli)',
    dimension: 'length',
    value: 2,
    unit: 'micrometer',
    valueMin: 1,
    valueMax: 10,
    tags: ['biology', 'microscopic', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'red-blood-cell',
    name: 'Red blood cell diameter',
    description: 'Diameter of a human red blood cell',
    dimension: 'length',
    value: 7,
    unit: 'micrometer',
    tags: ['biology', 'human-body', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'paramecium-length',
    name: 'Paramecium length',
    description: 'Length of a single-celled paramecium',
    dimension: 'length',
    value: 200,
    unit: 'micrometer',
    valueMin: 100,
    valueMax: 300,
    tags: ['biology', 'microscopic', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'human-hair-thickness',
    name: 'Human hair thickness',
    description: 'Average diameter of a human hair strand',
    dimension: 'length',
    value: 70,
    unit: 'micrometer',
    valueMin: 50,
    valueMax: 100,
    tags: ['biology', 'human-body', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Small everyday objects
  {
    id: 'grain-of-sand',
    name: 'Grain of sand',
    description: 'Diameter of a medium grain of sand',
    dimension: 'length',
    value: 0.5,
    unit: 'millimeter',
    valueMin: 0.1,
    valueMax: 2,
    tags: ['nature', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'fingernail-thickness',
    name: 'Fingernail thickness',
    description: 'Thickness of a human fingernail',
    dimension: 'length',
    value: 0.5,
    unit: 'millimeter',
    tags: ['human-body', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'credit-card-thickness',
    name: 'Credit card thickness',
    description: 'Thickness of a standard credit card',
    dimension: 'length',
    value: 0.76,
    unit: 'millimeter',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'ant-length',
    name: 'Ant length',
    description: 'Length of a typical ant',
    dimension: 'length',
    value: 4,
    unit: 'millimeter',
    valueMin: 2,
    valueMax: 6,
    tags: ['biology', 'insects', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'bee-hummingbird',
    name: 'Bee hummingbird length',
    description: 'Length of the world\'s smallest bird',
    dimension: 'length',
    value: 5.5,
    unit: 'centimeter',
    tags: ['animals', 'birds', 'nature'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'golf-ball-diameter',
    name: 'Golf ball diameter',
    description: 'Diameter of a standard golf ball',
    dimension: 'length',
    value: 4.27,
    unit: 'centimeter',
    tags: ['sports', 'golf', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'tennis-ball-diameter',
    name: 'Tennis ball diameter',
    description: 'Diameter of a standard tennis ball',
    dimension: 'length',
    value: 6.7,
    unit: 'centimeter',
    valueMin: 6.54,
    valueMax: 6.86,
    tags: ['sports', 'tennis', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'pencil-diameter',
    name: 'Pencil diameter',
    description: 'Diameter of a standard wooden pencil',
    dimension: 'length',
    value: 7,
    unit: 'millimeter',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'us-dime-diameter',
    name: 'US dime diameter',
    description: 'Diameter of a US dime coin',
    dimension: 'length',
    value: 17.91,
    unit: 'millimeter',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'us-penny-diameter',
    name: 'US penny diameter',
    description: 'Diameter of a US penny coin',
    dimension: 'length',
    value: 19.05,
    unit: 'millimeter',
    tags: ['money', 'american', 'everyday'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'thumb-width',
    name: 'Thumb width',
    description: 'Width of an adult thumbnail',
    dimension: 'length',
    value: 17,
    unit: 'millimeter',
    valueMin: 16,
    valueMax: 18,
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'us-quarter-diameter',
    name: 'US quarter diameter',
    description: 'Diameter of a US quarter coin',
    dimension: 'length',
    value: 24.26,
    unit: 'millimeter',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'basketball-diameter',
    name: 'Basketball diameter',
    description: 'Diameter of a regulation basketball',
    dimension: 'length',
    value: 24.6,
    unit: 'centimeter',
    tags: ['sports', 'basketball', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Human scale
  {
    id: 'iphone-length',
    name: 'iPhone length',
    description: 'Length of a modern smartphone (iPhone 16 Pro)',
    dimension: 'length',
    value: 159.9,
    unit: 'millimeter',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'hand-span',
    name: 'Hand span',
    description: 'Average adult hand span (thumb to pinky stretched)',
    dimension: 'length',
    value: 20,
    unit: 'centimeter',
    valueMin: 18,
    valueMax: 25,
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'human-arm-length',
    name: 'Human arm length',
    description: 'Average adult arm length (shoulder to fingertip)',
    dimension: 'length',
    value: 64,
    unit: 'centimeter',
    tags: ['human-body', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'human-height',
    name: 'Human height',
    description: 'Average adult human height',
    dimension: 'length',
    value: 1.7,
    unit: 'meter',
    valueMin: 1.5,
    valueMax: 1.9,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'doorway-height',
    name: 'Standard doorway height',
    description: 'Height of a standard residential door',
    dimension: 'length',
    value: 2.03,
    unit: 'meter',
    tags: ['architecture', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'refrigerator-height',
    name: 'Refrigerator height',
    description: 'Height of a standard refrigerator',
    dimension: 'length',
    value: 1.7,
    unit: 'meter',
    valueMin: 1.55,
    valueMax: 1.83,
    tags: ['appliances', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'giraffe-height',
    name: 'Giraffe height',
    description: 'Height of an adult giraffe, the tallest land animal',
    dimension: 'length',
    value: 5.2,
    unit: 'meter',
    valueMin: 4.8,
    valueMax: 5.9,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Vehicles and large objects
  {
    id: 'car-length',
    name: 'Car length',
    description: 'Length of an average sedan',
    dimension: 'length',
    value: 4.5,
    unit: 'meter',
    valueMin: 4,
    valueMax: 5,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'school-bus-length',
    name: 'School bus length',
    description: 'Length of a full-size school bus',
    dimension: 'length',
    value: 12,
    unit: 'meter',
    tags: ['vehicles', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'basketball-court-length',
    name: 'Basketball court length',
    description: 'Length of a regulation basketball court',
    dimension: 'length',
    value: 28,
    unit: 'meter',
    tags: ['sports', 'basketball', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'tennis-court-length',
    name: 'Tennis court length',
    description: 'Length of a regulation tennis court',
    dimension: 'length',
    value: 23.77,
    unit: 'meter',
    tags: ['sports', 'tennis', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'blue-whale-length',
    name: 'Blue whale length',
    description: 'Length of an adult blue whale, the largest animal',
    dimension: 'length',
    value: 30,
    unit: 'meter',
    valueMin: 24,
    valueMax: 33,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'boeing-747-length',
    name: 'Boeing 747 length',
    description: 'Length of a Boeing 747-400',
    dimension: 'length',
    value: 70.7,
    unit: 'meter',
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'iss-length',
    name: 'International Space Station length',
    description: 'End-to-end length of the ISS with solar arrays',
    dimension: 'length',
    value: 109,
    unit: 'meter',
    tags: ['space', 'technology', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'nuclear-submarine-length',
    name: 'Nuclear submarine length',
    description: 'Length of a Virginia-class attack submarine',
    dimension: 'length',
    value: 115,
    unit: 'meter',
    tags: ['military', 'vehicles', 'technology'],
    relatability: 6,
    accuracy: 10,
  },

  // Sports and fields
  {
    id: 'football-field-length',
    name: 'American football field',
    description: 'Length of an American football field (end zone to end zone)',
    dimension: 'length',
    value: 109.7,
    unit: 'meter',
    tags: ['sports', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'soccer-field-length',
    name: 'Soccer field length',
    description: 'Length of a regulation soccer/football pitch',
    dimension: 'length',
    value: 105,
    unit: 'meter',
    valueMin: 100,
    valueMax: 110,
    tags: ['sports', 'international'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'titanic-length',
    name: 'RMS Titanic length',
    description: 'Length of the Titanic ocean liner',
    dimension: 'length',
    value: 269,
    unit: 'meter',
    tags: ['ships', 'history', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'cruise-ship-length',
    name: 'Modern cruise ship length',
    description: 'Length of a large modern cruise ship',
    dimension: 'length',
    value: 365,
    unit: 'meter',
    tags: ['ships', 'vehicles', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Landmarks and structures
  {
    id: 'statue-of-liberty-height',
    name: 'Statue of Liberty height',
    description: 'Height from ground to torch tip',
    dimension: 'length',
    value: 93,
    unit: 'meter',
    tags: ['landmarks', 'american', 'architecture'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'redwood-tree-height',
    name: 'Coast redwood height',
    description: 'Height of the tallest tree species, including Hyperion',
    dimension: 'length',
    value: 116,
    unit: 'meter',
    valueMin: 90,
    valueMax: 116,
    tags: ['nature', 'trees', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'eiffel-tower-height',
    name: 'Eiffel Tower height',
    description: 'Height to the top of the Eiffel Tower (with antenna)',
    dimension: 'length',
    value: 330,
    unit: 'meter',
    tags: ['landmarks', 'european', 'architecture'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'empire-state-building',
    name: 'Empire State Building height',
    description: 'Height to roof (without antenna)',
    dimension: 'length',
    value: 381,
    unit: 'meter',
    tags: ['landmarks', 'american', 'architecture'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'burj-khalifa-height',
    name: 'Burj Khalifa height',
    description: "Height of the world's tallest building",
    dimension: 'length',
    value: 828,
    unit: 'meter',
    tags: ['landmarks', 'architecture', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'golden-gate-bridge-span',
    name: 'Golden Gate Bridge main span',
    description: 'Main span length of the Golden Gate Bridge',
    dimension: 'length',
    value: 1280,
    unit: 'meter',
    tags: ['landmarks', 'american', 'engineering'],
    relatability: 8,
    accuracy: 10,
  },

  // Geographic
  {
    id: 'marathon-distance',
    name: 'Marathon distance',
    description: 'Standard marathon race distance',
    dimension: 'length',
    value: 42.195,
    unit: 'kilometer',
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'suez-canal-length',
    name: 'Suez Canal length',
    description: 'Total length of the Suez Canal',
    dimension: 'length',
    value: 193,
    unit: 'kilometer',
    tags: ['geography', 'engineering', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'mount-everest-height',
    name: 'Mount Everest height',
    description: 'Height above sea level',
    dimension: 'length',
    value: 8848.86,
    unit: 'meter',
    tags: ['geography', 'nature', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'grand-canyon-depth',
    name: 'Grand Canyon depth',
    description: 'Maximum depth of the Grand Canyon',
    dimension: 'length',
    value: 1.83,
    unit: 'kilometer',
    tags: ['geography', 'american', 'nature'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'mariana-trench-depth',
    name: 'Mariana Trench depth',
    description: 'Depth of the deepest point in the ocean',
    dimension: 'length',
    value: 10.994,
    unit: 'kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'nile-river-length',
    name: 'Nile River length',
    description: 'Length of the Nile, one of the world\'s longest rivers',
    dimension: 'length',
    value: 6650,
    unit: 'kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'great-wall-china',
    name: 'Great Wall of China length',
    description: 'Total length of all sections of the Great Wall',
    dimension: 'length',
    value: 21196,
    unit: 'kilometer',
    tags: ['landmarks', 'architecture', 'history'],
    relatability: 8,
    accuracy: 10,
  },

  // Planetary
  {
    id: 'neutron-star-diameter',
    name: 'Neutron star diameter',
    description: 'Typical diameter of a neutron star',
    dimension: 'length',
    value: 20,
    unit: 'kilometer',
    valueMin: 18,
    valueMax: 30,
    tags: ['astronomy', 'physics', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'moon-diameter',
    name: 'Moon diameter',
    description: "Diameter of Earth's Moon",
    dimension: 'length',
    value: 3474,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'earth-diameter',
    name: 'Earth diameter',
    description: 'Equatorial diameter of Earth',
    dimension: 'length',
    value: 12742,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'neptune-diameter',
    name: 'Neptune diameter',
    description: 'Diameter of Neptune',
    dimension: 'length',
    value: 49500,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'saturn-diameter',
    name: 'Saturn diameter',
    description: 'Equatorial diameter of Saturn',
    dimension: 'length',
    value: 120536,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'jupiter-diameter',
    name: 'Jupiter diameter',
    description: 'Equatorial diameter of Jupiter, the largest planet',
    dimension: 'length',
    value: 142984,
    unit: 'kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'earth-to-moon',
    name: 'Earth to Moon distance',
    description: 'Average distance from Earth to Moon',
    dimension: 'length',
    value: 384400,
    unit: 'kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'sun-diameter',
    name: 'Sun diameter',
    description: 'Diameter of the Sun',
    dimension: 'length',
    value: 1392700,
    unit: 'kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'earth-to-sun',
    name: 'Earth to Sun distance',
    description: 'Average distance from Earth to Sun (1 AU)',
    dimension: 'length',
    value: 1,
    unit: 'astronomical-unit',
    tags: ['astronomy', 'universal'],
    relatability: 7,
    accuracy: 10,
  },

  // Galactic and Cosmic
  {
    id: 'light-second',
    name: 'Light-second',
    description: 'Distance light travels in one second',
    dimension: 'length',
    value: 299792,
    unit: 'kilometer',
    tags: ['physics', 'astronomy', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'light-year',
    name: 'Light-year',
    description: 'Distance light travels in one year',
    dimension: 'length',
    value: 1,
    unit: 'light-year',
    tags: ['physics', 'astronomy', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'milky-way-diameter',
    name: 'Milky Way diameter',
    description: 'Diameter of our galaxy',
    dimension: 'length',
    value: 100000,
    unit: 'light-year',
    tags: ['astronomy', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'andromeda-galaxy-diameter',
    name: 'Andromeda Galaxy diameter',
    description: 'Diameter of the nearest major galaxy to the Milky Way',
    dimension: 'length',
    value: 220000,
    unit: 'light-year',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'observable-universe-diameter',
    name: 'Observable universe diameter',
    description: 'Diameter of the observable universe',
    dimension: 'length',
    value: 93000000000,
    unit: 'light-year',
    tags: ['astronomy', 'cosmology', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
];
