import type { Measurable } from '@/types';

export const massMeasurables: Measurable[] = [
  // Atomic / Microscopic
  {
    id: 'electron-mass',
    name: 'Electron mass',
    description: 'Mass of a single electron',
    dimension: 'mass',
    value: 9.109e-31,
    unit: 'kilogram',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'proton-mass',
    name: 'Proton mass',
    description: 'Mass of a single proton',
    dimension: 'mass',
    value: 1.673e-27,
    unit: 'kilogram',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'water-molecule',
    name: 'Water molecule mass',
    description: 'Mass of a single H₂O molecule',
    dimension: 'mass',
    value: 2.99e-26,
    unit: 'kilogram',
    tags: ['chemistry', 'molecular', 'universal'],
    relatability: 6,
    accuracy: 10,
  },

  // Tiny objects
  {
    id: 'grain-of-sand-mass',
    name: 'Grain of sand mass',
    description: 'Mass of a single grain of sand',
    dimension: 'mass',
    value: 0.01,
    unit: 'gram',
    valueMin: 0.001,
    valueMax: 0.1,
    tags: ['nature', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 5,
  },
  {
    id: 'raindrop-mass',
    name: 'Raindrop mass',
    description: 'Mass of a typical raindrop',
    dimension: 'mass',
    value: 0.05,
    unit: 'gram',
    valueMin: 0.01,
    valueMax: 0.1,
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'paperclip-mass',
    name: 'Paperclip mass',
    description: 'Mass of a standard metal paperclip',
    dimension: 'mass',
    value: 1,
    unit: 'gram',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'us-penny',
    name: 'US penny mass',
    description: 'Mass of a US one-cent coin',
    dimension: 'mass',
    value: 2.5,
    unit: 'gram',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },

  // Food items
  {
    id: 'sugar-cube',
    name: 'Sugar cube mass',
    description: 'Mass of a standard sugar cube',
    dimension: 'mass',
    value: 4,
    unit: 'gram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'chicken-egg',
    name: 'Chicken egg mass',
    description: 'Mass of a large chicken egg',
    dimension: 'mass',
    value: 50,
    unit: 'gram',
    valueMin: 45,
    valueMax: 60,
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'apple-mass',
    name: 'Apple mass',
    description: 'Mass of a medium apple',
    dimension: 'mass',
    value: 180,
    unit: 'gram',
    valueMin: 150,
    valueMax: 220,
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'banana-mass',
    name: 'Banana mass',
    description: 'Mass of a medium banana',
    dimension: 'mass',
    value: 120,
    unit: 'gram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Everyday objects
  {
    id: 'smartphone-mass',
    name: 'Smartphone mass',
    description: 'Mass of a typical smartphone',
    dimension: 'mass',
    value: 175,
    unit: 'gram',
    valueMin: 140,
    valueMax: 230,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'can-of-soda',
    name: 'Can of soda mass',
    description: 'Mass of a 12oz can of soda',
    dimension: 'mass',
    value: 384,
    unit: 'gram',
    tags: ['food', 'everyday', 'american'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'basketball-mass',
    name: 'Basketball mass',
    description: 'Mass of a regulation basketball',
    dimension: 'mass',
    value: 625,
    unit: 'gram',
    valueMin: 567,
    valueMax: 650,
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'laptop-mass',
    name: 'Laptop mass',
    description: 'Mass of a typical laptop computer',
    dimension: 'mass',
    value: 2,
    unit: 'kilogram',
    valueMin: 1,
    valueMax: 3,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'bowling-ball',
    name: 'Bowling ball mass',
    description: 'Mass of a typical bowling ball',
    dimension: 'mass',
    value: 6,
    unit: 'kilogram',
    valueMin: 3.6,
    valueMax: 7.26,
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Humans and animals
  {
    id: 'newborn-human',
    name: 'Newborn baby mass',
    description: 'Average mass of a newborn human',
    dimension: 'mass',
    value: 3.4,
    unit: 'kilogram',
    valueMin: 2.5,
    valueMax: 4.5,
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'adult-human',
    name: 'Adult human mass',
    description: 'Average mass of an adult human',
    dimension: 'mass',
    value: 70,
    unit: 'kilogram',
    valueMin: 50,
    valueMax: 100,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 6,
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever mass',
    description: 'Mass of an adult Golden Retriever dog',
    dimension: 'mass',
    value: 32,
    unit: 'kilogram',
    valueMin: 25,
    valueMax: 35,
    tags: ['animals', 'pets', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'horse-mass',
    name: 'Horse mass',
    description: 'Mass of an average horse',
    dimension: 'mass',
    value: 500,
    unit: 'kilogram',
    valueMin: 380,
    valueMax: 1000,
    tags: ['animals', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'cow-mass',
    name: 'Cow mass',
    description: 'Mass of an adult dairy cow',
    dimension: 'mass',
    value: 720,
    unit: 'kilogram',
    valueMin: 400,
    valueMax: 900,
    tags: ['animals', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Large animals
  {
    id: 'elephant-mass',
    name: 'African elephant mass',
    description: 'Mass of an adult African elephant',
    dimension: 'mass',
    value: 6000,
    unit: 'kilogram',
    valueMin: 4000,
    valueMax: 7000,
    tags: ['animals', 'nature', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'blue-whale-mass',
    name: 'Blue whale mass',
    description: 'Mass of an adult blue whale',
    dimension: 'mass',
    value: 150,
    unit: 'metric-ton',
    valueMin: 100,
    valueMax: 200,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Vehicles
  {
    id: 'car-mass',
    name: 'Car mass',
    description: 'Mass of an average car',
    dimension: 'mass',
    value: 1500,
    unit: 'kilogram',
    valueMin: 1000,
    valueMax: 2000,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'school-bus-mass',
    name: 'School bus mass',
    description: 'Mass of a full-size school bus',
    dimension: 'mass',
    value: 10000,
    unit: 'kilogram',
    tags: ['vehicles', 'american'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'boeing-747-empty',
    name: 'Boeing 747 (empty)',
    description: 'Empty mass of a Boeing 747-400',
    dimension: 'mass',
    value: 178756,
    unit: 'kilogram',
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Structures
  {
    id: 'eiffel-tower-mass',
    name: 'Eiffel Tower mass',
    description: 'Total mass of the Eiffel Tower iron structure',
    dimension: 'mass',
    value: 7300,
    unit: 'metric-ton',
    tags: ['landmarks', 'architecture', 'european'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'titanic-mass',
    name: 'RMS Titanic mass',
    description: 'Displacement mass of the Titanic',
    dimension: 'mass',
    value: 52310,
    unit: 'metric-ton',
    tags: ['ships', 'historical', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'great-pyramid-mass',
    name: 'Great Pyramid of Giza mass',
    description: 'Estimated mass of the Great Pyramid',
    dimension: 'mass',
    value: 6000000,
    unit: 'metric-ton',
    tags: ['landmarks', 'architecture', 'historical'],
    relatability: 7,
    accuracy: 7,
  },

  // Astronomical
  {
    id: 'moon-mass',
    name: 'Moon mass',
    description: "Mass of Earth's Moon",
    dimension: 'mass',
    value: 7.342e22,
    unit: 'kilogram',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'earth-mass',
    name: 'Earth mass',
    description: 'Mass of planet Earth',
    dimension: 'mass',
    value: 1,
    unit: 'earth-mass',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'sun-mass',
    name: 'Sun mass',
    description: 'Mass of the Sun',
    dimension: 'mass',
    value: 1,
    unit: 'solar-mass',
    tags: ['astronomy', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
];
