import type { Measurable } from '@/types';

export const massMeasurables: Measurable[] = [
  // Atomic / Microscopic
  {
    id: 'electron-mass',
    name: 'Electron mass',
    description: 'Mass of a single electron',
    dimension: 'mass',
    value: 9.109e-31,
    unit: 'kilogram',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'proton-mass',
    name: 'Proton mass',
    description: 'Mass of a single proton',
    dimension: 'mass',
    value: 1.673e-27,
    unit: 'kilogram',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'neutron-mass',
    name: 'Neutron mass',
    description: 'Mass of a single neutron',
    dimension: 'mass',
    value: 1.675e-27,
    unit: 'kilogram',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'water-molecule',
    name: 'Water molecule mass',
    description: 'Mass of a single H₂O molecule',
    dimension: 'mass',
    value: 2.99e-26,
    unit: 'kilogram',
    tags: ['chemistry', 'molecular', 'universal'],
    relatability: 6,
    accuracy: 10,
  },

  // Cellular / Biological microscopic
  {
    id: 'human-dna',
    name: 'Human DNA (diploid cell)',
    description: 'Mass of DNA in a single human cell',
    dimension: 'mass',
    value: 6.5e-12,
    unit: 'gram',
    tags: ['biology', 'human-body', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'human-chromosome-set',
    name: 'Human chromosome set',
    description: 'Total mass of all 46 chromosomes in a human cell',
    dimension: 'mass',
    value: 242e-12,
    unit: 'gram',
    tags: ['biology', 'human-body', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'dust-mite',
    name: 'Dust mite mass',
    description: 'Mass of a typical dust mite',
    dimension: 'mass',
    value: 0.005,
    unit: 'milligram',
    valueMin: 0.002,
    valueMax: 0.01,
    tags: ['biology', 'everyday', 'universal'],
    relatability: 7,
    accuracy: 6,
  },

  // Tiny objects
  {
    id: 'sesame-seed',
    name: 'Sesame seed mass',
    description: 'Mass of a single sesame seed',
    dimension: 'mass',
    value: 3.6,
    unit: 'milligram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'grain-of-sand-mass',
    name: 'Grain of sand mass',
    description: 'Mass of a single grain of sand',
    dimension: 'mass',
    value: 0.01,
    unit: 'gram',
    valueMin: 0.001,
    valueMax: 0.1,
    tags: ['nature', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 5,
  },
  {
    id: 'grain-of-rice',
    name: 'Grain of rice mass',
    description: 'Mass of a single grain of rice',
    dimension: 'mass',
    value: 25,
    unit: 'milligram',
    valueMin: 20,
    valueMax: 30,
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'raindrop-mass',
    name: 'Raindrop mass',
    description: 'Mass of a typical raindrop',
    dimension: 'mass',
    value: 0.05,
    unit: 'gram',
    valueMin: 0.01,
    valueMax: 0.1,
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'snowflake-mass',
    name: 'Snowflake mass',
    description: 'Mass of a typical snowflake',
    dimension: 'mass',
    value: 3,
    unit: 'milligram',
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Small insects
  {
    id: 'ant-mass',
    name: 'Ant mass',
    description: 'Mass of a typical worker ant',
    dimension: 'mass',
    value: 2,
    unit: 'milligram',
    valueMin: 1,
    valueMax: 5,
    tags: ['animals', 'insects', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'housefly-mass',
    name: 'Housefly mass',
    description: 'Mass of a common housefly',
    dimension: 'mass',
    value: 12,
    unit: 'milligram',
    tags: ['animals', 'insects', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'honeybee-mass',
    name: 'Honeybee mass',
    description: 'Mass of a worker honeybee',
    dimension: 'mass',
    value: 100,
    unit: 'milligram',
    tags: ['animals', 'insects', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'butterfly-mass',
    name: 'Butterfly mass',
    description: 'Mass of a medium-sized butterfly',
    dimension: 'mass',
    value: 250,
    unit: 'milligram',
    valueMin: 40,
    valueMax: 500,
    tags: ['animals', 'insects', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'dragonfly-mass',
    name: 'Dragonfly mass',
    description: 'Mass of a typical dragonfly',
    dimension: 'mass',
    value: 750,
    unit: 'milligram',
    valueMin: 130,
    valueMax: 1100,
    tags: ['animals', 'insects', 'universal'],
    relatability: 7,
    accuracy: 6,
  },

  // Everyday small objects
  {
    id: 'paperclip-mass',
    name: 'Paperclip mass',
    description: 'Mass of a standard metal paperclip',
    dimension: 'mass',
    value: 1,
    unit: 'gram',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'us-dime',
    name: 'US dime mass',
    description: 'Mass of a US ten-cent coin',
    dimension: 'mass',
    value: 2.268,
    unit: 'gram',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'us-penny',
    name: 'US penny mass',
    description: 'Mass of a US one-cent coin',
    dimension: 'mass',
    value: 2.5,
    unit: 'gram',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'teaspoon-sugar',
    name: 'Teaspoon of sugar',
    description: 'Mass of sugar in a standard teaspoon',
    dimension: 'mass',
    value: 4,
    unit: 'gram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'a4-paper-sheet',
    name: 'Sheet of paper',
    description: 'Mass of a standard A4 or letter paper sheet',
    dimension: 'mass',
    value: 5,
    unit: 'gram',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'us-nickel',
    name: 'US nickel mass',
    description: 'Mass of a US five-cent coin',
    dimension: 'mass',
    value: 5,
    unit: 'gram',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'us-quarter',
    name: 'US quarter mass',
    description: 'Mass of a US twenty-five cent coin',
    dimension: 'mass',
    value: 5.67,
    unit: 'gram',
    tags: ['money', 'american', 'everyday'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'ballpoint-pen',
    name: 'Ballpoint pen mass',
    description: 'Mass of a standard disposable pen',
    dimension: 'mass',
    value: 6,
    unit: 'gram',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'pencil-mass',
    name: 'Pencil mass',
    description: 'Mass of a standard #2 pencil',
    dimension: 'mass',
    value: 6.5,
    unit: 'gram',
    tags: ['everyday', 'objects', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'aa-battery',
    name: 'AA battery mass',
    description: 'Mass of an alkaline AA battery',
    dimension: 'mass',
    value: 23,
    unit: 'gram',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'golf-ball-mass',
    name: 'Golf ball mass',
    description: 'Mass of a regulation golf ball',
    dimension: 'mass',
    value: 46,
    unit: 'gram',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: '9v-battery',
    name: '9V battery mass',
    description: 'Mass of a standard 9-volt battery',
    dimension: 'mass',
    value: 47,
    unit: 'gram',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'snickers-bar',
    name: 'Snickers bar mass',
    description: 'Mass of a standard Snickers chocolate bar',
    dimension: 'mass',
    value: 52,
    unit: 'gram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'tennis-ball-mass',
    name: 'Tennis ball mass',
    description: 'Mass of a regulation tennis ball',
    dimension: 'mass',
    value: 58,
    unit: 'gram',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 9,
  },

  // Food items
  {
    id: 'sugar-cube',
    name: 'Sugar cube mass',
    description: 'Mass of a standard sugar cube',
    dimension: 'mass',
    value: 4,
    unit: 'gram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'chicken-egg',
    name: 'Chicken egg mass',
    description: 'Mass of a large chicken egg',
    dimension: 'mass',
    value: 50,
    unit: 'gram',
    valueMin: 45,
    valueMax: 60,
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'banana-mass',
    name: 'Banana mass',
    description: 'Mass of a medium banana',
    dimension: 'mass',
    value: 120,
    unit: 'gram',
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'baseball-mass',
    name: 'Baseball mass',
    description: 'Mass of a regulation baseball',
    dimension: 'mass',
    value: 145,
    unit: 'gram',
    valueMin: 142,
    valueMax: 149,
    tags: ['sports', 'american', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'd-battery',
    name: 'D battery mass',
    description: 'Mass of a standard D-cell battery',
    dimension: 'mass',
    value: 165,
    unit: 'gram',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'apple-mass',
    name: 'Apple mass',
    description: 'Mass of a medium apple',
    dimension: 'mass',
    value: 180,
    unit: 'gram',
    valueMin: 150,
    valueMax: 220,
    tags: ['food', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Everyday objects
  {
    id: 'smartphone-mass',
    name: 'Smartphone mass',
    description: 'Mass of a typical smartphone',
    dimension: 'mass',
    value: 175,
    unit: 'gram',
    valueMin: 140,
    valueMax: 230,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'can-of-soda',
    name: 'Can of soda mass',
    description: 'Mass of a 12oz can of soda',
    dimension: 'mass',
    value: 384,
    unit: 'gram',
    tags: ['food', 'everyday', 'american'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'american-football-mass',
    name: 'American football mass',
    description: 'Mass of a regulation NFL football',
    dimension: 'mass',
    value: 411,
    unit: 'gram',
    valueMin: 397,
    valueMax: 425,
    tags: ['sports', 'american'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'soccer-ball-mass',
    name: 'Soccer ball mass',
    description: 'Mass of a regulation size 5 soccer ball',
    dimension: 'mass',
    value: 432,
    unit: 'gram',
    valueMin: 420,
    valueMax: 445,
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'basketball-mass',
    name: 'Basketball mass',
    description: 'Mass of a regulation basketball',
    dimension: 'mass',
    value: 625,
    unit: 'gram',
    valueMin: 567,
    valueMax: 650,
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'brick-mass',
    name: 'Brick mass',
    description: 'Mass of a standard construction brick',
    dimension: 'mass',
    value: 2.3,
    unit: 'kilogram',
    valueMin: 1.8,
    valueMax: 2.7,
    tags: ['construction', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'chihuahua-mass',
    name: 'Chihuahua mass',
    description: 'Mass of an adult Chihuahua dog',
    dimension: 'mass',
    value: 2.5,
    unit: 'kilogram',
    valueMin: 1.8,
    valueMax: 2.7,
    tags: ['animals', 'pets', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'laptop-mass',
    name: 'Laptop mass',
    description: 'Mass of a typical laptop computer',
    dimension: 'mass',
    value: 2,
    unit: 'kilogram',
    valueMin: 1,
    valueMax: 3,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'housecat-mass',
    name: 'Housecat mass',
    description: 'Mass of an average domestic cat',
    dimension: 'mass',
    value: 4.5,
    unit: 'kilogram',
    valueMin: 3.5,
    valueMax: 5.5,
    tags: ['animals', 'pets', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'bowling-ball',
    name: 'Bowling ball mass',
    description: 'Mass of a typical bowling ball',
    dimension: 'mass',
    value: 6,
    unit: 'kilogram',
    valueMin: 3.6,
    valueMax: 7.26,
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Humans and animals
  {
    id: 'hummingbird-mass',
    name: 'Hummingbird mass',
    description: 'Mass of a typical hummingbird',
    dimension: 'mass',
    value: 4,
    unit: 'gram',
    valueMin: 2,
    valueMax: 6,
    tags: ['animals', 'birds', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'house-sparrow-mass',
    name: 'House sparrow mass',
    description: 'Mass of a common house sparrow',
    dimension: 'mass',
    value: 30,
    unit: 'gram',
    valueMin: 24,
    valueMax: 40,
    tags: ['animals', 'birds', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'human-brain',
    name: 'Human brain mass',
    description: 'Average mass of an adult human brain',
    dimension: 'mass',
    value: 1.35,
    unit: 'kilogram',
    valueMin: 1.2,
    valueMax: 1.5,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'human-heart',
    name: 'Human heart mass',
    description: 'Average mass of an adult human heart',
    dimension: 'mass',
    value: 370,
    unit: 'gram',
    valueMin: 300,
    valueMax: 400,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'human-liver',
    name: 'Human liver mass',
    description: 'Average mass of an adult human liver',
    dimension: 'mass',
    value: 1.5,
    unit: 'kilogram',
    valueMin: 1.2,
    valueMax: 1.8,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'newborn-human',
    name: 'Newborn baby mass',
    description: 'Average mass of a newborn human',
    dimension: 'mass',
    value: 3.4,
    unit: 'kilogram',
    valueMin: 2.5,
    valueMax: 4.5,
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'ostrich-egg',
    name: 'Ostrich egg mass',
    description: 'Mass of an ostrich egg',
    dimension: 'mass',
    value: 1.4,
    unit: 'kilogram',
    valueMin: 1.0,
    valueMax: 2.0,
    tags: ['animals', 'birds', 'nature'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'bicycle-mass',
    name: 'Bicycle mass',
    description: 'Mass of a typical road bike',
    dimension: 'mass',
    value: 9,
    unit: 'kilogram',
    valueMin: 7,
    valueMax: 13,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'chimpanzee-mass',
    name: 'Chimpanzee mass',
    description: 'Mass of an adult male chimpanzee',
    dimension: 'mass',
    value: 55,
    unit: 'kilogram',
    valueMin: 40,
    valueMax: 70,
    tags: ['animals', 'primates', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'adult-human',
    name: 'Adult human mass',
    description: 'Average mass of an adult human',
    dimension: 'mass',
    value: 70,
    unit: 'kilogram',
    valueMin: 50,
    valueMax: 100,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 6,
  },
  {
    id: 'panda-mass',
    name: 'Giant panda mass',
    description: 'Mass of an adult giant panda',
    dimension: 'mass',
    value: 110,
    unit: 'kilogram',
    valueMin: 100,
    valueMax: 150,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'lion-mass',
    name: 'Lion mass',
    description: 'Mass of an adult male lion',
    dimension: 'mass',
    value: 190,
    unit: 'kilogram',
    valueMin: 150,
    valueMax: 225,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'motorcycle-mass',
    name: 'Motorcycle mass',
    description: 'Mass of a typical motorcycle',
    dimension: 'mass',
    value: 230,
    unit: 'kilogram',
    valueMin: 180,
    valueMax: 300,
    tags: ['vehicles', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'gorilla-mass',
    name: 'Gorilla mass',
    description: 'Mass of an adult male gorilla',
    dimension: 'mass',
    value: 180,
    unit: 'kilogram',
    valueMin: 135,
    valueMax: 220,
    tags: ['animals', 'primates', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'grizzly-bear-mass',
    name: 'Grizzly bear mass',
    description: 'Mass of an adult male grizzly bear',
    dimension: 'mass',
    value: 270,
    unit: 'kilogram',
    valueMin: 180,
    valueMax: 360,
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever mass',
    description: 'Mass of an adult Golden Retriever dog',
    dimension: 'mass',
    value: 32,
    unit: 'kilogram',
    valueMin: 25,
    valueMax: 35,
    tags: ['animals', 'pets', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'great-dane-mass',
    name: 'Great Dane mass',
    description: 'Mass of an adult Great Dane dog',
    dimension: 'mass',
    value: 70,
    unit: 'kilogram',
    valueMin: 45,
    valueMax: 90,
    tags: ['animals', 'pets', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'polar-bear-mass',
    name: 'Polar bear mass',
    description: 'Mass of an adult male polar bear',
    dimension: 'mass',
    value: 450,
    unit: 'kilogram',
    valueMin: 350,
    valueMax: 700,
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'horse-mass',
    name: 'Horse mass',
    description: 'Mass of an average horse',
    dimension: 'mass',
    value: 500,
    unit: 'kilogram',
    valueMin: 380,
    valueMax: 1000,
    tags: ['animals', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'cow-mass',
    name: 'Cow mass',
    description: 'Mass of an adult dairy cow',
    dimension: 'mass',
    value: 720,
    unit: 'kilogram',
    valueMin: 400,
    valueMax: 900,
    tags: ['animals', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'grand-piano-mass',
    name: 'Grand piano mass',
    description: 'Mass of a concert grand piano',
    dimension: 'mass',
    value: 480,
    unit: 'kilogram',
    valueMin: 300,
    valueMax: 600,
    tags: ['objects', 'music', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'giraffe-mass',
    name: 'Giraffe mass',
    description: 'Mass of an adult giraffe',
    dimension: 'mass',
    value: 1200,
    unit: 'kilogram',
    valueMin: 800,
    valueMax: 1900,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'great-white-shark-mass',
    name: 'Great white shark mass',
    description: 'Mass of an adult great white shark',
    dimension: 'mass',
    value: 1100,
    unit: 'kilogram',
    valueMin: 680,
    valueMax: 1800,
    tags: ['animals', 'marine', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'hippo-mass',
    name: 'Hippopotamus mass',
    description: 'Mass of an adult hippopotamus',
    dimension: 'mass',
    value: 1500,
    unit: 'kilogram',
    valueMin: 1400,
    valueMax: 4500,
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'white-rhino-mass',
    name: 'White rhinoceros mass',
    description: 'Mass of an adult white rhinoceros',
    dimension: 'mass',
    value: 2300,
    unit: 'kilogram',
    valueMin: 1800,
    valueMax: 3600,
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'orca-mass',
    name: 'Orca (killer whale) mass',
    description: 'Mass of an adult male orca',
    dimension: 'mass',
    value: 5400,
    unit: 'kilogram',
    valueMin: 3600,
    valueMax: 6800,
    tags: ['animals', 'marine', 'universal'],
    relatability: 7,
    accuracy: 7,
  },

  // Large animals
  {
    id: 'elephant-mass',
    name: 'African elephant mass',
    description: 'Mass of an adult African elephant',
    dimension: 'mass',
    value: 6000,
    unit: 'kilogram',
    valueMin: 4000,
    valueMax: 7000,
    tags: ['animals', 'nature', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'blue-whale-mass',
    name: 'Blue whale mass',
    description: 'Mass of an adult blue whale',
    dimension: 'mass',
    value: 150,
    unit: 'metric-ton',
    valueMin: 100,
    valueMax: 200,
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Vehicles
  {
    id: 'car-mass',
    name: 'Car mass',
    description: 'Mass of an average car',
    dimension: 'mass',
    value: 1500,
    unit: 'kilogram',
    valueMin: 1000,
    valueMax: 2000,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'pickup-truck-mass',
    name: 'Pickup truck mass',
    description: 'Mass of a standard pickup truck',
    dimension: 'mass',
    value: 2250,
    unit: 'kilogram',
    valueMin: 1800,
    valueMax: 2700,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'school-bus-mass',
    name: 'School bus mass',
    description: 'Mass of a full-size school bus',
    dimension: 'mass',
    value: 10000,
    unit: 'kilogram',
    tags: ['vehicles', 'american'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'semi-truck-empty',
    name: 'Semi-truck (empty)',
    description: 'Empty mass of a semi-truck with trailer',
    dimension: 'mass',
    value: 16000,
    unit: 'kilogram',
    tags: ['vehicles', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'semi-truck-loaded',
    name: 'Semi-truck (loaded)',
    description: 'Maximum loaded mass of a semi-truck',
    dimension: 'mass',
    value: 36000,
    unit: 'kilogram',
    tags: ['vehicles', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'boeing-747-empty',
    name: 'Boeing 747 (empty)',
    description: 'Empty mass of a Boeing 747-400',
    dimension: 'mass',
    value: 178756,
    unit: 'kilogram',
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'airbus-a380-empty',
    name: 'Airbus A380 (empty)',
    description: 'Empty mass of an Airbus A380',
    dimension: 'mass',
    value: 285000,
    unit: 'kilogram',
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'space-shuttle-orbiter',
    name: 'Space Shuttle orbiter',
    description: 'Mass of the Space Shuttle orbiter',
    dimension: 'mass',
    value: 99000,
    unit: 'kilogram',
    tags: ['vehicles', 'space', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Structures
  {
    id: 'statue-of-liberty',
    name: 'Statue of Liberty (copper)',
    description: 'Mass of the Statue of Liberty copper structure',
    dimension: 'mass',
    value: 204,
    unit: 'metric-ton',
    tags: ['landmarks', 'architecture', 'american'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'international-space-station',
    name: 'International Space Station',
    description: 'Total mass of the ISS',
    dimension: 'mass',
    value: 420000,
    unit: 'kilogram',
    tags: ['space', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'eiffel-tower-mass',
    name: 'Eiffel Tower mass',
    description: 'Total mass of the Eiffel Tower iron structure',
    dimension: 'mass',
    value: 7300,
    unit: 'metric-ton',
    tags: ['landmarks', 'architecture', 'european'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'titanic-mass',
    name: 'RMS Titanic mass',
    description: 'Displacement mass of the Titanic',
    dimension: 'mass',
    value: 52310,
    unit: 'metric-ton',
    tags: ['ships', 'historical', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'cruise-ship-mass',
    name: 'Large cruise ship mass',
    description: 'Gross tonnage of a large modern cruise ship',
    dimension: 'mass',
    value: 100000,
    unit: 'metric-ton',
    tags: ['ships', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'aircraft-carrier-mass',
    name: 'Aircraft carrier mass',
    description: 'Displacement of a modern aircraft carrier',
    dimension: 'mass',
    value: 100000,
    unit: 'metric-ton',
    tags: ['ships', 'military', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'great-pyramid-mass',
    name: 'Great Pyramid of Giza mass',
    description: 'Estimated mass of the Great Pyramid',
    dimension: 'mass',
    value: 6000000,
    unit: 'metric-ton',
    tags: ['landmarks', 'architecture', 'historical'],
    relatability: 7,
    accuracy: 7,
  },

  // Astronomical
  {
    id: 'moon-mass',
    name: 'Moon mass',
    description: "Mass of Earth's Moon",
    dimension: 'mass',
    value: 7.342e22,
    unit: 'kilogram',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'mars-mass',
    name: 'Mars mass',
    description: 'Mass of planet Mars',
    dimension: 'mass',
    value: 6.42e23,
    unit: 'kilogram',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'venus-mass',
    name: 'Venus mass',
    description: 'Mass of planet Venus',
    dimension: 'mass',
    value: 4.87e24,
    unit: 'kilogram',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'earth-mass',
    name: 'Earth mass',
    description: 'Mass of planet Earth',
    dimension: 'mass',
    value: 1,
    unit: 'earth-mass',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'jupiter-mass',
    name: 'Jupiter mass',
    description: 'Mass of planet Jupiter',
    dimension: 'mass',
    value: 1.898e27,
    unit: 'kilogram',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'saturn-mass',
    name: 'Saturn mass',
    description: 'Mass of planet Saturn',
    dimension: 'mass',
    value: 5.68e26,
    unit: 'kilogram',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'sun-mass',
    name: 'Sun mass',
    description: 'Mass of the Sun',
    dimension: 'mass',
    value: 1,
    unit: 'solar-mass',
    tags: ['astronomy', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'black-hole-stellar',
    name: 'Stellar-mass black hole',
    description: 'Mass of a typical stellar-mass black hole',
    dimension: 'mass',
    value: 10,
    unit: 'solar-mass',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 7,
  },
  {
    id: 'sagittarius-a-star',
    name: 'Sagittarius A* black hole',
    description: 'Mass of the supermassive black hole at the Milky Way center',
    dimension: 'mass',
    value: 4.3e6,
    unit: 'solar-mass',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
];
