import type { Measurable } from '@/types';

export const powerMeasurables: Measurable[] = [
  // Biological - Microscopic/Small
  {
    id: 'bee-flight',
    name: 'Honeybee in flight',
    description: 'Metabolic power output of a flying honeybee',
    dimension: 'power',
    value: 1,
    unit: 'milliwatt',
    tags: ['biology', 'insects', 'nature'],
    relatability: 6,
    accuracy: 7,
  },

  // Human body - resting
  {
    id: 'human-brain-power',
    name: 'Human brain',
    description: 'Metabolic power consumption of the human brain at rest',
    dimension: 'power',
    value: 20,
    unit: 'watt',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'human-resting',
    name: 'Human at rest',
    description: 'Basal metabolic rate of an average adult human',
    dimension: 'power',
    value: 100,
    unit: 'watt',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Human activity
  {
    id: 'human-walking',
    name: 'Human walking',
    description: 'Metabolic power output while walking at moderate pace',
    dimension: 'power',
    value: 300,
    unit: 'watt',
    tags: ['human-body', 'activity', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'human-running',
    name: 'Human running',
    description: 'Metabolic power output during moderate running',
    dimension: 'power',
    value: 500,
    unit: 'watt',
    tags: ['human-body', 'activity', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'cyclist-recreational',
    name: 'Recreational cyclist',
    description: 'Mechanical power output of a recreational cyclist',
    dimension: 'power',
    value: 200,
    unit: 'watt',
    tags: ['human-body', 'sports', 'cycling', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'cyclist-elite',
    name: 'Elite cyclist',
    description: 'Sustained power output of an elite cyclist during racing',
    dimension: 'power',
    value: 350,
    unit: 'watt',
    tags: ['human-body', 'sports', 'cycling', 'professional'],
    relatability: 7,
    accuracy: 8,
  },

  // Small electronics and devices
  {
    id: 'smartphone-charging',
    name: 'Smartphone charging',
    description: 'Power consumption while charging a typical smartphone',
    dimension: 'power',
    value: 5,
    unit: 'watt',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'led-bulb-60w-equivalent',
    name: 'LED bulb (60W equivalent)',
    description: 'Modern LED bulb producing light equivalent to a 60W incandescent',
    dimension: 'power',
    value: 10,
    unit: 'watt',
    tags: ['everyday', 'lighting', 'universal'],
    relatability: 10,
    accuracy: 9,
  },
  {
    id: 'wifi-router',
    name: 'WiFi router',
    description: 'Typical home wireless router power consumption',
    dimension: 'power',
    value: 10,
    unit: 'watt',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'laptop-in-use',
    name: 'Laptop computer',
    description: 'Power consumption of a typical laptop during regular use',
    dimension: 'power',
    value: 60,
    unit: 'watt',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'incandescent-bulb-60w',
    name: 'Incandescent bulb (60W)',
    description: 'Traditional 60-watt incandescent light bulb',
    dimension: 'power',
    value: 60,
    unit: 'watt',
    tags: ['everyday', 'lighting', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'desktop-computer',
    name: 'Desktop computer',
    description: 'Power consumption of a typical desktop PC',
    dimension: 'power',
    value: 300,
    unit: 'watt',
    valueMin: 200,
    valueMax: 500,
    tags: ['technology', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Household appliances
  {
    id: 'ceiling-fan',
    name: 'Ceiling fan',
    description: 'Typical ceiling fan on medium speed',
    dimension: 'power',
    value: 75,
    unit: 'watt',
    tags: ['everyday', 'appliances', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'lcd-television-40-inch',
    name: '40-inch LCD TV',
    description: 'Modern 40-inch LCD television',
    dimension: 'power',
    value: 100,
    unit: 'watt',
    tags: ['everyday', 'appliances', 'entertainment', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'refrigerator-power',
    name: 'Refrigerator',
    description: 'Average household refrigerator when running',
    dimension: 'power',
    value: 600,
    unit: 'watt',
    valueMin: 400,
    valueMax: 800,
    tags: ['everyday', 'appliances', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'washing-machine-power',
    name: 'Washing machine',
    description: 'Typical washing machine during operation',
    dimension: 'power',
    value: 500,
    unit: 'watt',
    valueMin: 350,
    valueMax: 1400,
    tags: ['everyday', 'appliances', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'vacuum-cleaner',
    name: 'Vacuum cleaner',
    description: 'Typical household vacuum cleaner',
    dimension: 'power',
    value: 1000,
    unit: 'watt',
    valueMin: 500,
    valueMax: 2000,
    tags: ['everyday', 'appliances', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'microwave-oven-power',
    name: 'Microwave oven',
    description: 'Standard household microwave oven',
    dimension: 'power',
    value: 1200,
    unit: 'watt',
    valueMin: 800,
    valueMax: 1500,
    tags: ['everyday', 'appliances', 'kitchen', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'toaster',
    name: 'Toaster',
    description: 'Typical two-slice toaster',
    dimension: 'power',
    value: 1200,
    unit: 'watt',
    valueMin: 800,
    valueMax: 1800,
    tags: ['everyday', 'appliances', 'kitchen', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'hair-dryer',
    name: 'Hair dryer',
    description: 'Typical household hair dryer on high setting',
    dimension: 'power',
    value: 1500,
    unit: 'watt',
    valueMin: 1200,
    valueMax: 2000,
    tags: ['everyday', 'appliances', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'electric-kettle',
    name: 'Electric kettle',
    description: 'Standard electric kettle for boiling water',
    dimension: 'power',
    value: 1500,
    unit: 'watt',
    valueMin: 1000,
    valueMax: 3000,
    tags: ['everyday', 'appliances', 'kitchen', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'dishwasher',
    name: 'Dishwasher',
    description: 'Standard household dishwasher during operation',
    dimension: 'power',
    value: 1800,
    unit: 'watt',
    valueMin: 1200,
    valueMax: 2400,
    tags: ['everyday', 'appliances', 'kitchen', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'electric-oven',
    name: 'Electric oven',
    description: 'Electric oven on medium-high heat',
    dimension: 'power',
    value: 2400,
    unit: 'watt',
    tags: ['everyday', 'appliances', 'kitchen', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'clothes-dryer-power',
    name: 'Clothes dryer',
    description: 'Electric clothes dryer during operation',
    dimension: 'power',
    value: 3000,
    unit: 'watt',
    valueMin: 1800,
    valueMax: 5000,
    tags: ['everyday', 'appliances', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Power tools
  {
    id: 'power-drill',
    name: 'Power drill',
    description: 'Corded electric power drill',
    dimension: 'power',
    value: 750,
    unit: 'watt',
    valueMin: 500,
    valueMax: 1000,
    tags: ['tools', 'construction', 'everyday'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'chainsaw-electric',
    name: 'Electric chainsaw',
    description: 'Corded electric chainsaw',
    dimension: 'power',
    value: 1800,
    unit: 'watt',
    valueMin: 1200,
    valueMax: 2400,
    tags: ['tools', 'outdoor', 'construction'],
    relatability: 7,
    accuracy: 7,
  },

  // Vehicles - Small
  {
    id: 'electric-bicycle',
    name: 'Electric bicycle motor',
    description: 'Typical e-bike motor power',
    dimension: 'power',
    value: 250,
    unit: 'watt',
    tags: ['transportation', 'electric', 'urban'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'motorcycle-small',
    name: 'Small motorcycle',
    description: 'Engine power of a small 125cc motorcycle',
    dimension: 'power',
    value: 11,
    unit: 'horsepower',
    tags: ['transportation', 'vehicles', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Vehicles - Cars
  {
    id: 'car-headlight-led',
    name: 'Car LED headlight',
    description: 'Modern LED headlight bulb',
    dimension: 'power',
    value: 20,
    unit: 'watt',
    tags: ['automotive', 'technology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'car-headlight-halogen',
    name: 'Car halogen headlight',
    description: 'Traditional halogen headlight bulb',
    dimension: 'power',
    value: 55,
    unit: 'watt',
    tags: ['automotive', 'technology', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'car-sedan-average',
    name: 'Average sedan car',
    description: 'Engine power of a typical compact sedan (Toyota Corolla)',
    dimension: 'power',
    value: 169,
    unit: 'horsepower',
    tags: ['automotive', 'transportation', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'tesla-model-3',
    name: 'Tesla Model 3',
    description: 'Peak motor power of a Tesla Model 3',
    dimension: 'power',
    value: 194,
    unit: 'kilowatt',
    tags: ['automotive', 'electric', 'technology'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'sports-car',
    name: 'Sports car',
    description: 'Typical high-performance sports car engine',
    dimension: 'power',
    value: 450,
    unit: 'horsepower',
    valueMin: 350,
    valueMax: 600,
    tags: ['automotive', 'sports', 'performance'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'formula-1-car',
    name: 'Formula 1 race car',
    description: 'Modern F1 hybrid power unit total output',
    dimension: 'power',
    value: 1000,
    unit: 'horsepower',
    tags: ['automotive', 'sports', 'racing', 'professional'],
    relatability: 8,
    accuracy: 8,
  },

  // Vehicles - Heavy/Large
  {
    id: 'lawn-mower-riding',
    name: 'Riding lawn mower',
    description: 'Gasoline-powered riding lawn mower engine',
    dimension: 'power',
    value: 20,
    unit: 'horsepower',
    tags: ['outdoor', 'tools', 'everyday'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'motorcycle-large',
    name: 'Large motorcycle',
    description: 'Engine power of a large 1000cc+ motorcycle',
    dimension: 'power',
    value: 150,
    unit: 'horsepower',
    valueMin: 120,
    valueMax: 200,
    tags: ['transportation', 'vehicles', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'diesel-locomotive',
    name: 'Diesel-electric locomotive',
    description: 'Power output of an Amtrak ALC-42 locomotive',
    dimension: 'power',
    value: 4200,
    unit: 'horsepower',
    tags: ['transportation', 'trains', 'american'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'container-ship-engine',
    name: 'Container ship engine',
    description: "World's largest container ship engine power",
    dimension: 'power',
    value: 80,
    unit: 'megawatt',
    tags: ['transportation', 'ships', 'maritime'],
    relatability: 5,
    accuracy: 9,
  },

  // Aircraft
  {
    id: 'cessna-172',
    name: 'Cessna 172',
    description: 'Engine power of a popular small aircraft',
    dimension: 'power',
    value: 160,
    unit: 'horsepower',
    tags: ['aviation', 'transportation'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'boeing-737-cruise',
    name: 'Boeing 737 in cruise',
    description: 'Power required to maintain cruise flight',
    dimension: 'power',
    value: 7.2,
    unit: 'megawatt',
    tags: ['aviation', 'transportation', 'commercial'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'boeing-777-engines',
    name: 'Boeing 777 engines',
    description: 'Combined power of two engines at cruise',
    dimension: 'power',
    value: 23,
    unit: 'megawatt',
    tags: ['aviation', 'transportation', 'commercial'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'airbus-a380-takeoff',
    name: 'Airbus A380 at takeoff',
    description: 'Total power of four engines during takeoff',
    dimension: 'power',
    value: 230,
    unit: 'megawatt',
    tags: ['aviation', 'transportation', 'commercial'],
    relatability: 7,
    accuracy: 8,
  },

  // Power generation - Renewable
  {
    id: 'solar-panel-residential-power',
    name: 'Residential solar panel',
    description: 'Power output of a single residential solar panel',
    dimension: 'power',
    value: 300,
    unit: 'watt',
    valueMin: 250,
    valueMax: 400,
    tags: ['renewable-energy', 'solar', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'home-solar-system',
    name: 'Home solar system',
    description: 'Typical residential rooftop solar installation',
    dimension: 'power',
    value: 6,
    unit: 'kilowatt',
    valueMin: 4,
    valueMax: 10,
    tags: ['renewable-energy', 'solar', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'wind-turbine-residential',
    name: 'Residential wind turbine',
    description: 'Small wind turbine for home use',
    dimension: 'power',
    value: 10,
    unit: 'kilowatt',
    valueMin: 5,
    valueMax: 15,
    tags: ['renewable-energy', 'wind', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'wind-turbine-utility',
    name: 'Utility-scale wind turbine',
    description: 'Large modern wind turbine',
    dimension: 'power',
    value: 3,
    unit: 'megawatt',
    tags: ['renewable-energy', 'wind', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Power generation - Large scale
  {
    id: 'iss-solar-arrays',
    name: 'ISS solar arrays',
    description: 'International Space Station total solar array output',
    dimension: 'power',
    value: 240,
    unit: 'kilowatt',
    tags: ['space', 'technology', 'solar', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'submarine-nuclear-reactor',
    name: 'Submarine nuclear reactor',
    description: 'Virginia-class submarine S9G reactor',
    dimension: 'power',
    value: 210,
    unit: 'megawatt',
    tags: ['military', 'nuclear', 'maritime'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'aircraft-carrier-reactor',
    name: 'Aircraft carrier reactor',
    description: 'Single A1B reactor on Gerald R. Ford-class carrier',
    dimension: 'power',
    value: 700,
    unit: 'megawatt',
    tags: ['military', 'nuclear', 'maritime', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'commercial-nuclear-reactor',
    name: 'Commercial nuclear reactor',
    description: 'Average nuclear power plant reactor',
    dimension: 'power',
    value: 900,
    unit: 'megawatt',
    tags: ['power-generation', 'nuclear', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'hoover-dam',
    name: 'Hoover Dam',
    description: 'Total hydroelectric generating capacity',
    dimension: 'power',
    value: 2080,
    unit: 'megawatt',
    tags: ['power-generation', 'hydroelectric', 'american', 'landmarks'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'large-nuclear-reactor',
    name: 'Large nuclear reactor',
    description: 'Modern high-capacity nuclear reactor',
    dimension: 'power',
    value: 1600,
    unit: 'megawatt',
    tags: ['power-generation', 'nuclear', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'coal-power-plant',
    name: 'Large coal power plant',
    description: 'Typical large coal-fired power station',
    dimension: 'power',
    value: 2000,
    unit: 'megawatt',
    valueMin: 1000,
    valueMax: 3000,
    tags: ['power-generation', 'fossil-fuel', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'three-gorges-dam',
    name: 'Three Gorges Dam',
    description: "Total generating capacity of the world's largest power station",
    dimension: 'power',
    value: 22500,
    unit: 'megawatt',
    tags: ['power-generation', 'hydroelectric', 'asian', 'landmarks'],
    relatability: 7,
    accuracy: 10,
  },

  // Natural phenomena
  {
    id: 'lightning-bolt-power',
    name: 'Lightning bolt',
    description: 'Peak power during a lightning strike',
    dimension: 'power',
    value: 1,
    unit: 'gigawatt',
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'hurricane-winds',
    name: 'Hurricane wind power',
    description: 'Energy from winds in a typical mature hurricane',
    dimension: 'power',
    value: 1500,
    unit: 'gigawatt',
    tags: ['nature', 'weather', 'extreme'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'hurricane-total',
    name: 'Hurricane total power',
    description: 'Total energy release including rain formation',
    dimension: 'power',
    value: 600000,
    unit: 'gigawatt',
    tags: ['nature', 'weather', 'extreme'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'mount-st-helens-eruption',
    name: 'Mount St. Helens eruption',
    description: 'Average power during the 1980 volcanic eruption',
    dimension: 'power',
    value: 24000,
    unit: 'gigawatt',
    tags: ['nature', 'geology', 'extreme', 'american'],
    relatability: 7,
    accuracy: 6,
  },

  // Astronomical
  {
    id: 'earth-sunlight-total',
    name: 'Sunlight reaching Earth',
    description: 'Total solar power intercepted by Earth',
    dimension: 'power',
    value: 174000,
    unit: 'gigawatt',
    tags: ['astronomy', 'solar', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'sun-total-output',
    name: 'Sun total power output',
    description: 'Total luminosity of the Sun',
    dimension: 'power',
    value: 3.86e26,
    unit: 'watt',
    tags: ['astronomy', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
];
