import type { Measurable } from '@/types';

export const pressureMeasurables: Measurable[] = [
  // Extreme vacuum
  {
    id: 'intergalactic-space-vacuum',
    name: 'Intergalactic space',
    description: 'Pressure in deep intergalactic space',
    dimension: 'pressure',
    value: 1e-17,
    unit: 'pascal',
    tags: ['astronomy', 'vacuum', 'extreme'],
    relatability: 4,
    accuracy: 7,
  },
  {
    id: 'interstellar-space-vacuum',
    name: 'Interstellar space',
    description: 'Pressure in interstellar space within galaxies',
    dimension: 'pressure',
    value: 1e-15,
    unit: 'pascal',
    tags: ['astronomy', 'vacuum', 'extreme'],
    relatability: 5,
    accuracy: 7,
  },
  {
    id: 'space-simulation-chamber',
    name: 'Space simulation chamber',
    description: 'Pressure in NASA space simulation vacuum chambers',
    dimension: 'pressure',
    value: 5.3e-4,
    unit: 'pascal',
    valueMin: 1.3e-4,
    valueMax: 1.3e-3,
    tags: ['technology', 'aerospace', 'vacuum'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'laboratory-vacuum-pump',
    name: 'Laboratory vacuum pump',
    description: 'Typical high-vacuum laboratory pump pressure',
    dimension: 'pressure',
    value: 1,
    unit: 'pascal',
    valueMin: 0.1,
    valueMax: 10,
    tags: ['science', 'laboratory', 'vacuum'],
    relatability: 5,
    accuracy: 7,
  },

  // Low pressure - altitude and weather
  {
    id: 'low-earth-orbit',
    name: 'Low Earth orbit',
    description: 'Atmospheric pressure at 100 km altitude',
    dimension: 'pressure',
    value: 0.032,
    unit: 'pascal',
    tags: ['aerospace', 'atmosphere'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'mars-surface-pressure',
    name: 'Mars surface',
    description: 'Atmospheric pressure on the surface of Mars',
    dimension: 'pressure',
    value: 600,
    unit: 'pascal',
    tags: ['astronomy', 'planetary'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'typhoon-tip-center',
    name: 'Typhoon Tip center',
    description: 'Lowest non-tornadic pressure ever recorded (1979)',
    dimension: 'pressure',
    value: 87000,
    unit: 'pascal',
    tags: ['weather', 'extreme', 'record'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'hurricane-wilma-center',
    name: 'Hurricane Wilma center',
    description: 'Lowest Atlantic hurricane pressure on record (2005)',
    dimension: 'pressure',
    value: 88200,
    unit: 'pascal',
    tags: ['weather', 'extreme', 'record'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'tornado-center',
    name: 'Tornado center',
    description: 'Estimated pressure at the center of a strong tornado',
    dimension: 'pressure',
    value: 88000,
    unit: 'pascal',
    tags: ['weather', 'extreme'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'mount-everest-summit',
    name: 'Mount Everest summit',
    description: 'Atmospheric pressure at the summit of Mount Everest',
    dimension: 'pressure',
    value: 33700,
    unit: 'pascal',
    tags: ['geography', 'altitude', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'airplane-cabin-pressure',
    name: 'Airplane cabin pressure',
    description: 'Typical cabin pressure at cruising altitude',
    dimension: 'pressure',
    value: 75,
    unit: 'kilopascal',
    valueMin: 75,
    valueMax: 87,
    tags: ['aviation', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Standard atmospheric pressure
  {
    id: 'sea-level-atmosphere',
    name: 'Sea level atmospheric pressure',
    description: 'Standard atmospheric pressure at sea level',
    dimension: 'pressure',
    value: 1,
    unit: 'atmosphere',
    tags: ['atmosphere', 'universal', 'standard'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'record-high-atmosphere',
    name: 'Record high atmospheric pressure',
    description: 'Highest sea-level atmospheric pressure ever recorded',
    dimension: 'pressure',
    value: 108480,
    unit: 'pascal',
    tags: ['weather', 'record', 'extreme'],
    relatability: 6,
    accuracy: 10,
  },

  // Human body
  {
    id: 'cpap-machine',
    name: 'CPAP machine',
    description: 'Typical continuous positive airway pressure for sleep apnea',
    dimension: 'pressure',
    value: 980,
    unit: 'pascal',
    valueMin: 590,
    valueMax: 1370,
    tags: ['medical', 'health'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'blood-pressure-systolic',
    name: 'Blood pressure (systolic)',
    description: 'Normal human systolic blood pressure',
    dimension: 'pressure',
    value: 16,
    unit: 'kilopascal',
    tags: ['biology', 'human-body', 'medical', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'blood-pressure-diastolic',
    name: 'Blood pressure (diastolic)',
    description: 'Normal human diastolic blood pressure',
    dimension: 'pressure',
    value: 11,
    unit: 'kilopascal',
    tags: ['biology', 'human-body', 'medical', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Beverages and food
  {
    id: 'beer-bottle',
    name: 'Beer bottle',
    description: 'Typical pressure inside a sealed beer bottle',
    dimension: 'pressure',
    value: 3,
    unit: 'atmosphere',
    tags: ['food', 'beverages', 'everyday'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'soda-bottle',
    name: 'Soda bottle',
    description: 'Typical pressure inside a carbonated soft drink bottle',
    dimension: 'pressure',
    value: 4,
    unit: 'atmosphere',
    tags: ['food', 'beverages', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'champagne-bottle',
    name: 'Champagne bottle',
    description: 'Pressure inside a sealed champagne bottle',
    dimension: 'pressure',
    value: 6,
    unit: 'atmosphere',
    tags: ['food', 'beverages', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'espresso-extraction',
    name: 'Espresso extraction',
    description: 'Standard pressure for espresso coffee extraction',
    dimension: 'pressure',
    value: 9,
    unit: 'bar',
    tags: ['food', 'beverages', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'pressure-cooker',
    name: 'Pressure cooker',
    description: 'Typical operating pressure of a home pressure cooker',
    dimension: 'pressure',
    value: 15,
    unit: 'psi',
    valueMin: 10,
    valueMax: 15,
    tags: ['everyday', 'cooking', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Tires
  {
    id: 'bicycle-tire-mountain',
    name: 'Mountain bike tire',
    description: 'Typical mountain bike tire pressure',
    dimension: 'pressure',
    value: 30,
    unit: 'psi',
    valueMin: 25,
    valueMax: 35,
    tags: ['sports', 'cycling', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'car-tire',
    name: 'Car tire',
    description: 'Typical passenger car tire pressure',
    dimension: 'pressure',
    value: 32,
    unit: 'psi',
    valueMin: 30,
    valueMax: 35,
    tags: ['automotive', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 9,
  },
  {
    id: 'bicycle-tire-road',
    name: 'Road bike tire',
    description: 'Typical road bike tire pressure',
    dimension: 'pressure',
    value: 90,
    unit: 'psi',
    valueMin: 80,
    valueMax: 100,
    tags: ['sports', 'cycling', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'truck-tire',
    name: 'Semi-truck tire',
    description: 'Typical semi-truck tire pressure',
    dimension: 'pressure',
    value: 100,
    unit: 'psi',
    valueMin: 95,
    valueMax: 110,
    tags: ['automotive', 'commercial'],
    relatability: 7,
    accuracy: 8,
  },

  // Water and diving
  {
    id: 'home-water-pressure',
    name: 'Home water pressure',
    description: 'Typical residential water supply pressure',
    dimension: 'pressure',
    value: 60,
    unit: 'psi',
    valueMin: 40,
    valueMax: 80,
    tags: ['everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'pressure-washer-car',
    name: 'Pressure washer (car washing)',
    description: 'Typical pressure washer for car washing',
    dimension: 'pressure',
    value: 1500,
    unit: 'psi',
    valueMin: 1200,
    valueMax: 1800,
    tags: ['automotive', 'cleaning', 'everyday'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'fire-hose',
    name: 'Fire hose',
    description: 'Working pressure of firefighting attack hose',
    dimension: 'pressure',
    value: 275,
    unit: 'psi',
    valueMin: 100,
    valueMax: 300,
    tags: ['emergency', 'public-safety'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'scuba-diving-10m',
    name: 'Scuba diving at 10m',
    description: 'Water pressure at 10 meters depth',
    dimension: 'pressure',
    value: 2,
    unit: 'atmosphere',
    tags: ['sports', 'diving', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'scuba-diving-30m',
    name: 'Scuba diving at 30m',
    description: 'Water pressure at 30 meters depth (recreational limit)',
    dimension: 'pressure',
    value: 4,
    unit: 'atmosphere',
    tags: ['sports', 'diving', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'scuba-tank',
    name: 'Scuba tank (full)',
    description: 'Pressure inside a full scuba diving air tank',
    dimension: 'pressure',
    value: 3000,
    unit: 'psi',
    tags: ['sports', 'diving', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'deep-ocean-1km',
    name: 'Ocean at 1 km depth',
    description: 'Water pressure at 1 kilometer depth',
    dimension: 'pressure',
    value: 10,
    unit: 'megapascal',
    tags: ['ocean', 'nature'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'mariana-trench',
    name: 'Mariana Trench bottom',
    description: 'Water pressure at the deepest point in the ocean',
    dimension: 'pressure',
    value: 110,
    unit: 'megapascal',
    tags: ['ocean', 'extreme', 'nature', 'universal'],
    relatability: 8,
    accuracy: 9,
  },

  // Industrial and high pressure
  {
    id: 'oxygen-cylinder-medical',
    name: 'Medical oxygen cylinder',
    description: 'Pressure in a full medical oxygen tank',
    dimension: 'pressure',
    value: 2000,
    unit: 'psi',
    tags: ['medical', 'industrial'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'steam-boiler-industrial',
    name: 'Industrial steam boiler',
    description: 'Typical pressure in an industrial power plant boiler',
    dimension: 'pressure',
    value: 12.5,
    unit: 'megapascal',
    tags: ['industrial', 'energy'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'hydraulic-press',
    name: 'Hydraulic press',
    description: 'Typical operating pressure of an industrial hydraulic press',
    dimension: 'pressure',
    value: 20,
    unit: 'megapascal',
    valueMin: 10,
    valueMax: 40,
    tags: ['industrial', 'manufacturing'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'waterjet-cutter',
    name: 'Waterjet cutter',
    description: 'Operating pressure of an industrial waterjet cutting system',
    dimension: 'pressure',
    value: 400,
    unit: 'megapascal',
    valueMin: 300,
    valueMax: 620,
    tags: ['industrial', 'manufacturing', 'technology'],
    relatability: 6,
    accuracy: 8,
  },

  // Planetary atmospheres
  {
    id: 'venus-surface-pressure',
    name: 'Venus surface',
    description: 'Atmospheric pressure on the surface of Venus',
    dimension: 'pressure',
    value: 9.3,
    unit: 'megapascal',
    tags: ['astronomy', 'planetary'],
    relatability: 7,
    accuracy: 9,
  },

  // Extreme pressure - Earth and beyond
  {
    id: 'earth-outer-core',
    name: "Earth's outer core",
    description: 'Pressure at the boundary between mantle and outer core',
    dimension: 'pressure',
    value: 136,
    unit: 'gigapascal',
    tags: ['geology', 'extreme'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'earth-inner-core',
    name: "Earth's inner core",
    description: 'Pressure at the center of the Earth',
    dimension: 'pressure',
    value: 360,
    unit: 'gigapascal',
    tags: ['geology', 'extreme'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'diamond-anvil-cell',
    name: 'Diamond anvil cell',
    description: 'Record pressure achieved in laboratory diamond anvil cell',
    dimension: 'pressure',
    value: 640,
    unit: 'gigapascal',
    tags: ['science', 'laboratory', 'technology', 'extreme', 'record'],
    relatability: 5,
    accuracy: 9,
  },
];
