import type { Measurable } from '@/types';

export const temperatureMeasurables: Measurable[] = [
  // Extreme cold - near absolute zero
  {
    id: 'absolute-zero',
    name: 'Absolute zero',
    description: 'The lowest possible temperature where molecular motion ceases',
    dimension: 'temperature',
    value: 0,
    unit: 'kelvin',
    tags: ['physics', 'theoretical', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'cosmic-microwave-background',
    name: 'Cosmic microwave background',
    description: 'Temperature of space, remnant radiation from the Big Bang',
    dimension: 'temperature',
    value: 2.725,
    unit: 'kelvin',
    tags: ['space', 'astronomy', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'liquid-helium-boiling',
    name: 'Liquid helium boiling point',
    description: 'Boiling point of helium, the coldest liquid',
    dimension: 'temperature',
    value: 4.2,
    unit: 'kelvin',
    tags: ['physics', 'cryogenics', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'liquid-nitrogen-boiling',
    name: 'Liquid nitrogen boiling point',
    description: 'Commonly used cryogenic liquid',
    dimension: 'temperature',
    value: 77,
    unit: 'kelvin',
    tags: ['physics', 'cryogenics', 'science'],
    relatability: 7,
    accuracy: 10,
  },

  // Very cold
  {
    id: 'antarctica-coldest-recorded',
    name: 'Antarctica coldest temperature',
    description: 'Coldest temperature ever recorded at Vostok Station',
    dimension: 'temperature',
    value: -89.2,
    unit: 'celsius',
    tags: ['geography', 'weather', 'extreme', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'dry-ice-sublimation',
    name: 'Dry ice sublimation',
    description: 'Temperature of solid carbon dioxide',
    dimension: 'temperature',
    value: -78.5,
    unit: 'celsius',
    tags: ['science', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'mars-average-temperature',
    name: 'Mars average surface temperature',
    description: 'Average temperature on the surface of Mars',
    dimension: 'temperature',
    value: -63,
    unit: 'celsius',
    tags: ['space', 'astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Cold
  {
    id: 'home-freezer',
    name: 'Home freezer temperature',
    description: 'Standard home freezer setting',
    dimension: 'temperature',
    value: -18,
    unit: 'celsius',
    tags: ['everyday', 'household', 'universal'],
    relatability: 10,
    accuracy: 9,
  },
  {
    id: 'ice-cream-serving',
    name: 'Ice cream serving temperature',
    description: 'Optimal temperature for serving ice cream',
    dimension: 'temperature',
    value: -12,
    unit: 'celsius',
    valueMin: -14,
    valueMax: -10,
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Around freezing
  {
    id: 'water-freezing-point',
    name: 'Water freezing point',
    description: 'Freezing point of water at sea level',
    dimension: 'temperature',
    value: 0,
    unit: 'celsius',
    tags: ['physics', 'universal', 'nature'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'home-refrigerator',
    name: 'Home refrigerator temperature',
    description: 'Standard home refrigerator setting',
    dimension: 'temperature',
    value: 4,
    unit: 'celsius',
    valueMin: 1.7,
    valueMax: 5,
    tags: ['everyday', 'household', 'universal'],
    relatability: 10,
    accuracy: 9,
  },

  // Comfortable temperatures
  {
    id: 'room-temperature',
    name: 'Room temperature',
    description: 'Comfortable indoor temperature',
    dimension: 'temperature',
    value: 21,
    unit: 'celsius',
    valueMin: 20,
    valueMax: 22,
    tags: ['everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },

  // Warm
  {
    id: 'earth-average-temperature',
    name: "Earth's average surface temperature",
    description: 'Average temperature on Earth',
    dimension: 'temperature',
    value: 15,
    unit: 'celsius',
    tags: ['geography', 'nature', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'mars-maximum-temperature',
    name: 'Mars maximum temperature',
    description: 'Maximum temperature recorded on Mars',
    dimension: 'temperature',
    value: 30,
    unit: 'celsius',
    tags: ['space', 'astronomy', 'planetary'],
    relatability: 6,
    accuracy: 8,
  },

  // Body temperature
  {
    id: 'human-body-temperature',
    name: 'Normal human body temperature',
    description: 'Average healthy human body temperature',
    dimension: 'temperature',
    value: 37,
    unit: 'celsius',
    valueMin: 36.5,
    valueMax: 37.5,
    tags: ['human-body', 'medical', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'fever-threshold',
    name: 'Fever threshold',
    description: 'Body temperature considered a fever',
    dimension: 'temperature',
    value: 38,
    unit: 'celsius',
    tags: ['human-body', 'medical', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'high-fever',
    name: 'High fever',
    description: 'High-grade fever requiring medical attention',
    dimension: 'temperature',
    value: 40,
    unit: 'celsius',
    valueMin: 39.1,
    valueMax: 41,
    tags: ['human-body', 'medical', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Hot weather
  {
    id: 'death-valley-hottest',
    name: 'Death Valley hottest temperature',
    description: 'Highest reliably measured temperature on Earth',
    dimension: 'temperature',
    value: 54.4,
    unit: 'celsius',
    tags: ['geography', 'weather', 'extreme', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'hot-coffee-serving',
    name: 'Hot coffee serving temperature',
    description: 'Typical temperature for served hot coffee',
    dimension: 'temperature',
    value: 63,
    unit: 'celsius',
    valueMin: 55,
    valueMax: 70,
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Hot environments
  {
    id: 'sauna-temperature',
    name: 'Sauna temperature',
    description: 'Typical traditional sauna temperature',
    dimension: 'temperature',
    value: 80,
    unit: 'celsius',
    valueMin: 70,
    valueMax: 90,
    tags: ['everyday', 'wellness', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Boiling and cooking
  {
    id: 'water-boiling-point',
    name: 'Water boiling point',
    description: 'Boiling point of water at sea level',
    dimension: 'temperature',
    value: 100,
    unit: 'celsius',
    tags: ['physics', 'cooking', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'oven-baking-temperature',
    name: 'Oven baking temperature',
    description: 'Typical temperature for baking bread or cookies',
    dimension: 'temperature',
    value: 177,
    unit: 'celsius',
    valueMin: 163,
    valueMax: 191,
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'pizza-oven-temperature',
    name: 'Pizza oven temperature',
    description: 'Optimal temperature for baking pizza',
    dimension: 'temperature',
    value: 250,
    unit: 'celsius',
    valueMin: 230,
    valueMax: 260,
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Hot planets
  {
    id: 'mercury-average-temperature',
    name: 'Mercury average surface temperature',
    description: 'Average temperature on Mercury (highly variable)',
    dimension: 'temperature',
    value: 167,
    unit: 'celsius',
    tags: ['space', 'astronomy', 'planetary'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'venus-surface-temperature',
    name: 'Venus surface temperature',
    description: 'Surface temperature on Venus, hottest planet in our solar system',
    dimension: 'temperature',
    value: 464,
    unit: 'celsius',
    tags: ['space', 'astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Very hot - flames and fire
  {
    id: 'candle-flame',
    name: 'Candle flame temperature',
    description: 'Average temperature of a candle flame',
    dimension: 'temperature',
    value: 1000,
    unit: 'celsius',
    valueMin: 600,
    valueMax: 1400,
    tags: ['fire', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'lava-temperature',
    name: 'Lava temperature',
    description: 'Typical temperature of molten lava during eruption',
    dimension: 'temperature',
    value: 1170,
    unit: 'celsius',
    valueMin: 700,
    valueMax: 1250,
    tags: ['geology', 'nature', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Extremely hot - industrial
  {
    id: 'earth-mantle-temperature',
    name: "Earth's mantle temperature",
    description: "Average temperature of Earth's mantle",
    dimension: 'temperature',
    value: 1350,
    unit: 'celsius',
    valueMin: 1000,
    valueMax: 3500,
    tags: ['geology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'steel-melting-point',
    name: 'Steel melting point',
    description: 'Melting point of carbon steel',
    dimension: 'temperature',
    value: 1450,
    unit: 'celsius',
    valueMin: 1370,
    valueMax: 1530,
    tags: ['industrial', 'manufacturing', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'iron-melting-point',
    name: 'Iron melting point',
    description: 'Melting point of pure iron',
    dimension: 'temperature',
    value: 1538,
    unit: 'celsius',
    tags: ['industrial', 'physics', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'tungsten-melting-point',
    name: 'Tungsten melting point',
    description: 'Highest melting point of any pure metal',
    dimension: 'temperature',
    value: 3422,
    unit: 'celsius',
    tags: ['industrial', 'physics', 'extreme'],
    relatability: 6,
    accuracy: 10,
  },

  // Stellar temperatures
  {
    id: 'earth-core-temperature',
    name: "Earth's inner core temperature",
    description: 'Temperature at the center of Earth',
    dimension: 'temperature',
    value: 5430,
    unit: 'celsius',
    valueMin: 5000,
    valueMax: 6000,
    tags: ['geology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'sun-surface-temperature',
    name: 'Sun surface temperature',
    description: "Temperature of the Sun's photosphere",
    dimension: 'temperature',
    value: 5778,
    unit: 'kelvin',
    tags: ['astronomy', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'sun-core-temperature',
    name: 'Sun core temperature',
    description: 'Temperature at the center of the Sun',
    dimension: 'temperature',
    value: 15000000,
    unit: 'kelvin',
    valueMin: 15000000,
    valueMax: 15700000,
    tags: ['astronomy', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Extreme high temperatures
  {
    id: 'lightning-bolt-temperature',
    name: 'Lightning bolt temperature',
    description: 'Temperature of air around a lightning flash',
    dimension: 'temperature',
    value: 30000,
    unit: 'kelvin',
    tags: ['weather', 'nature', 'extreme', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'supernova-core',
    name: 'Supernova core temperature',
    description: 'Temperature at the core during supernova explosion',
    dimension: 'temperature',
    value: 100000000000,
    unit: 'kelvin',
    valueMin: 100000000000,
    valueMax: 200000000000,
    tags: ['astronomy', 'extreme', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
];
