import type { Measurable } from '@/types';

export const timeMeasurables: Measurable[] = [
  // Ultra-short (physics)
  {
    id: 'planck-time',
    name: 'Planck time',
    description: 'The smallest meaningful unit of time in physics',
    dimension: 'time',
    value: 5.39e-44,
    unit: 'second',
    tags: ['physics', 'theoretical', 'universal'],
    relatability: 3,
    accuracy: 10,
  },
  {
    id: 'light-crosses-atom',
    name: 'Light crossing an atom',
    description: 'Time for light to cross a hydrogen atom',
    dimension: 'time',
    value: 0.4,
    unit: 'picosecond',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 4,
    accuracy: 9,
  },

  // Nanoseconds (computing)
  {
    id: 'cpu-clock-cycle-4ghz',
    name: 'CPU clock cycle (4 GHz)',
    description: 'Time for one clock cycle of a 4 GHz processor',
    dimension: 'time',
    value: 0.25,
    unit: 'nanosecond',
    tags: ['technology', 'computing', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'cpu-clock-cycle-1ghz',
    name: 'CPU clock cycle (1 GHz)',
    description: 'Time for one clock cycle of a 1 GHz processor',
    dimension: 'time',
    value: 1,
    unit: 'nanosecond',
    tags: ['technology', 'computing', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'light-travels-one-foot',
    name: 'Light travels one foot',
    description: 'Time for light to travel 1 foot in vacuum',
    dimension: 'time',
    value: 1.017,
    unit: 'nanosecond',
    tags: ['physics', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'gps-timing-accuracy',
    name: 'GPS timing accuracy',
    description: 'Theoretical accuracy of GPS satellite time',
    dimension: 'time',
    value: 14,
    unit: 'nanosecond',
    tags: ['technology', 'navigation', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Microseconds
  {
    id: 'enzymatic-reaction',
    name: 'Enzymatic reaction',
    description: 'Typical duration of a fast enzymatic reaction',
    dimension: 'time',
    value: 10,
    unit: 'microsecond',
    tags: ['biology', 'chemistry', 'universal'],
    relatability: 4,
    accuracy: 7,
  },

  // Milliseconds (perception & biology)
  {
    id: 'neuron-action-potential',
    name: 'Neuron action potential',
    description: 'Duration of a single neuron firing',
    dimension: 'time',
    value: 1,
    unit: 'millisecond',
    tags: ['biology', 'human-body', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'hummingbird-wingbeat',
    name: 'Hummingbird wingbeat',
    description: 'Duration of one wing flap (at 80 Hz)',
    dimension: 'time',
    value: 12.5,
    unit: 'millisecond',
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Very short
  {
    id: 'camera-flash',
    name: 'Camera flash duration',
    description: 'Duration of a typical camera flash',
    dimension: 'time',
    value: 1,
    unit: 'millisecond',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'eye-blink',
    name: 'Eye blink duration',
    description: 'Average duration of a human eye blink',
    dimension: 'time',
    value: 150,
    unit: 'millisecond',
    valueMin: 100,
    valueMax: 400,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'human-reaction-time',
    name: 'Human reaction time',
    description: 'Average simple reaction time for most people',
    dimension: 'time',
    value: 250,
    unit: 'millisecond',
    valueMin: 200,
    valueMax: 300,
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'athlete-reaction-time',
    name: 'Elite athlete reaction time',
    description: 'Reaction time of professional athletes',
    dimension: 'time',
    value: 150,
    unit: 'millisecond',
    valueMin: 100,
    valueMax: 200,
    tags: ['sports', 'human-body', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Short human-scale
  {
    id: 'heartbeat-duration',
    name: 'Heartbeat duration',
    description: 'Time between heartbeats at rest (60 bpm)',
    dimension: 'time',
    value: 1,
    unit: 'second',
    valueMin: 0.6,
    valueMax: 1.2,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'deep-breath',
    name: 'Deep breath',
    description: 'Duration of a single deep breath',
    dimension: 'time',
    value: 5,
    unit: 'second',
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'sneeze-duration',
    name: 'Sneeze duration',
    description: 'Duration of a typical sneeze',
    dimension: 'time',
    value: 0.5,
    unit: 'second',
    tags: ['human-body', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'f1-pit-stop',
    name: 'Formula 1 pit stop',
    description: 'Time to change all four tires',
    dimension: 'time',
    value: 2.5,
    unit: 'second',
    valueMin: 1.8,
    valueMax: 3,
    tags: ['sports', 'racing', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'rocket-engine-ignition',
    name: 'Rocket main engine ignition',
    description: 'Space shuttle main engines start sequence',
    dimension: 'time',
    value: 6.6,
    unit: 'second',
    tags: ['space', 'technology', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: '100m-sprint',
    name: '100m world record sprint',
    description: "Usain Bolt's world record (9.58 seconds)",
    dimension: 'time',
    value: 9.58,
    unit: 'second',
    tags: ['sports', 'athletics', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'tiktok-video',
    name: 'TikTok/Reels sweet spot',
    description: 'Optimal duration for short-form social media',
    dimension: 'time',
    value: 30,
    unit: 'second',
    valueMin: 15,
    valueMax: 60,
    tags: ['media', 'entertainment', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'elevator-burj-khalifa',
    name: 'Burj Khalifa elevator ride',
    description: 'Ground to 124th floor observation deck',
    dimension: 'time',
    value: 60,
    unit: 'second',
    tags: ['architecture', 'technology', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Minutes
  {
    id: 'microwave-minute',
    name: 'Microwave minute',
    description: 'One minute of microwaving (feels longer!)',
    dimension: 'time',
    value: 1,
    unit: 'minute',
    tags: ['everyday', 'humor', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'brushing-teeth',
    name: 'Brushing teeth',
    description: 'Recommended tooth brushing duration',
    dimension: 'time',
    value: 2,
    unit: 'minute',
    tags: ['health', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'quarter-note-60bpm',
    name: 'Quarter note at 60 BPM',
    description: 'Duration of one musical beat in moderate tempo',
    dimension: 'time',
    value: 1,
    unit: 'second',
    tags: ['music', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'commercial-break',
    name: 'TV commercial break',
    description: 'Typical TV commercial break duration',
    dimension: 'time',
    value: 3,
    unit: 'minute',
    valueMin: 2,
    valueMax: 5,
    tags: ['media', 'american', 'everyday'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'pop-song',
    name: 'Pop song length',
    description: 'Average length of a pop song',
    dimension: 'time',
    value: 3.5,
    unit: 'minute',
    valueMin: 3,
    valueMax: 4,
    tags: ['music', 'entertainment', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'boil-egg',
    name: 'Soft-boil an egg',
    description: 'Time to soft-boil an egg',
    dimension: 'time',
    value: 6,
    unit: 'minute',
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'shower-duration',
    name: 'Average shower',
    description: 'Typical shower duration',
    dimension: 'time',
    value: 9,
    unit: 'minute',
    valueMin: 5,
    valueMax: 15,
    tags: ['everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'nascar-pit-stop',
    name: 'NASCAR pit stop',
    description: 'Four tire change plus refueling',
    dimension: 'time',
    value: 14,
    unit: 'second',
    valueMin: 12,
    valueMax: 16,
    tags: ['sports', 'racing', 'american'],
    relatability: 7,
    accuracy: 8,
  },

  // Hours
  {
    id: 'light-earth-to-moon',
    name: 'Light travel to Moon',
    description: 'Time for light to travel from Earth to Moon',
    dimension: 'time',
    value: 1.28,
    unit: 'second',
    tags: ['space', 'astronomy', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'marathon-world-record',
    name: 'Marathon world record',
    description: 'Fastest marathon time (2:00:35)',
    dimension: 'time',
    value: 2.01,
    unit: 'hour',
    tags: ['sports', 'athletics', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'movie-length',
    name: 'Average movie length',
    description: 'Duration of an average feature film',
    dimension: 'time',
    value: 2,
    unit: 'hour',
    valueMin: 1.5,
    valueMax: 2.5,
    tags: ['entertainment', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'nfl-game',
    name: 'NFL game duration',
    description: 'Average American football game length',
    dimension: 'time',
    value: 3.2,
    unit: 'hour',
    valueMin: 3,
    valueMax: 3.5,
    tags: ['sports', 'american', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'concorde-transatlantic',
    name: 'Concorde supersonic flight',
    description: 'London to New York on Concorde',
    dimension: 'time',
    value: 3,
    unit: 'hour',
    valueMin: 2.9,
    valueMax: 3.5,
    tags: ['aviation', 'travel', 'historical'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'soccer-match',
    name: 'Soccer match duration',
    description: 'Full 90-minute match plus halftime',
    dimension: 'time',
    value: 2,
    unit: 'hour',
    tags: ['sports', 'international', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'workday',
    name: 'Standard workday',
    description: 'Duration of a standard 8-hour workday',
    dimension: 'time',
    value: 8,
    unit: 'hour',
    tags: ['work', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'sleep-duration',
    name: "Night's sleep",
    description: 'Recommended adult sleep duration',
    dimension: 'time',
    value: 8,
    unit: 'hour',
    valueMin: 7,
    valueMax: 9,
    tags: ['human-body', 'health', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'transatlantic-flight',
    name: 'Transatlantic flight',
    description: 'New York to London flight time',
    dimension: 'time',
    value: 7,
    unit: 'hour',
    valueMin: 6.5,
    valueMax: 8,
    tags: ['travel', 'aviation', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'light-earth-to-sun',
    name: 'Light travel to Sun',
    description: 'Time for light to travel from Earth to Sun',
    dimension: 'time',
    value: 8.3,
    unit: 'minute',
    tags: ['space', 'astronomy', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'voyager-to-neptune',
    name: 'Voyager 2 to Neptune',
    description: 'Time for Voyager 2 to reach Neptune from Earth',
    dimension: 'time',
    value: 12,
    unit: 'year',
    tags: ['space', 'exploration', 'universal'],
    relatability: 6,
    accuracy: 10,
  },

  // Days
  {
    id: 'earth-rotation',
    name: 'Earth rotation',
    description: 'Time for Earth to complete one rotation (sidereal day)',
    dimension: 'time',
    value: 23.934,
    unit: 'hour',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'weekend',
    name: 'Weekend duration',
    description: 'Duration of a two-day weekend',
    dimension: 'time',
    value: 2,
    unit: 'day',
    tags: ['everyday', 'work', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'work-week',
    name: 'Work week',
    description: 'Standard 5-day work week',
    dimension: 'time',
    value: 5,
    unit: 'day',
    tags: ['work', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'mouse-gestation',
    name: 'Mouse pregnancy',
    description: 'Gestation period of a mouse',
    dimension: 'time',
    value: 19,
    unit: 'day',
    tags: ['animals', 'biology', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Weeks/Months
  {
    id: 'lunar-month',
    name: 'Lunar month',
    description: 'Time between full moons',
    dimension: 'time',
    value: 29.53,
    unit: 'day',
    tags: ['astronomy', 'nature', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'dog-gestation',
    name: 'Dog pregnancy',
    description: 'Average gestation period for dogs',
    dimension: 'time',
    value: 63,
    unit: 'day',
    valueMin: 58,
    valueMax: 68,
    tags: ['animals', 'biology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'cat-gestation',
    name: 'Cat pregnancy',
    description: 'Average gestation period for cats',
    dimension: 'time',
    value: 64,
    unit: 'day',
    valueMin: 58,
    valueMax: 67,
    tags: ['animals', 'biology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'human-pregnancy',
    name: 'Human pregnancy',
    description: 'Average human gestation period',
    dimension: 'time',
    value: 9,
    unit: 'month',
    valueMin: 8,
    valueMax: 10,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'elephant-gestation',
    name: 'Elephant pregnancy',
    description: 'African elephant gestation period',
    dimension: 'time',
    value: 645,
    unit: 'day',
    tags: ['animals', 'biology', 'universal'],
    relatability: 7,
    accuracy: 9,
  },

  // Years
  {
    id: 'earth-orbit',
    name: 'Earth orbit (year)',
    description: 'Time for Earth to orbit the Sun',
    dimension: 'time',
    value: 1,
    unit: 'year',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'dog-year',
    name: 'Dog year',
    description: "One year in a dog's life",
    dimension: 'time',
    value: 1,
    unit: 'year',
    tags: ['animals', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'mars-orbit',
    name: 'Mars orbital period',
    description: 'Time for Mars to orbit the Sun',
    dimension: 'time',
    value: 1.88,
    unit: 'year',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'olympic-cycle',
    name: 'Olympic cycle',
    description: 'Time between Summer Olympics',
    dimension: 'time',
    value: 4,
    unit: 'year',
    tags: ['sports', 'international', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'jupiter-orbit',
    name: 'Jupiter orbital period',
    description: 'Time for Jupiter to orbit the Sun',
    dimension: 'time',
    value: 11.86,
    unit: 'year',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'saturn-orbit',
    name: 'Saturn orbital period',
    description: 'Time for Saturn to orbit the Sun',
    dimension: 'time',
    value: 29.46,
    unit: 'year',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'us-presidential-term',
    name: 'US presidential term',
    description: 'Duration of one US presidential term',
    dimension: 'time',
    value: 4,
    unit: 'year',
    tags: ['politics', 'american'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'world-cup-cycle',
    name: 'World Cup cycle',
    description: 'Time between FIFA World Cups',
    dimension: 'time',
    value: 4,
    unit: 'year',
    tags: ['sports', 'international', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'carbon-14-half-life',
    name: 'Carbon-14 half-life',
    description: 'Radioactive decay half-life of carbon-14',
    dimension: 'time',
    value: 5730,
    unit: 'year',
    tags: ['physics', 'archaeology', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'sequoia-lifespan',
    name: 'Giant sequoia lifespan',
    description: 'Age of oldest known giant sequoia tree',
    dimension: 'time',
    value: 3200,
    unit: 'year',
    tags: ['nature', 'biology', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Human lifespan
  {
    id: 'periodical-cicada-13yr',
    name: '13-year cicada cycle',
    description: 'Periodical cicada emergence period',
    dimension: 'time',
    value: 13,
    unit: 'year',
    tags: ['animals', 'nature', 'biology'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'childhood',
    name: 'Childhood years',
    description: 'Birth to age 12',
    dimension: 'time',
    value: 12,
    unit: 'year',
    tags: ['human-body', 'development', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'periodical-cicada-17yr',
    name: '17-year cicada cycle',
    description: 'Periodical cicada emergence period',
    dimension: 'time',
    value: 17,
    unit: 'year',
    tags: ['animals', 'nature', 'biology'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'generation',
    name: 'Human generation',
    description: 'Average time between generations',
    dimension: 'time',
    value: 25,
    unit: 'year',
    valueMin: 20,
    valueMax: 30,
    tags: ['human-body', 'demographics', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'halleys-comet',
    name: "Halley's Comet orbit",
    description: 'Time between appearances of Halley\'s Comet',
    dimension: 'time',
    value: 76,
    unit: 'year',
    valueMin: 74,
    valueMax: 79,
    tags: ['astronomy', 'space', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'human-lifespan',
    name: 'Human lifespan',
    description: 'Average human lifespan in developed countries',
    dimension: 'time',
    value: 80,
    unit: 'year',
    valueMin: 70,
    valueMax: 85,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Historical
  {
    id: 'century',
    name: 'Century',
    description: 'One hundred years',
    dimension: 'time',
    value: 100,
    unit: 'year',
    tags: ['historical', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'since-moon-landing',
    name: 'Since Moon landing',
    description: 'Time since Apollo 11 (1969)',
    dimension: 'time',
    value: 56,
    unit: 'year',
    tags: ['historical', 'space', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'since-world-war-2',
    name: 'Since World War II',
    description: 'Time since end of WWII (1945)',
    dimension: 'time',
    value: 80,
    unit: 'year',
    tags: ['historical', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'age-of-pyramids',
    name: 'Age of the Pyramids',
    description: 'Time since the Great Pyramid was built',
    dimension: 'time',
    value: 4500,
    unit: 'year',
    tags: ['historical', 'ancient', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'bristlecone-pine-age',
    name: 'Oldest living tree',
    description: 'Age of the oldest bristlecone pine',
    dimension: 'time',
    value: 5060,
    unit: 'year',
    tags: ['nature', 'biology', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'written-history',
    name: 'Written history',
    description: 'Time since earliest written records',
    dimension: 'time',
    value: 5000,
    unit: 'year',
    tags: ['historical', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'ice-age-end',
    name: 'End of last ice age',
    description: 'Time since the last glacial period ended',
    dimension: 'time',
    value: 11700,
    unit: 'year',
    tags: ['geology', 'climate', 'universal'],
    relatability: 6,
    accuracy: 9,
  },

  // Geological/Cosmic
  {
    id: 'dinosaur-reign',
    name: 'Dinosaur reign',
    description: 'Duration dinosaurs dominated Earth',
    dimension: 'time',
    value: 165,
    unit: 'million-years',
    tags: ['paleontology', 'geology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'since-dinosaurs',
    name: 'Since dinosaur extinction',
    description: 'Time since the K-Pg extinction event',
    dimension: 'time',
    value: 66,
    unit: 'million-years',
    tags: ['geology', 'paleontology', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'uranium-238-half-life',
    name: 'Uranium-238 half-life',
    description: 'Radioactive decay half-life of uranium-238',
    dimension: 'time',
    value: 4.5,
    unit: 'billion-years',
    tags: ['physics', 'geology', 'universal'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'age-of-earth',
    name: 'Age of Earth',
    description: 'Time since Earth formed',
    dimension: 'time',
    value: 4.54,
    unit: 'billion-years',
    tags: ['geology', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'age-of-universe',
    name: 'Age of the Universe',
    description: 'Time since the Big Bang',
    dimension: 'time',
    value: 13.8,
    unit: 'billion-years',
    tags: ['astronomy', 'cosmology', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
];
