import type { Measurable } from '@/types';

export const timeMeasurables: Measurable[] = [
  // Ultra-short (physics)
  {
    id: 'planck-time',
    name: 'Planck time',
    description: 'The smallest meaningful unit of time in physics',
    dimension: 'time',
    value: 5.39e-44,
    unit: 'second',
    tags: ['physics', 'theoretical', 'universal'],
    relatability: 3,
    accuracy: 10,
  },
  {
    id: 'light-crosses-atom',
    name: 'Light crossing an atom',
    description: 'Time for light to cross a hydrogen atom',
    dimension: 'time',
    value: 0.4,
    unit: 'picosecond',
    tags: ['physics', 'atomic', 'universal'],
    relatability: 4,
    accuracy: 9,
  },

  // Very short
  {
    id: 'camera-flash',
    name: 'Camera flash duration',
    description: 'Duration of a typical camera flash',
    dimension: 'time',
    value: 1,
    unit: 'millisecond',
    tags: ['technology', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'eye-blink',
    name: 'Eye blink duration',
    description: 'Average duration of a human eye blink',
    dimension: 'time',
    value: 150,
    unit: 'millisecond',
    valueMin: 100,
    valueMax: 400,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Short human-scale
  {
    id: 'heartbeat-duration',
    name: 'Heartbeat duration',
    description: 'Time between heartbeats at rest (60 bpm)',
    dimension: 'time',
    value: 1,
    unit: 'second',
    valueMin: 0.6,
    valueMax: 1.2,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'deep-breath',
    name: 'Deep breath',
    description: 'Duration of a single deep breath',
    dimension: 'time',
    value: 5,
    unit: 'second',
    tags: ['human-body', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'sneeze-duration',
    name: 'Sneeze duration',
    description: 'Duration of a typical sneeze',
    dimension: 'time',
    value: 0.5,
    unit: 'second',
    tags: ['human-body', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Minutes
  {
    id: 'microwave-minute',
    name: 'Microwave minute',
    description: 'One minute of microwaving (feels longer!)',
    dimension: 'time',
    value: 1,
    unit: 'minute',
    tags: ['everyday', 'humor', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'commercial-break',
    name: 'TV commercial break',
    description: 'Typical TV commercial break duration',
    dimension: 'time',
    value: 3,
    unit: 'minute',
    valueMin: 2,
    valueMax: 5,
    tags: ['media', 'american', 'everyday'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'pop-song',
    name: 'Pop song length',
    description: 'Average length of a pop song',
    dimension: 'time',
    value: 3.5,
    unit: 'minute',
    valueMin: 3,
    valueMax: 4,
    tags: ['music', 'entertainment', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'boil-egg',
    name: 'Soft-boil an egg',
    description: 'Time to soft-boil an egg',
    dimension: 'time',
    value: 6,
    unit: 'minute',
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Hours
  {
    id: 'movie-length',
    name: 'Average movie length',
    description: 'Duration of an average feature film',
    dimension: 'time',
    value: 2,
    unit: 'hour',
    valueMin: 1.5,
    valueMax: 2.5,
    tags: ['entertainment', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'workday',
    name: 'Standard workday',
    description: 'Duration of a standard 8-hour workday',
    dimension: 'time',
    value: 8,
    unit: 'hour',
    tags: ['work', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'sleep-duration',
    name: "Night's sleep",
    description: 'Recommended adult sleep duration',
    dimension: 'time',
    value: 8,
    unit: 'hour',
    valueMin: 7,
    valueMax: 9,
    tags: ['human-body', 'health', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'transatlantic-flight',
    name: 'Transatlantic flight',
    description: 'New York to London flight time',
    dimension: 'time',
    value: 7,
    unit: 'hour',
    valueMin: 6.5,
    valueMax: 8,
    tags: ['travel', 'aviation', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Days
  {
    id: 'earth-rotation',
    name: 'Earth rotation',
    description: 'Time for Earth to complete one rotation (sidereal day)',
    dimension: 'time',
    value: 23.934,
    unit: 'hour',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'weekend',
    name: 'Weekend duration',
    description: 'Duration of a two-day weekend',
    dimension: 'time',
    value: 2,
    unit: 'day',
    tags: ['everyday', 'work', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'work-week',
    name: 'Work week',
    description: 'Standard 5-day work week',
    dimension: 'time',
    value: 5,
    unit: 'day',
    tags: ['work', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },

  // Weeks/Months
  {
    id: 'lunar-month',
    name: 'Lunar month',
    description: 'Time between full moons',
    dimension: 'time',
    value: 29.53,
    unit: 'day',
    tags: ['astronomy', 'nature', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'human-pregnancy',
    name: 'Human pregnancy',
    description: 'Average human gestation period',
    dimension: 'time',
    value: 9,
    unit: 'month',
    valueMin: 8,
    valueMax: 10,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 10,
    accuracy: 8,
  },

  // Years
  {
    id: 'earth-orbit',
    name: 'Earth orbit (year)',
    description: 'Time for Earth to orbit the Sun',
    dimension: 'time',
    value: 1,
    unit: 'year',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'dog-year',
    name: 'Dog year',
    description: "One year in a dog's life",
    dimension: 'time',
    value: 1,
    unit: 'year',
    tags: ['animals', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'olympic-cycle',
    name: 'Olympic cycle',
    description: 'Time between Summer Olympics',
    dimension: 'time',
    value: 4,
    unit: 'year',
    tags: ['sports', 'international', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'us-presidential-term',
    name: 'US presidential term',
    description: 'Duration of one US presidential term',
    dimension: 'time',
    value: 4,
    unit: 'year',
    tags: ['politics', 'american'],
    relatability: 8,
    accuracy: 10,
  },

  // Human lifespan
  {
    id: 'childhood',
    name: 'Childhood years',
    description: 'Birth to age 12',
    dimension: 'time',
    value: 12,
    unit: 'year',
    tags: ['human-body', 'development', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'generation',
    name: 'Human generation',
    description: 'Average time between generations',
    dimension: 'time',
    value: 25,
    unit: 'year',
    valueMin: 20,
    valueMax: 30,
    tags: ['human-body', 'demographics', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'human-lifespan',
    name: 'Human lifespan',
    description: 'Average human lifespan in developed countries',
    dimension: 'time',
    value: 80,
    unit: 'year',
    valueMin: 70,
    valueMax: 85,
    tags: ['human-body', 'universal'],
    relatability: 10,
    accuracy: 7,
  },

  // Historical
  {
    id: 'century',
    name: 'Century',
    description: 'One hundred years',
    dimension: 'time',
    value: 100,
    unit: 'year',
    tags: ['historical', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'since-moon-landing',
    name: 'Since Moon landing',
    description: 'Time since Apollo 11 (1969)',
    dimension: 'time',
    value: 56,
    unit: 'year',
    tags: ['historical', 'space', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'since-world-war-2',
    name: 'Since World War II',
    description: 'Time since end of WWII (1945)',
    dimension: 'time',
    value: 80,
    unit: 'year',
    tags: ['historical', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'age-of-pyramids',
    name: 'Age of the Pyramids',
    description: 'Time since the Great Pyramid was built',
    dimension: 'time',
    value: 4500,
    unit: 'year',
    tags: ['historical', 'ancient', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Geological/Cosmic
  {
    id: 'since-dinosaurs',
    name: 'Since dinosaur extinction',
    description: 'Time since the K-Pg extinction event',
    dimension: 'time',
    value: 66,
    unit: 'million-years',
    tags: ['geology', 'paleontology', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'age-of-earth',
    name: 'Age of Earth',
    description: 'Time since Earth formed',
    dimension: 'time',
    value: 4.54,
    unit: 'billion-years',
    tags: ['geology', 'planetary', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'age-of-universe',
    name: 'Age of the Universe',
    description: 'Time since the Big Bang',
    dimension: 'time',
    value: 13.8,
    unit: 'billion-years',
    tags: ['astronomy', 'cosmology', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
];
