import type { Measurable } from '@/types';

export const velocityMeasurables: Measurable[] = [
  // Very slow
  {
    id: 'continental-drift',
    name: 'Continental drift speed',
    description: 'Speed at which tectonic plates move (~2.5 cm/year)',
    dimension: 'velocity',
    value: 7.9e-10,
    unit: 'meter-per-second',
    tags: ['geology', 'nature', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'hair-growth',
    name: 'Hair growth speed',
    description: 'Rate at which human hair grows',
    dimension: 'velocity',
    value: 1.25e-8,
    unit: 'meter-per-second',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'snail-speed',
    name: 'Snail speed',
    description: 'Speed of a garden snail',
    dimension: 'velocity',
    value: 0.03,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'three-toed-sloth',
    name: 'Three-toed sloth',
    description: 'Slowest land mammal',
    dimension: 'velocity',
    value: 0.15,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'galapagos-tortoise',
    name: 'Galapagos tortoise',
    description: 'One of the slowest reptiles',
    dimension: 'velocity',
    value: 0.3,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 7,
  },

  // Human speeds
  {
    id: 'walking-speed',
    name: 'Walking speed',
    description: 'Average human walking pace',
    dimension: 'velocity',
    value: 5,
    unit: 'kilometer-per-hour',
    valueMin: 4,
    valueMax: 6,
    tags: ['human-body', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'jogging-speed',
    name: 'Jogging speed',
    description: 'Average jogging pace',
    dimension: 'velocity',
    value: 8,
    unit: 'kilometer-per-hour',
    valueMin: 6,
    valueMax: 10,
    tags: ['human-body', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'running-speed',
    name: 'Running speed',
    description: 'Average running speed',
    dimension: 'velocity',
    value: 15,
    unit: 'kilometer-per-hour',
    tags: ['human-body', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'usain-bolt',
    name: 'Usain Bolt top speed',
    description: "Usain Bolt's record top speed",
    dimension: 'velocity',
    value: 44.72,
    unit: 'kilometer-per-hour',
    tags: ['sports', 'human-body', 'universal'],
    relatability: 8,
    accuracy: 10,
  },
  {
    id: 'swimming-speed',
    name: 'Olympic swimming speed',
    description: '50m freestyle record pace',
    dimension: 'velocity',
    value: 8.45,
    unit: 'kilometer-per-hour',
    tags: ['sports', 'human-body', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'cycling-sprint',
    name: 'Track cycling sprint',
    description: '200m flying start record by François Pervis',
    dimension: 'velocity',
    value: 76.6,
    unit: 'kilometer-per-hour',
    tags: ['sports', 'human-body', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'downhill-skiing',
    name: 'Olympic downhill skiing',
    description: 'Top speed in alpine skiing competition',
    dimension: 'velocity',
    value: 100.6,
    unit: 'mile-per-hour',
    tags: ['sports', 'winter-sports', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'speed-skiing',
    name: 'Speed skiing record',
    description: 'World record by Ivan Origone',
    dimension: 'velocity',
    value: 254,
    unit: 'kilometer-per-hour',
    tags: ['sports', 'winter-sports', 'extreme'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'skeleton-sled',
    name: 'Skeleton sled',
    description: 'Top speed in Olympic skeleton event',
    dimension: 'velocity',
    value: 91,
    unit: 'mile-per-hour',
    tags: ['sports', 'winter-sports', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'luge-sled',
    name: 'Luge sled',
    description: 'Top speed in Olympic luge',
    dimension: 'velocity',
    value: 90,
    unit: 'mile-per-hour',
    tags: ['sports', 'winter-sports', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'bobsled-four-man',
    name: '4-man bobsled',
    description: 'Top speed in Olympic bobsled',
    dimension: 'velocity',
    value: 95.4,
    unit: 'mile-per-hour',
    tags: ['sports', 'winter-sports', 'universal'],
    relatability: 6,
    accuracy: 8,
  },

  // Animals - slow
  {
    id: 'elephant-seal-land',
    name: 'Elephant seal on land',
    description: 'Speed of an elephant seal moving on land',
    dimension: 'velocity',
    value: 4,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'marine'],
    relatability: 5,
    accuracy: 7,
  },

  // Animals - insects
  {
    id: 'house-fly',
    name: 'House fly speed',
    description: 'Flying speed of a common house fly',
    dimension: 'velocity',
    value: 7,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'mosquito-flight',
    name: 'Mosquito flight',
    description: 'Flying speed of a mosquito',
    dimension: 'velocity',
    value: 2,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 6,
    accuracy: 6,
  },
  {
    id: 'bee-speed',
    name: 'Bee flight speed',
    description: 'Cruising speed of a honeybee',
    dimension: 'velocity',
    value: 24,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'dragonfly-speed',
    name: 'Dragonfly speed',
    description: 'Flying speed of a dragonfly',
    dimension: 'velocity',
    value: 35,
    unit: 'mile-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'hornet-speed',
    name: 'Hornet flight',
    description: 'Flying speed of a hornet',
    dimension: 'velocity',
    value: 15.6,
    unit: 'mile-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'butterfly-skipper',
    name: 'Skipper butterfly',
    description: 'Speed of a skipper butterfly',
    dimension: 'velocity',
    value: 37,
    unit: 'mile-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 5,
    accuracy: 7,
  },

  // Animals - land mammals
  {
    id: 'elephant-charge',
    name: 'Elephant charging',
    description: 'Charging speed of an African elephant',
    dimension: 'velocity',
    value: 25,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'alligator-land',
    name: 'Alligator on land',
    description: 'Short burst speed on land',
    dimension: 'velocity',
    value: 11,
    unit: 'mile-per-hour',
    tags: ['animals', 'reptiles', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'crocodile-sprint',
    name: 'Crocodile sprint',
    description: 'Short burst land speed of a Nile crocodile',
    dimension: 'velocity',
    value: 20,
    unit: 'mile-per-hour',
    tags: ['animals', 'reptiles', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'black-mamba',
    name: 'Black mamba',
    description: 'Fastest land snake',
    dimension: 'velocity',
    value: 20,
    unit: 'mile-per-hour',
    tags: ['animals', 'reptiles', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'kangaroo-hop',
    name: 'Kangaroo hopping',
    description: 'Maximum hopping speed',
    dimension: 'velocity',
    value: 44,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'greyhound-racing',
    name: 'Greyhound racing',
    description: 'Top speed of a racing greyhound',
    dimension: 'velocity',
    value: 45,
    unit: 'mile-per-hour',
    tags: ['animals', 'sports', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'horse-gallop',
    name: 'Horse galloping',
    description: 'Speed of a galloping horse',
    dimension: 'velocity',
    value: 55,
    unit: 'kilometer-per-hour',
    valueMin: 40,
    valueMax: 70,
    tags: ['animals', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'pronghorn-antelope',
    name: 'Pronghorn antelope',
    description: 'Second fastest land animal, sustained speed',
    dimension: 'velocity',
    value: 55,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'ostrich-run',
    name: 'Ostrich running',
    description: 'Fastest running bird',
    dimension: 'velocity',
    value: 40,
    unit: 'mile-per-hour',
    tags: ['animals', 'birds', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'cheetah-speed',
    name: 'Cheetah top speed',
    description: 'Maximum speed of a cheetah',
    dimension: 'velocity',
    value: 120,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Animals - birds and bats
  {
    id: 'hummingbird-flight',
    name: 'Hummingbird flight',
    description: 'Typical flight speed',
    dimension: 'velocity',
    value: 30,
    unit: 'mile-per-hour',
    tags: ['animals', 'birds', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'pigeon-flight',
    name: 'Pigeon flight',
    description: 'Racing pigeon top speed',
    dimension: 'velocity',
    value: 93,
    unit: 'mile-per-hour',
    tags: ['animals', 'birds', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'bat-flight',
    name: 'Brazilian free-tailed bat',
    description: 'Fastest bat in level flight',
    dimension: 'velocity',
    value: 100,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'peregrine-falcon',
    name: 'Peregrine falcon dive',
    description: 'Diving speed of a peregrine falcon',
    dimension: 'velocity',
    value: 390,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'birds', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Animals - marine
  {
    id: 'sea-turtle',
    name: 'Leatherback sea turtle',
    description: 'Fastest sea turtle',
    dimension: 'velocity',
    value: 22,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'gentoo-penguin',
    name: 'Gentoo penguin',
    description: 'Fastest swimming penguin',
    dimension: 'velocity',
    value: 22,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'dolphin-swim',
    name: 'Dolphin swimming',
    description: 'Common dolphin swimming speed',
    dimension: 'velocity',
    value: 25,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'orca-swim',
    name: 'Killer whale (orca)',
    description: 'Top speed of an orca',
    dimension: 'velocity',
    value: 34.5,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'mako-shark',
    name: 'Shortfin mako shark',
    description: 'Fastest shark species',
    dimension: 'velocity',
    value: 43,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'bluefin-tuna',
    name: 'Bluefin tuna',
    description: 'Speed in a 20-second dash',
    dimension: 'velocity',
    value: 43.4,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'sailfish-speed',
    name: 'Sailfish',
    description: 'Fastest fish in the ocean',
    dimension: 'velocity',
    value: 68,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'black-marlin',
    name: 'Black marlin',
    description: 'One of the fastest marine animals',
    dimension: 'velocity',
    value: 82,
    unit: 'mile-per-hour',
    tags: ['animals', 'marine', 'universal'],
    relatability: 5,
    accuracy: 7,
  },

  // Vehicles - ground (slow)
  {
    id: 'golf-cart',
    name: 'Golf cart',
    description: 'Standard electric golf cart speed',
    dimension: 'velocity',
    value: 13,
    unit: 'mile-per-hour',
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'electric-scooter',
    name: 'Electric scooter',
    description: 'Typical e-scooter speed',
    dimension: 'velocity',
    value: 20,
    unit: 'mile-per-hour',
    valueMin: 15,
    valueMax: 25,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'bicycle-speed',
    name: 'Bicycle speed',
    description: 'Average cycling speed',
    dimension: 'velocity',
    value: 20,
    unit: 'kilometer-per-hour',
    valueMin: 15,
    valueMax: 25,
    tags: ['vehicles', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'city-driving',
    name: 'City driving speed',
    description: 'Average speed in city traffic',
    dimension: 'velocity',
    value: 40,
    unit: 'kilometer-per-hour',
    valueMin: 30,
    valueMax: 50,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'highway-driving',
    name: 'Highway driving speed',
    description: 'Typical highway driving speed',
    dimension: 'velocity',
    value: 110,
    unit: 'kilometer-per-hour',
    valueMin: 90,
    valueMax: 130,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'snowmobile-average',
    name: 'Snowmobile',
    description: 'Average snowmobile top speed',
    dimension: 'velocity',
    value: 95,
    unit: 'mile-per-hour',
    tags: ['vehicles', 'winter-sports', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'roller-coaster',
    name: 'Roller coaster',
    description: 'Kingda Ka record-holding coaster',
    dimension: 'velocity',
    value: 128,
    unit: 'mile-per-hour',
    tags: ['vehicles', 'entertainment', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'high-speed-train',
    name: 'High-speed train',
    description: 'Cruising speed of a bullet train',
    dimension: 'velocity',
    value: 320,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'trains', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'motorcycle-record',
    name: 'Motorcycle land speed record',
    description: 'Ack Attack streamliner record',
    dimension: 'velocity',
    value: 376.36,
    unit: 'mile-per-hour',
    tags: ['vehicles', 'sports', 'extreme'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'f1-car',
    name: 'Formula 1 car top speed',
    description: 'Top speed of a Formula 1 race car',
    dimension: 'velocity',
    value: 370,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'sports', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'land-speed-record',
    name: 'Land speed record',
    description: 'ThrustSSC supersonic car',
    dimension: 'velocity',
    value: 763,
    unit: 'mile-per-hour',
    tags: ['vehicles', 'extreme', 'universal'],
    relatability: 6,
    accuracy: 10,
  },

  // Vehicles - water
  {
    id: 'sailboat-cruising',
    name: 'Sailboat cruising',
    description: 'Typical sailboat cruising speed',
    dimension: 'velocity',
    value: 6,
    unit: 'knot',
    valueMin: 4,
    valueMax: 8,
    tags: ['vehicles', 'water', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'cruise-ship',
    name: 'Cruise ship',
    description: 'Typical cruise ship service speed',
    dimension: 'velocity',
    value: 21,
    unit: 'knot',
    tags: ['vehicles', 'water', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'submarine-akula',
    name: 'Akula-class submarine',
    description: 'Submerged speed of Russian Akula submarine',
    dimension: 'velocity',
    value: 35,
    unit: 'knot',
    tags: ['vehicles', 'military', 'water'],
    relatability: 5,
    accuracy: 7,
  },

  // Vehicles - air
  {
    id: 'commercial-airplane',
    name: 'Commercial airplane',
    description: 'Cruising speed of a commercial jet',
    dimension: 'velocity',
    value: 900,
    unit: 'kilometer-per-hour',
    valueMin: 800,
    valueMax: 950,
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'concorde',
    name: 'Concorde cruising speed',
    description: 'Cruising speed of the Concorde (Mach 2)',
    dimension: 'velocity',
    value: 2180,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'aviation', 'historical'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'sr71-blackbird',
    name: 'SR-71 Blackbird',
    description: 'Top speed of the SR-71 spy plane',
    dimension: 'velocity',
    value: 3540,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'aviation', 'military'],
    relatability: 6,
    accuracy: 9,
  },

  // Projectiles - sports
  {
    id: 'soccer-kick',
    name: 'Soccer ball kick',
    description: 'Fastest recorded shot by Ronny Heberson',
    dimension: 'velocity',
    value: 131,
    unit: 'mile-per-hour',
    tags: ['sports', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'baseball-pitch',
    name: 'Baseball fastball',
    description: 'Speed of a professional fastball pitch',
    dimension: 'velocity',
    value: 160,
    unit: 'kilometer-per-hour',
    valueMin: 145,
    valueMax: 170,
    tags: ['sports', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'hockey-slapshot',
    name: 'Hockey slapshot',
    description: 'Record slapshot speed',
    dimension: 'velocity',
    value: 110,
    unit: 'mile-per-hour',
    tags: ['sports', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'tennis-serve',
    name: 'Tennis serve',
    description: 'Professional tennis serve speed',
    dimension: 'velocity',
    value: 200,
    unit: 'kilometer-per-hour',
    valueMin: 180,
    valueMax: 250,
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'golf-ball-drive',
    name: 'Golf ball drive',
    description: 'Record golf ball speed off the club',
    dimension: 'velocity',
    value: 241.6,
    unit: 'mile-per-hour',
    tags: ['sports', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'badminton-smash',
    name: 'Badminton smash',
    description: 'Fastest recorded shuttlecock speed',
    dimension: 'velocity',
    value: 306,
    unit: 'mile-per-hour',
    tags: ['sports', 'universal'],
    relatability: 6,
    accuracy: 10,
  },

  // Projectiles - weapons
  {
    id: 'bullet-speed',
    name: 'Bullet speed',
    description: 'Muzzle velocity of a 9mm handgun',
    dimension: 'velocity',
    value: 375,
    unit: 'meter-per-second',
    tags: ['weapons', 'physics', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'rifle-bullet',
    name: 'Rifle bullet speed',
    description: 'Muzzle velocity of an assault rifle',
    dimension: 'velocity',
    value: 940,
    unit: 'meter-per-second',
    tags: ['weapons', 'military', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Natural phenomena
  {
    id: 'gentle-breeze',
    name: 'Gentle breeze',
    description: 'Light wind, enough to wave a flag',
    dimension: 'velocity',
    value: 10,
    unit: 'knot',
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'breezy-wind',
    name: 'Breezy conditions',
    description: 'Sustained breezy winds',
    dimension: 'velocity',
    value: 20,
    unit: 'mile-per-hour',
    valueMin: 15,
    valueMax: 25,
    tags: ['nature', 'weather', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'avalanche-dry',
    name: 'Dry snow avalanche',
    description: 'Typical dry avalanche speed',
    dimension: 'velocity',
    value: 70,
    unit: 'mile-per-hour',
    valueMin: 60,
    valueMax: 80,
    tags: ['nature', 'extreme', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'hurricane-category-1',
    name: 'Category 1 hurricane',
    description: 'Minimum hurricane wind speed',
    dimension: 'velocity',
    value: 74,
    unit: 'mile-per-hour',
    tags: ['nature', 'weather', 'extreme'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'category-5-hurricane',
    name: 'Category 5 hurricane',
    description: 'Strongest hurricane category winds',
    dimension: 'velocity',
    value: 157,
    unit: 'mile-per-hour',
    tags: ['nature', 'weather', 'extreme'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'tornado-ef5',
    name: 'EF5 tornado',
    description: 'Strongest tornado wind speeds',
    dimension: 'velocity',
    value: 250,
    unit: 'mile-per-hour',
    tags: ['nature', 'weather', 'extreme'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'tsunami-ocean',
    name: 'Tsunami in deep ocean',
    description: 'Speed of tsunami wave in deep water',
    dimension: 'velocity',
    value: 500,
    unit: 'mile-per-hour',
    tags: ['nature', 'extreme', 'universal'],
    relatability: 6,
    accuracy: 8,
  },

  // Physics and space
  {
    id: 'speed-of-sound',
    name: 'Speed of sound',
    description: 'Speed of sound in air at sea level',
    dimension: 'velocity',
    value: 1,
    unit: 'mach',
    tags: ['physics', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'earth-rotation-equator',
    name: 'Earth rotation at equator',
    description: 'Rotational speed at the equator',
    dimension: 'velocity',
    value: 1000,
    unit: 'mile-per-hour',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'escape-velocity-earth',
    name: 'Earth escape velocity',
    description: "Minimum speed to escape Earth's gravity",
    dimension: 'velocity',
    value: 11.2,
    unit: 'kilometer-per-second',
    tags: ['physics', 'space', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'voyager-1-speed',
    name: 'Voyager 1 speed',
    description: 'Speed of the Voyager 1 spacecraft',
    dimension: 'velocity',
    value: 17,
    unit: 'kilometer-per-second',
    tags: ['space', 'spacecraft', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'iss-orbital-speed',
    name: 'ISS orbital speed',
    description: 'International Space Station orbit speed',
    dimension: 'velocity',
    value: 17136,
    unit: 'mile-per-hour',
    tags: ['space', 'spacecraft', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'space-shuttle-orbit',
    name: 'Space Shuttle orbital speed',
    description: 'Speed to maintain low Earth orbit',
    dimension: 'velocity',
    value: 17500,
    unit: 'mile-per-hour',
    tags: ['space', 'spacecraft', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'apollo-10-record',
    name: 'Apollo 10 speed record',
    description: 'Fastest crewed vehicle speed',
    dimension: 'velocity',
    value: 24791,
    unit: 'mile-per-hour',
    tags: ['space', 'spacecraft', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'earth-orbital-speed',
    name: "Earth's orbital speed",
    description: 'Speed of Earth orbiting the Sun',
    dimension: 'velocity',
    value: 30,
    unit: 'kilometer-per-second',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'new-horizons-launch',
    name: 'New Horizons launch speed',
    description: 'Fastest spacecraft launch speed',
    dimension: 'velocity',
    value: 36373,
    unit: 'mile-per-hour',
    tags: ['space', 'spacecraft', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'parker-solar-probe',
    name: 'Parker Solar Probe',
    description: 'Fastest human-made object',
    dimension: 'velocity',
    value: 430000,
    unit: 'mile-per-hour',
    tags: ['space', 'spacecraft', 'extreme'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'solar-system-galactic-orbit',
    name: 'Solar system through galaxy',
    description: 'Speed of solar system orbiting Milky Way center',
    dimension: 'velocity',
    value: 514000,
    unit: 'mile-per-hour',
    tags: ['astronomy', 'extreme', 'universal'],
    relatability: 4,
    accuracy: 7,
  },
  {
    id: 'speed-of-light',
    name: 'Speed of light',
    description: 'Speed of light in a vacuum',
    dimension: 'velocity',
    value: 1,
    unit: 'speed-of-light',
    tags: ['physics', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
];
