import type { Measurable } from '@/types';

export const velocityMeasurables: Measurable[] = [
  // Very slow
  {
    id: 'snail-speed',
    name: 'Snail speed',
    description: 'Speed of a garden snail',
    dimension: 'velocity',
    value: 0.03,
    unit: 'mile-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'continental-drift',
    name: 'Continental drift speed',
    description: 'Speed at which tectonic plates move (~2.5 cm/year)',
    dimension: 'velocity',
    value: 7.9e-10,
    unit: 'meter-per-second',
    tags: ['geology', 'nature', 'universal'],
    relatability: 6,
    accuracy: 7,
  },
  {
    id: 'hair-growth',
    name: 'Hair growth speed',
    description: 'Rate at which human hair grows',
    dimension: 'velocity',
    value: 1.25e-8,
    unit: 'meter-per-second',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 7,
  },

  // Human speeds
  {
    id: 'walking-speed',
    name: 'Walking speed',
    description: 'Average human walking pace',
    dimension: 'velocity',
    value: 5,
    unit: 'kilometer-per-hour',
    valueMin: 4,
    valueMax: 6,
    tags: ['human-body', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'jogging-speed',
    name: 'Jogging speed',
    description: 'Average jogging pace',
    dimension: 'velocity',
    value: 8,
    unit: 'kilometer-per-hour',
    valueMin: 6,
    valueMax: 10,
    tags: ['human-body', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'running-speed',
    name: 'Running speed',
    description: 'Average running speed',
    dimension: 'velocity',
    value: 15,
    unit: 'kilometer-per-hour',
    tags: ['human-body', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'usain-bolt',
    name: 'Usain Bolt top speed',
    description: "Usain Bolt's record top speed",
    dimension: 'velocity',
    value: 44.72,
    unit: 'kilometer-per-hour',
    tags: ['sports', 'human-body', 'universal'],
    relatability: 8,
    accuracy: 10,
  },

  // Animals
  {
    id: 'house-fly',
    name: 'House fly speed',
    description: 'Flying speed of a common house fly',
    dimension: 'velocity',
    value: 7,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'bee-speed',
    name: 'Bee flight speed',
    description: 'Cruising speed of a honeybee',
    dimension: 'velocity',
    value: 24,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'insects', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'horse-gallop',
    name: 'Horse galloping',
    description: 'Speed of a galloping horse',
    dimension: 'velocity',
    value: 55,
    unit: 'kilometer-per-hour',
    valueMin: 40,
    valueMax: 70,
    tags: ['animals', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'cheetah-speed',
    name: 'Cheetah top speed',
    description: 'Maximum speed of a cheetah',
    dimension: 'velocity',
    value: 120,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'nature', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'peregrine-falcon',
    name: 'Peregrine falcon dive',
    description: 'Diving speed of a peregrine falcon',
    dimension: 'velocity',
    value: 390,
    unit: 'kilometer-per-hour',
    tags: ['animals', 'birds', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Vehicles - ground
  {
    id: 'bicycle-speed',
    name: 'Bicycle speed',
    description: 'Average cycling speed',
    dimension: 'velocity',
    value: 20,
    unit: 'kilometer-per-hour',
    valueMin: 15,
    valueMax: 25,
    tags: ['vehicles', 'sports', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'city-driving',
    name: 'City driving speed',
    description: 'Average speed in city traffic',
    dimension: 'velocity',
    value: 40,
    unit: 'kilometer-per-hour',
    valueMin: 30,
    valueMax: 50,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'highway-driving',
    name: 'Highway driving speed',
    description: 'Typical highway driving speed',
    dimension: 'velocity',
    value: 110,
    unit: 'kilometer-per-hour',
    valueMin: 90,
    valueMax: 130,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'high-speed-train',
    name: 'High-speed train',
    description: 'Cruising speed of a bullet train',
    dimension: 'velocity',
    value: 320,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'trains', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'f1-car',
    name: 'Formula 1 car top speed',
    description: 'Top speed of a Formula 1 race car',
    dimension: 'velocity',
    value: 370,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'sports', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Vehicles - air/water
  {
    id: 'commercial-airplane',
    name: 'Commercial airplane',
    description: 'Cruising speed of a commercial jet',
    dimension: 'velocity',
    value: 900,
    unit: 'kilometer-per-hour',
    valueMin: 800,
    valueMax: 950,
    tags: ['vehicles', 'aviation', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'concorde',
    name: 'Concorde cruising speed',
    description: 'Cruising speed of the Concorde (Mach 2)',
    dimension: 'velocity',
    value: 2180,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'aviation', 'historical'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'sr71-blackbird',
    name: 'SR-71 Blackbird',
    description: 'Top speed of the SR-71 spy plane',
    dimension: 'velocity',
    value: 3540,
    unit: 'kilometer-per-hour',
    tags: ['vehicles', 'aviation', 'military'],
    relatability: 6,
    accuracy: 9,
  },

  // Projectiles and weapons
  {
    id: 'baseball-pitch',
    name: 'Baseball fastball',
    description: 'Speed of a professional fastball pitch',
    dimension: 'velocity',
    value: 160,
    unit: 'kilometer-per-hour',
    valueMin: 145,
    valueMax: 170,
    tags: ['sports', 'american'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'tennis-serve',
    name: 'Tennis serve',
    description: 'Professional tennis serve speed',
    dimension: 'velocity',
    value: 200,
    unit: 'kilometer-per-hour',
    valueMin: 180,
    valueMax: 250,
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'bullet-speed',
    name: 'Bullet speed',
    description: 'Muzzle velocity of a 9mm handgun',
    dimension: 'velocity',
    value: 375,
    unit: 'meter-per-second',
    tags: ['weapons', 'physics', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'rifle-bullet',
    name: 'Rifle bullet speed',
    description: 'Muzzle velocity of an assault rifle',
    dimension: 'velocity',
    value: 940,
    unit: 'meter-per-second',
    tags: ['weapons', 'military', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Physics references
  {
    id: 'speed-of-sound',
    name: 'Speed of sound',
    description: 'Speed of sound in air at sea level',
    dimension: 'velocity',
    value: 1,
    unit: 'mach',
    tags: ['physics', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'escape-velocity-earth',
    name: 'Earth escape velocity',
    description: "Minimum speed to escape Earth's gravity",
    dimension: 'velocity',
    value: 11.2,
    unit: 'kilometer-per-second',
    tags: ['physics', 'space', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'earth-orbital-speed',
    name: "Earth's orbital speed",
    description: 'Speed of Earth orbiting the Sun',
    dimension: 'velocity',
    value: 30,
    unit: 'kilometer-per-second',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'voyager-1-speed',
    name: 'Voyager 1 speed',
    description: 'Speed of the Voyager 1 spacecraft',
    dimension: 'velocity',
    value: 17,
    unit: 'kilometer-per-second',
    tags: ['space', 'spacecraft', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'speed-of-light',
    name: 'Speed of light',
    description: 'Speed of light in a vacuum',
    dimension: 'velocity',
    value: 1,
    unit: 'speed-of-light',
    tags: ['physics', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
];
