import type { Measurable } from '@/types';

export const volumeMeasurables: Measurable[] = [
  // Tiny
  {
    id: 'raindrop-volume',
    name: 'Raindrop volume',
    description: 'Volume of a typical raindrop',
    dimension: 'volume',
    value: 0.05,
    unit: 'milliliter',
    valueMin: 0.01,
    valueMax: 0.1,
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'eyedrop',
    name: 'Eyedrop',
    description: 'Volume of a single eyedrop',
    dimension: 'volume',
    value: 0.05,
    unit: 'milliliter',
    tags: ['medical', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },

  // Kitchen small
  {
    id: 'teaspoon-volume',
    name: 'Teaspoon',
    description: 'Volume of one teaspoon',
    dimension: 'volume',
    value: 1,
    unit: 'teaspoon',
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'tablespoon-volume',
    name: 'Tablespoon',
    description: 'Volume of one tablespoon',
    dimension: 'volume',
    value: 1,
    unit: 'tablespoon',
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'shot-glass',
    name: 'Shot glass',
    description: 'Volume of a standard shot glass',
    dimension: 'volume',
    value: 44,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },

  // Drinks
  {
    id: 'espresso-shot',
    name: 'Espresso shot',
    description: 'Volume of a single espresso shot',
    dimension: 'volume',
    value: 30,
    unit: 'milliliter',
    tags: ['beverages', 'coffee', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'soda-can',
    name: 'Soda can',
    description: 'Volume of a standard 12 oz soda can',
    dimension: 'volume',
    value: 355,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'american'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'water-bottle',
    name: 'Water bottle',
    description: 'Standard disposable water bottle',
    dimension: 'volume',
    value: 500,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 9,
  },
  {
    id: 'wine-bottle',
    name: 'Wine bottle',
    description: 'Standard wine bottle',
    dimension: 'volume',
    value: 750,
    unit: 'milliliter',
    tags: ['beverages', 'alcohol', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'beer-pitcher',
    name: 'Beer pitcher',
    description: 'Standard restaurant beer pitcher',
    dimension: 'volume',
    value: 1.9,
    unit: 'liter',
    tags: ['beverages', 'alcohol', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Kitchen larger
  {
    id: 'milk-carton',
    name: 'Milk carton',
    description: 'Half-gallon milk carton',
    dimension: 'volume',
    value: 1.89,
    unit: 'liter',
    tags: ['food', 'everyday', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'cooking-pot',
    name: 'Large cooking pot',
    description: 'Volume of a large stock pot',
    dimension: 'volume',
    value: 8,
    unit: 'liter',
    valueMin: 6,
    valueMax: 12,
    tags: ['cooking', 'kitchen', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Human body
  {
    id: 'human-stomach',
    name: 'Human stomach capacity',
    description: 'Maximum capacity of an adult human stomach',
    dimension: 'volume',
    value: 1,
    unit: 'liter',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'human-blood-volume',
    name: 'Human blood volume',
    description: 'Total blood in adult human body',
    dimension: 'volume',
    value: 5,
    unit: 'liter',
    valueMin: 4.5,
    valueMax: 5.5,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'human-lung-capacity',
    name: 'Human lung capacity',
    description: 'Total lung capacity of an adult',
    dimension: 'volume',
    value: 6,
    unit: 'liter',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Household
  {
    id: 'bucket',
    name: 'Standard bucket',
    description: 'Volume of a standard 5-gallon bucket',
    dimension: 'volume',
    value: 19,
    unit: 'liter',
    tags: ['household', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'bathtub',
    name: 'Bathtub',
    description: 'Volume of water in a full bathtub',
    dimension: 'volume',
    value: 300,
    unit: 'liter',
    valueMin: 200,
    valueMax: 400,
    tags: ['household', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 6,
  },
  {
    id: 'hot-tub',
    name: 'Hot tub',
    description: 'Volume of a standard hot tub',
    dimension: 'volume',
    value: 1500,
    unit: 'liter',
    valueMin: 1000,
    valueMax: 2000,
    tags: ['household', 'recreation', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Vehicles
  {
    id: 'car-gas-tank',
    name: 'Car gas tank',
    description: 'Average car fuel tank capacity',
    dimension: 'volume',
    value: 50,
    unit: 'liter',
    valueMin: 40,
    valueMax: 70,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'fuel-truck',
    name: 'Fuel tanker truck',
    description: 'Capacity of a fuel tanker truck',
    dimension: 'volume',
    value: 34000,
    unit: 'liter',
    valueMin: 20000,
    valueMax: 45000,
    tags: ['vehicles', 'industrial', 'universal'],
    relatability: 6,
    accuracy: 6,
  },

  // Pools and large containers
  {
    id: 'shipping-container',
    name: 'Shipping container',
    description: 'Volume of a 40-foot shipping container',
    dimension: 'volume',
    value: 67.7,
    unit: 'cubic-meter',
    tags: ['industrial', 'logistics', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'olympic-pool',
    name: 'Olympic swimming pool',
    description: 'Volume of an Olympic-size swimming pool',
    dimension: 'volume',
    value: 2500,
    unit: 'cubic-meter',
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 10,
  },

  // Large natural
  {
    id: 'oil-supertanker',
    name: 'Oil supertanker capacity',
    description: 'Cargo capacity of a large oil tanker',
    dimension: 'volume',
    value: 500000,
    unit: 'cubic-meter',
    valueMin: 300000,
    valueMax: 550000,
    tags: ['ships', 'industrial', 'universal'],
    relatability: 6,
    accuracy: 7,
  },

  // Geographic
  {
    id: 'lake-tahoe',
    name: 'Lake Tahoe volume',
    description: 'Volume of water in Lake Tahoe',
    dimension: 'volume',
    value: 150.7,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'lake-superior',
    name: 'Lake Superior volume',
    description: 'Volume of the largest Great Lake',
    dimension: 'volume',
    value: 12100,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'mediterranean-sea',
    name: 'Mediterranean Sea volume',
    description: 'Total volume of the Mediterranean Sea',
    dimension: 'volume',
    value: 3750000,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'all-ocean-water',
    name: 'All ocean water',
    description: "Total volume of Earth's oceans",
    dimension: 'volume',
    value: 1.335e9,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },

  // Astronomical
  {
    id: 'earth-volume',
    name: 'Earth volume',
    description: 'Total volume of planet Earth',
    dimension: 'volume',
    value: 1.08321e12,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'sun-volume',
    name: 'Sun volume',
    description: 'Total volume of the Sun',
    dimension: 'volume',
    value: 1.41e18,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
];
