import type { Measurable } from '@/types';

export const volumeMeasurables: Measurable[] = [
  // Microscopic
  {
    id: 'red-blood-cell-volume',
    name: 'Red blood cell',
    description: 'Volume of a single red blood cell',
    dimension: 'volume',
    value: 0.00009,
    unit: 'milliliter',
    valueMin: 0.00008,
    valueMax: 0.0001,
    tags: ['biology', 'human-body', 'microscopic', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'aspirin-tablet',
    name: 'Aspirin tablet',
    description: 'Standard 325mg aspirin tablet',
    dimension: 'volume',
    value: 0.23,
    unit: 'milliliter',
    valueMin: 0.16,
    valueMax: 0.25,
    tags: ['medical', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'grain-of-rice-volume',
    name: 'Grain of rice',
    description: 'Volume of a single grain of rice',
    dimension: 'volume',
    value: 0.01,
    unit: 'milliliter',
    valueMin: 0.005,
    valueMax: 0.029,
    tags: ['food', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'standard-die',
    name: 'Six-sided die',
    description: 'Standard gaming die cube',
    dimension: 'volume',
    value: 4.1,
    unit: 'milliliter',
    tags: ['games', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Tiny
  {
    id: 'raindrop-volume',
    name: 'Raindrop volume',
    description: 'Volume of a typical raindrop',
    dimension: 'volume',
    value: 0.05,
    unit: 'milliliter',
    valueMin: 0.01,
    valueMax: 0.1,
    tags: ['nature', 'weather', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'eyedrop',
    name: 'Eyedrop',
    description: 'Volume of a single eyedrop',
    dimension: 'volume',
    value: 0.05,
    unit: 'milliliter',
    tags: ['medical', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'thimble',
    name: 'Thimble',
    description: 'Volume of a sewing thimble',
    dimension: 'volume',
    value: 5,
    unit: 'milliliter',
    valueMin: 2,
    valueMax: 10,
    tags: ['sewing', 'crafts', 'everyday', 'universal'],
    relatability: 7,
    accuracy: 6,
  },
  {
    id: 'human-eyeball',
    name: 'Human eyeball',
    description: 'Volume of an adult human eye',
    dimension: 'volume',
    value: 6.5,
    unit: 'milliliter',
    valueMin: 5.7,
    valueMax: 6.5,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'ping-pong-ball',
    name: 'Ping pong ball',
    description: 'Table tennis ball',
    dimension: 'volume',
    value: 33.5,
    unit: 'milliliter',
    tags: ['sports', 'games', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'golf-ball',
    name: 'Golf ball',
    description: 'Standard regulation golf ball',
    dimension: 'volume',
    value: 40.7,
    unit: 'milliliter',
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 10,
  },

  // Kitchen small
  {
    id: 'teaspoon-volume',
    name: 'Teaspoon',
    description: 'Volume of one teaspoon',
    dimension: 'volume',
    value: 1,
    unit: 'teaspoon',
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'tablespoon-volume',
    name: 'Tablespoon',
    description: 'Volume of one tablespoon',
    dimension: 'volume',
    value: 1,
    unit: 'tablespoon',
    tags: ['cooking', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'medicine-dropper',
    name: 'Medicine dropper',
    description: 'Typical medicine dropper capacity',
    dimension: 'volume',
    value: 1,
    unit: 'milliliter',
    tags: ['medical', 'everyday', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'shot-glass',
    name: 'Shot glass',
    description: 'Volume of a standard shot glass',
    dimension: 'volume',
    value: 44,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'tennis-ball',
    name: 'Tennis ball',
    description: 'Regulation tennis ball',
    dimension: 'volume',
    value: 155,
    unit: 'milliliter',
    valueMin: 150,
    valueMax: 160,
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'baseball',
    name: 'Baseball',
    description: 'Major League Baseball regulation ball',
    dimension: 'volume',
    value: 210,
    unit: 'milliliter',
    valueMin: 202,
    valueMax: 219,
    tags: ['sports', 'american', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'champagne-flute',
    name: 'Champagne flute',
    description: 'Standard champagne glass capacity',
    dimension: 'volume',
    value: 185,
    unit: 'milliliter',
    valueMin: 150,
    valueMax: 220,
    tags: ['beverages', 'alcohol', 'universal'],
    relatability: 8,
    accuracy: 7,
  },

  // Drinks
  {
    id: 'espresso-shot',
    name: 'Espresso shot',
    description: 'Volume of a single espresso shot',
    dimension: 'volume',
    value: 30,
    unit: 'milliliter',
    tags: ['beverages', 'coffee', 'universal'],
    relatability: 9,
    accuracy: 8,
  },
  {
    id: 'tea-cup',
    name: 'Tea cup',
    description: 'Volume of a typical tea cup',
    dimension: 'volume',
    value: 180,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'coffee-mug',
    name: 'Coffee mug',
    description: 'Standard coffee mug capacity',
    dimension: 'volume',
    value: 300,
    unit: 'milliliter',
    valueMin: 240,
    valueMax: 475,
    tags: ['beverages', 'coffee', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 7,
  },
  {
    id: 'soda-can',
    name: 'Soda can',
    description: 'Volume of a standard 12 oz soda can',
    dimension: 'volume',
    value: 355,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'american'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'water-bottle',
    name: 'Water bottle',
    description: 'Standard disposable water bottle',
    dimension: 'volume',
    value: 500,
    unit: 'milliliter',
    tags: ['beverages', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 9,
  },
  {
    id: 'wine-bottle',
    name: 'Wine bottle',
    description: 'Standard wine bottle',
    dimension: 'volume',
    value: 750,
    unit: 'milliliter',
    tags: ['beverages', 'alcohol', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'soup-bowl',
    name: 'Soup bowl',
    description: 'Volume of a typical soup bowl',
    dimension: 'volume',
    value: 400,
    unit: 'milliliter',
    valueMin: 300,
    valueMax: 500,
    tags: ['food', 'kitchen', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'beer-pitcher',
    name: 'Beer pitcher',
    description: 'Standard restaurant beer pitcher',
    dimension: 'volume',
    value: 1.9,
    unit: 'liter',
    tags: ['beverages', 'alcohol', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'human-brain-volume',
    name: 'Human brain',
    description: 'Average adult human brain volume',
    dimension: 'volume',
    value: 1.35,
    unit: 'liter',
    valueMin: 1.2,
    valueMax: 1.5,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'human-heart-volume',
    name: 'Human heart',
    description: 'Total blood capacity of human heart chambers',
    dimension: 'volume',
    value: 0.28,
    unit: 'liter',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'volleyball',
    name: 'Volleyball',
    description: 'Regulation volleyball',
    dimension: 'volume',
    value: 4.19,
    unit: 'liter',
    tags: ['sports', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'soccer-ball',
    name: 'Soccer ball',
    description: 'FIFA regulation soccer ball',
    dimension: 'volume',
    value: 5.5,
    unit: 'liter',
    valueMin: 5.3,
    valueMax: 5.8,
    tags: ['sports', 'universal'],
    relatability: 10,
    accuracy: 8,
  },
  {
    id: 'basketball',
    name: 'Basketball',
    description: 'NBA regulation basketball',
    dimension: 'volume',
    value: 7.1,
    unit: 'liter',
    tags: ['sports', 'american', 'universal'],
    relatability: 9,
    accuracy: 9,
  },

  // Kitchen larger
  {
    id: 'pint-volume',
    name: 'Pint',
    description: 'Volume of one US pint',
    dimension: 'volume',
    value: 473,
    unit: 'milliliter',
    tags: ['cooking', 'beverages', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'quart-volume',
    name: 'Quart',
    description: 'Volume of one US quart',
    dimension: 'volume',
    value: 946,
    unit: 'milliliter',
    tags: ['cooking', 'everyday', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'gallon-volume',
    name: 'Gallon',
    description: 'Volume of one US gallon',
    dimension: 'volume',
    value: 3.78,
    unit: 'liter',
    tags: ['cooking', 'everyday', 'american'],
    relatability: 10,
    accuracy: 10,
  },
  {
    id: 'milk-carton',
    name: 'Milk carton',
    description: 'Half-gallon milk carton',
    dimension: 'volume',
    value: 1.89,
    unit: 'liter',
    tags: ['food', 'everyday', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'paint-gallon',
    name: 'Paint gallon can',
    description: 'Standard gallon paint can capacity',
    dimension: 'volume',
    value: 3.78,
    unit: 'liter',
    tags: ['household', 'construction', 'american'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'cooking-pot',
    name: 'Large cooking pot',
    description: 'Volume of a large stock pot',
    dimension: 'volume',
    value: 8,
    unit: 'liter',
    valueMin: 6,
    valueMax: 12,
    tags: ['cooking', 'kitchen', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'fire-extinguisher',
    name: 'Fire extinguisher',
    description: 'Standard 2.5 gallon water fire extinguisher',
    dimension: 'volume',
    value: 9.5,
    unit: 'liter',
    tags: ['safety', 'household', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'helium-balloon',
    name: 'Party helium balloon',
    description: 'Standard 11-inch latex balloon',
    dimension: 'volume',
    value: 14,
    unit: 'liter',
    valueMin: 10,
    valueMax: 18,
    tags: ['party', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'propane-tank-bbq',
    name: 'BBQ propane tank',
    description: '20-pound propane tank for grilling',
    dimension: 'volume',
    value: 17.8,
    unit: 'liter',
    valueMin: 13,
    valueMax: 18,
    tags: ['household', 'cooking', 'american', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'water-cooler-bottle',
    name: 'Water cooler bottle',
    description: 'Standard 5-gallon office water dispenser bottle',
    dimension: 'volume',
    value: 19,
    unit: 'liter',
    tags: ['beverages', 'office', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'aquarium-small',
    name: 'Small aquarium',
    description: '10-gallon fish tank',
    dimension: 'volume',
    value: 38,
    unit: 'liter',
    tags: ['pets', 'household', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'kiddie-pool',
    name: 'Kiddie pool',
    description: 'Small plastic wading pool',
    dimension: 'volume',
    value: 60,
    unit: 'liter',
    valueMin: 40,
    valueMax: 100,
    tags: ['recreation', 'children', 'household', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'aquarium-medium',
    name: 'Medium aquarium',
    description: '30-gallon fish tank',
    dimension: 'volume',
    value: 114,
    unit: 'liter',
    tags: ['pets', 'household', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'oil-barrel',
    name: 'Oil barrel',
    description: 'Standard petroleum barrel',
    dimension: 'volume',
    value: 159,
    unit: 'liter',
    tags: ['industrial', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'aquarium-large',
    name: 'Large aquarium',
    description: '55-gallon fish tank',
    dimension: 'volume',
    value: 208,
    unit: 'liter',
    tags: ['pets', 'household', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'human-bladder',
    name: 'Human bladder',
    description: 'Maximum bladder capacity',
    dimension: 'volume',
    value: 0.7,
    unit: 'liter',
    valueMin: 0.6,
    valueMax: 0.8,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Human body
  {
    id: 'human-stomach',
    name: 'Human stomach capacity',
    description: 'Maximum capacity of an adult human stomach',
    dimension: 'volume',
    value: 1,
    unit: 'liter',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'human-blood-volume',
    name: 'Human blood volume',
    description: 'Total blood in adult human body',
    dimension: 'volume',
    value: 5,
    unit: 'liter',
    valueMin: 4.5,
    valueMax: 5.5,
    tags: ['human-body', 'biology', 'universal'],
    relatability: 8,
    accuracy: 8,
  },
  {
    id: 'human-lung-capacity',
    name: 'Human lung capacity',
    description: 'Total lung capacity of an adult',
    dimension: 'volume',
    value: 6,
    unit: 'liter',
    tags: ['human-body', 'biology', 'universal'],
    relatability: 7,
    accuracy: 8,
  },

  // Household containers
  {
    id: 'bucket',
    name: 'Standard bucket',
    description: 'Volume of a standard 5-gallon bucket',
    dimension: 'volume',
    value: 19,
    unit: 'liter',
    tags: ['household', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 9,
  },
  {
    id: 'small-backpack',
    name: 'Small backpack',
    description: 'Volume of a typical school backpack',
    dimension: 'volume',
    value: 20,
    unit: 'liter',
    valueMin: 15,
    valueMax: 25,
    tags: ['everyday', 'school', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'large-backpack',
    name: 'Large backpack',
    description: 'Volume of a hiking or travel backpack',
    dimension: 'volume',
    value: 45,
    unit: 'liter',
    valueMin: 35,
    valueMax: 55,
    tags: ['travel', 'hiking', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'trash-can-kitchen',
    name: 'Kitchen trash can',
    description: 'Typical kitchen waste bin capacity',
    dimension: 'volume',
    value: 50,
    unit: 'liter',
    valueMin: 35,
    valueMax: 60,
    tags: ['household', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'suitcase-carryon',
    name: 'Carry-on suitcase',
    description: 'Volume of a standard carry-on suitcase',
    dimension: 'volume',
    value: 45,
    unit: 'liter',
    valueMin: 35,
    valueMax: 55,
    tags: ['travel', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'suitcase-large',
    name: 'Large suitcase',
    description: 'Volume of a large checked suitcase',
    dimension: 'volume',
    value: 90,
    unit: 'liter',
    valueMin: 75,
    valueMax: 110,
    tags: ['travel', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'moving-box-small',
    name: 'Small moving box',
    description: 'Volume of a small packing box',
    dimension: 'volume',
    value: 42,
    unit: 'liter',
    tags: ['household', 'moving', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'moving-box-medium',
    name: 'Medium moving box',
    description: 'Volume of a medium packing box',
    dimension: 'volume',
    value: 85,
    unit: 'liter',
    tags: ['household', 'moving', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'moving-box-large',
    name: 'Large moving box',
    description: 'Volume of a large packing box',
    dimension: 'volume',
    value: 127,
    unit: 'liter',
    tags: ['household', 'moving', 'universal'],
    relatability: 8,
    accuracy: 9,
  },
  {
    id: 'trash-can-outdoor',
    name: 'Outdoor trash can',
    description: 'Large outdoor waste bin capacity',
    dimension: 'volume',
    value: 120,
    unit: 'liter',
    valueMin: 90,
    valueMax: 150,
    tags: ['household', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },

  // Appliances
  {
    id: 'washing-machine-capacity',
    name: 'Washing machine drum',
    description: 'Capacity of a standard washing machine',
    dimension: 'volume',
    value: 110,
    unit: 'liter',
    valueMin: 80,
    valueMax: 150,
    tags: ['household', 'appliances', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'clothes-dryer-capacity',
    name: 'Clothes dryer drum',
    description: 'Capacity of a standard clothes dryer',
    dimension: 'volume',
    value: 170,
    unit: 'liter',
    valueMin: 140,
    valueMax: 200,
    tags: ['household', 'appliances', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'refrigerator-capacity',
    name: 'Refrigerator',
    description: 'Total capacity of a standard refrigerator',
    dimension: 'volume',
    value: 566,
    unit: 'liter',
    valueMin: 400,
    valueMax: 700,
    tags: ['household', 'appliances', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'bathtub',
    name: 'Bathtub',
    description: 'Volume of water in a full bathtub',
    dimension: 'volume',
    value: 300,
    unit: 'liter',
    valueMin: 200,
    valueMax: 400,
    tags: ['household', 'everyday', 'universal'],
    relatability: 10,
    accuracy: 6,
  },
  {
    id: 'hot-tub',
    name: 'Hot tub',
    description: 'Volume of a standard hot tub',
    dimension: 'volume',
    value: 1500,
    unit: 'liter',
    valueMin: 1000,
    valueMax: 2000,
    tags: ['household', 'recreation', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'beer-keg-quarter',
    name: 'Quarter barrel keg',
    description: 'Pony keg, standard party size',
    dimension: 'volume',
    value: 29.3,
    unit: 'liter',
    tags: ['beverages', 'alcohol', 'party', 'universal'],
    relatability: 7,
    accuracy: 10,
  },
  {
    id: 'beer-keg-half',
    name: 'Half barrel keg',
    description: 'Full-size beer keg',
    dimension: 'volume',
    value: 58.7,
    unit: 'liter',
    tags: ['beverages', 'alcohol', 'universal'],
    relatability: 8,
    accuracy: 10,
  },

  // Vehicles
  {
    id: 'car-gas-tank',
    name: 'Car gas tank',
    description: 'Average car fuel tank capacity',
    dimension: 'volume',
    value: 50,
    unit: 'liter',
    valueMin: 40,
    valueMax: 70,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 6,
  },
  {
    id: 'car-trunk',
    name: 'Car trunk',
    description: 'Cargo volume of a typical sedan trunk',
    dimension: 'volume',
    value: 450,
    unit: 'liter',
    valueMin: 350,
    valueMax: 550,
    tags: ['vehicles', 'everyday', 'universal'],
    relatability: 9,
    accuracy: 7,
  },
  {
    id: 'pickup-truck-bed',
    name: 'Pickup truck bed',
    description: 'Cargo volume of a standard pickup truck bed',
    dimension: 'volume',
    value: 1800,
    unit: 'liter',
    valueMin: 1400,
    valueMax: 2500,
    tags: ['vehicles', 'american', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'fuel-truck',
    name: 'Fuel tanker truck',
    description: 'Capacity of a fuel tanker truck',
    dimension: 'volume',
    value: 34000,
    unit: 'liter',
    valueMin: 20000,
    valueMax: 45000,
    tags: ['vehicles', 'industrial', 'universal'],
    relatability: 6,
    accuracy: 6,
  },
  {
    id: 'boeing-747-fuel',
    name: 'Boeing 747 fuel tank',
    description: 'Fuel capacity of Boeing 747-400',
    dimension: 'volume',
    value: 216840,
    unit: 'liter',
    tags: ['aviation', 'vehicles', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'space-shuttle-external-tank',
    name: 'Space Shuttle external tank',
    description: 'Total propellant capacity',
    dimension: 'volume',
    value: 2040000,
    unit: 'liter',
    tags: ['space', 'aviation', 'american'],
    relatability: 6,
    accuracy: 9,
  },

  // Rooms
  {
    id: 'bedroom-volume',
    name: 'Bedroom',
    description: 'Volume of a standard bedroom',
    dimension: 'volume',
    value: 40,
    unit: 'cubic-meter',
    valueMin: 30,
    valueMax: 60,
    tags: ['household', 'architecture', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'garage-volume',
    name: 'One-car garage',
    description: 'Volume of a single-car garage',
    dimension: 'volume',
    value: 80,
    unit: 'cubic-meter',
    valueMin: 60,
    valueMax: 100,
    tags: ['household', 'architecture', 'universal'],
    relatability: 8,
    accuracy: 6,
  },
  {
    id: 'dumpster-10-yard',
    name: '10-yard dumpster',
    description: 'Small construction dumpster',
    dimension: 'volume',
    value: 7.65,
    unit: 'cubic-meter',
    tags: ['construction', 'industrial', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'dumpster-20-yard',
    name: '20-yard dumpster',
    description: 'Medium construction dumpster',
    dimension: 'volume',
    value: 15.3,
    unit: 'cubic-meter',
    tags: ['construction', 'industrial', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'dumpster-30-yard',
    name: '30-yard dumpster',
    description: 'Large construction dumpster',
    dimension: 'volume',
    value: 22.9,
    unit: 'cubic-meter',
    tags: ['construction', 'industrial', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'semi-trailer',
    name: 'Semi truck trailer',
    description: 'Cargo volume of 53-foot trailer',
    dimension: 'volume',
    value: 115,
    unit: 'cubic-meter',
    valueMin: 100,
    valueMax: 120,
    tags: ['vehicles', 'industrial', 'american', 'universal'],
    relatability: 7,
    accuracy: 7,
  },
  {
    id: 'average-house',
    name: 'Average house',
    description: 'Interior volume of typical single-family home',
    dimension: 'volume',
    value: 580,
    unit: 'cubic-meter',
    valueMin: 400,
    valueMax: 800,
    tags: ['household', 'architecture', 'universal'],
    relatability: 8,
    accuracy: 6,
  },

  // Pools and large containers
  {
    id: 'shipping-container',
    name: 'Shipping container',
    description: 'Volume of a 40-foot shipping container',
    dimension: 'volume',
    value: 67.7,
    unit: 'cubic-meter',
    tags: ['industrial', 'logistics', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'residential-pool',
    name: 'Residential swimming pool',
    description: 'Volume of a typical backyard pool',
    dimension: 'volume',
    value: 72,
    unit: 'cubic-meter',
    valueMin: 40,
    valueMax: 100,
    tags: ['recreation', 'household', 'universal'],
    relatability: 8,
    accuracy: 7,
  },
  {
    id: 'olympic-pool',
    name: 'Olympic swimming pool',
    description: 'Volume of an Olympic-size swimming pool',
    dimension: 'volume',
    value: 2500,
    unit: 'cubic-meter',
    tags: ['sports', 'universal'],
    relatability: 9,
    accuracy: 10,
  },
  {
    id: 'grain-silo',
    name: 'Grain silo',
    description: 'Capacity of a typical grain storage silo',
    dimension: 'volume',
    value: 1500,
    unit: 'cubic-meter',
    valueMin: 500,
    valueMax: 5000,
    tags: ['agriculture', 'industrial', 'universal'],
    relatability: 6,
    accuracy: 6,
  },
  {
    id: 'warehouse',
    name: 'Warehouse',
    description: 'Volume of a medium-sized warehouse',
    dimension: 'volume',
    value: 15000,
    unit: 'cubic-meter',
    valueMin: 5000,
    valueMax: 30000,
    tags: ['industrial', 'commercial', 'universal'],
    relatability: 6,
    accuracy: 6,
  },

  // Large structures
  {
    id: 'great-pyramid',
    name: 'Great Pyramid of Giza',
    description: 'Volume of the Great Pyramid',
    dimension: 'volume',
    value: 2600000,
    unit: 'cubic-meter',
    tags: ['architecture', 'history', 'universal'],
    relatability: 7,
    accuracy: 8,
  },
  {
    id: 'superdome',
    name: 'Superdome',
    description: 'Interior volume of the New Orleans Superdome',
    dimension: 'volume',
    value: 3500000,
    unit: 'cubic-meter',
    tags: ['sports', 'architecture', 'american'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'boeing-factory',
    name: 'Boeing Everett Factory',
    description: 'Volume of the largest building by volume',
    dimension: 'volume',
    value: 13376000,
    unit: 'cubic-meter',
    tags: ['industrial', 'architecture', 'american'],
    relatability: 5,
    accuracy: 10,
  },
  {
    id: 'empire-state-building-volume',
    name: 'Empire State Building',
    description: 'Interior volume of iconic skyscraper',
    dimension: 'volume',
    value: 1000000,
    unit: 'cubic-meter',
    tags: ['architecture', 'american', 'universal'],
    relatability: 7,
    accuracy: 9,
  },
  {
    id: 'grand-canyon',
    name: 'Grand Canyon',
    description: 'Total volume of the Grand Canyon',
    dimension: 'volume',
    value: 4170,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 8,
  },

  // Large natural
  {
    id: 'oil-supertanker',
    name: 'Oil supertanker capacity',
    description: 'Cargo capacity of a large oil tanker',
    dimension: 'volume',
    value: 500000,
    unit: 'cubic-meter',
    valueMin: 300000,
    valueMax: 550000,
    tags: ['ships', 'industrial', 'universal'],
    relatability: 6,
    accuracy: 7,
  },

  // Geographic
  {
    id: 'lake-tahoe-volume',
    name: 'Lake Tahoe volume',
    description: 'Volume of water in Lake Tahoe',
    dimension: 'volume',
    value: 150.7,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'caspian-sea-volume',
    name: 'Caspian Sea volume',
    description: 'Largest inland body of water by volume',
    dimension: 'volume',
    value: 78200,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'great-lakes-total',
    name: 'Great Lakes total volume',
    description: 'Combined volume of all five Great Lakes',
    dimension: 'volume',
    value: 22671,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'lake-baikal',
    name: 'Lake Baikal volume',
    description: "World's largest freshwater lake by volume",
    dimension: 'volume',
    value: 23615,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'lake-superior-volume',
    name: 'Lake Superior volume',
    description: 'Volume of the largest Great Lake',
    dimension: 'volume',
    value: 12100,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'american'],
    relatability: 6,
    accuracy: 8,
  },
  {
    id: 'black-sea',
    name: 'Black Sea volume',
    description: 'Total volume of the Black Sea',
    dimension: 'volume',
    value: 547000,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'mediterranean-sea-volume',
    name: 'Mediterranean Sea volume',
    description: 'Total volume of the Mediterranean Sea',
    dimension: 'volume',
    value: 3750000,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },
  {
    id: 'all-ocean-water',
    name: 'All ocean water',
    description: "Total volume of Earth's oceans",
    dimension: 'volume',
    value: 1.335e9,
    unit: 'cubic-kilometer',
    tags: ['geography', 'nature', 'universal'],
    relatability: 5,
    accuracy: 8,
  },

  // Astronomical
  {
    id: 'mercury-volume',
    name: 'Mercury volume',
    description: 'Total volume of planet Mercury',
    dimension: 'volume',
    value: 6.08e10,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'moon-volume',
    name: 'Moon volume',
    description: 'Total volume of the Moon',
    dimension: 'volume',
    value: 2.2e10,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'venus-volume',
    name: 'Venus volume',
    description: 'Total volume of planet Venus',
    dimension: 'volume',
    value: 9.28e11,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'mars-volume',
    name: 'Mars volume',
    description: 'Total volume of planet Mars',
    dimension: 'volume',
    value: 1.632e11,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 9,
  },
  {
    id: 'earth-volume',
    name: 'Earth volume',
    description: 'Total volume of planet Earth',
    dimension: 'volume',
    value: 1.08321e12,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 6,
    accuracy: 10,
  },
  {
    id: 'jupiter-volume',
    name: 'Jupiter volume',
    description: 'Total volume of planet Jupiter',
    dimension: 'volume',
    value: 1.43e15,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'uranus-volume',
    name: 'Uranus volume',
    description: 'Total volume of planet Uranus',
    dimension: 'volume',
    value: 6.83e13,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'neptune-volume',
    name: 'Neptune volume',
    description: 'Total volume of planet Neptune',
    dimension: 'volume',
    value: 6.3e13,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'saturn-volume',
    name: 'Saturn volume',
    description: 'Total volume of planet Saturn',
    dimension: 'volume',
    value: 8.27e14,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'planetary', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
  {
    id: 'sun-volume',
    name: 'Sun volume',
    description: 'Total volume of the Sun',
    dimension: 'volume',
    value: 1.41e18,
    unit: 'cubic-kilometer',
    tags: ['astronomy', 'universal'],
    relatability: 5,
    accuracy: 9,
  },
];
